Repository scratchfoundation/scratch-www, pull requests merged in 2018-12, with the labels that each got.

#2371 [Master] No localhost allowed on HoC Banner
  src/views/splash/hoc/middle-banner.jsx
Labels: hotfix

#2346 Display green "Shared" banner after user shares; bring CSS into line with spec
  src/_colors.scss
  src/views/preview/banner.jsx
  src/views/preview/banner.scss
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2184 Thumbnail Fix
  src/views/microworld/fashion/fashion.json
  src/views/microworld/hiphop/hiphop.json
Labels: pr - good to merge

#2375 [Master] Add project data to adventure game tutorial
  src/views/splash/hoc/top-banner.jsx
Labels: hotfix, pr - good to merge

#2372 Add es6-promise polyfill to fix browsers lacking promise.finally
  static/js/polyfill.min.js
Labels: pr - good to merge

#2377 Point scratch-gui dependency back to develop tag
  package.json
Labels: pr - needs review

#2378 Track isScratcher status and pass hasCloudPermission flag to gui.
  src/views/preview/presentation.jsx
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2374 Add missing tutorial shortcuts
  src/routes.json
Labels: pr - good to merge

#2379 Refresh the data related to the project json on switch back from editor
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2380 Update Windows version requirement on hardware extension landing pages
  src/components/extension-landing/extension-header.jsx
  src/components/extension-landing/extension-landing.scss
  src/views/ev3/ev3.jsx
  src/views/ev3/l10n.json
  src/views/microbit/l10n.json
  src/views/microbit/microbit.jsx
  src/views/microbit/microbit.scss
  src/views/wedo2/l10n.json
  src/views/wedo2/wedo2.jsx
  static/images/microbit/microbit-heart.png
Labels: pr - good to merge

#2393 project page will no longer vanish when project metadata update fails on the backend
  src/redux/preview.js
Labels: pr - good to merge

#2394 Use message instead of censorMessage for the censor message.
  src/views/preview/presentation.jsx
  src/views/preview/project-view.jsx
Labels: pr - needs review

#2389 Show NotAvailable for invalid URL
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2401 Allow admins to see share banner
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2407 Fix image path bug and capitalization CBs name.
  src/views/credits/people.json
  src/views/credits/supporters.json
Labels: pr - good to merge

#2404 Admin panel for the project page
  src/components/adminpanel/adminpanel.jsx
  src/components/adminpanel/adminpanel.scss
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
  src/views/preview/project-view.jsx
  src/views/splash/presentation.jsx
  src/views/splash/splash.scss
Labels: pr - good to merge

#2405 Add videos to WeDo and EV3 landing pages
  src/components/extension-landing/extension-landing.scss
  src/components/extension-landing/extension-video.jsx
  src/views/ev3/ev3.jsx
  src/views/wedo2/wedo2.jsx
Labels: pr - good to merge

#2406 show embed view
  bin/configure-fastly.js
  src/routes.json
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2413 Match scratchr2 admin panel behavior more closely
  src/components/adminpanel/adminpanel.jsx
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
  src/views/preview/project-view.jsx
  src/views/splash/presentation.jsx
  src/views/splash/splash.jsx
Labels: pr - good to merge

#2408 Remix button progress spinner & banner message showing that user has remixed
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2419 Fix admin panel visibility and style
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2420 Fix lint issues
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2422 Remove share button on censored project banner.
  src/views/preview/presentation.jsx
Labels: pr - good to merge

#2423 Show addToStudio for all logged in users on shared projects
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2424 Allow admins to toggle comments
  src/views/preview/presentation.jsx
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2417 pass onGreenFlag to GUI; when called, call API to register project view
  src/redux/preview.js
  src/views/preview/presentation.jsx
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2430 Use falsey check for shareDate instead of checking for null.
  src/views/preview/subactions.jsx
Labels: pr - good to merge

#2425 Don't occlude page content with the admin panel
  src/components/page/www/page.jsx
  src/views/preview/preview.scss
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2431 Only try to update fave counts if there are no requests in progress.
  src/views/preview/project-view.jsx
Labels: pr - needs review

#2440 Translate placeholder
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
Labels: pr - good to merge

#2427 Add moderator info for sb2 projects
  src/views/preview/presentation.jsx
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2387 Redirect /info/cards route to /ideas
  src/routes.json
  src/views/cards/cards.jsx
  src/views/cards/cards.scss
  src/views/cards/l10n-static.json
  src/views/cards/l10n.json
Labels: pr - good to merge

#2433 Show username and cloud var alerts on projects that use them.
  src/lib/project-info.js
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2437 Placeholder text go away
  src/views/preview/preview.scss
Labels: pr - good to merge

#2447 Educators Page Changes
  src/views/teachers/landing/l10n.json
  src/views/teachers/landing/landing.jsx
  src/views/teachers/landing/landing.scss
  static/svgs/teachers/coding-cards-icon.svg
  static/svgs/teachers/ideas-page-icon.svg
  static/svgs/teachers/scratch-tutorials-icons.svg
Labels: pr - good to merge

#2463 Actually return the mapping of extension info
  src/lib/project-info.js
Labels: pr - good to merge

#2460 Make the remix button spin the correct the direction
  src/views/preview/preview.scss
Labels: pr - good to merge

#2443 Update extension landing pages
  src/views/ev3/ev3.jsx
  src/views/ev3/l10n.json
  src/views/microbit/microbit.jsx
  src/views/wedo2/l10n.json
  src/views/wedo2/wedo2.jsx
  static/images/ev3/ev3-starter1.png
  static/images/ev3/ev3-starter2.png
  static/images/ev3/ev3-starter3.png
  static/images/ev3/starter-distance-instrument.png
  static/images/ev3/starter-wave-hello.png
  static/images/wedo2/wedo2-starter1.png
  static/images/wedo2/wedo2-starter2.png
  static/images/wedo2/wedo2-starter3.png
Labels: pr - good to merge

#2448 Use custom meta tag info for project page.
  package.json
  src/views/preview/meta.jsx
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2445 Fix hard-coded /preview/id url for remix list.
  src/components/thumbnailcolumn/thumbnailcolumn.jsx
  src/views/preview/remix-list.jsx
Labels: pr - good to merge

#2452 if remix parent or original is unshared, don't crash project page
  src/redux/preview.js
  src/views/preview/remix-credit.jsx
Labels: pr - good to merge

#2464 Minor style fixes to the project page
  src/views/preview/comment/comment.scss
  src/views/preview/extension-chip.scss
  src/views/preview/mod-info.jsx
  src/views/preview/mod-info.scss
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
  src/views/preview/stats.scss
  src/views/preview/subactions.scss
Labels: pr - good to merge

#2459 Hook up onClickLogo in GUI
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2451 minor educator pages fixes
  src/views/teachers/landing/landing.scss
Labels: pr - good to merge

#2470 Issue/2318 launch banner
  src/_colors.scss
  src/views/splash/beta/middle-banner.jsx
  src/views/splash/beta/top-banner.jsx
  src/views/splash/beta/top-banner.scss
  src/views/splash/feature/middle-banner.jsx
  src/views/splash/feature/middle-banner.scss
  src/views/splash/feature/small-top-banner.jsx
  src/views/splash/feature/small-top-banner.scss
  src/views/splash/feature/top-banner.jsx
  src/views/splash/feature/top-banner.scss
  src/views/splash/hoc/hoc-banner.scss
  src/views/splash/hoc/middle-banner.jsx
  src/views/splash/hoc/top-banner.jsx
  src/views/splash/l10n.json
  src/views/splash/presentation.jsx
  static/images/beta/left-illustration.png
  static/images/beta/right-illustration.png
  static/images/feature/bg-pattern.png
  static/svgs/feature/banner-notch.svg
  static/svgs/feature/create-icon.svg
  static/svgs/feature/illustration-left.svg
  static/svgs/feature/illustration-right.svg
  static/svgs/feature/tapping-block.svg
Labels: pr - good to merge

#2457 Fix scrollbars for add-to-studio modal
  src/components/modal/addtostudio/modal.scss
Labels: pr - good to merge

#2455 Ideas page
  .tx/config
  src/components/footer/www/footer.jsx
  src/components/masonrygrid/masonrygrid.scss
  src/components/modal/ttt/modal.jsx
  src/components/modal/ttt/modal.scss
  src/components/navigation/www/navigation.jsx
  src/components/ttt-tile/ttt-tile.jsx
  src/components/ttt-tile/ttt-tile.scss
  src/l10n.json
  src/routes.json
  src/views/ideas/ideas.jsx
  src/views/ideas/ideas.scss
  src/views/ideas/l10n-static.json
  src/views/ideas/l10n.json
  src/views/ideas/ttt.json
  src/views/microworld/art/art.json
  src/views/microworld/art/art.jsx
  src/views/microworld/fashion/fashion.json
  src/views/microworld/fashion/fashion.jsx
  src/views/microworld/hiphop/hiphop.json
  src/views/microworld/hiphop/hiphop.jsx
  src/views/microworld/soccer/soccer.json
  src/views/microworld/soccer/soccer.jsx
  src/views/microworldshomepage/l10n.json
  src/views/microworldshomepage/microworlds.json
  src/views/microworldshomepage/microworldshomepage.jsx
  src/views/microworldshomepage/microworldshomepage.scss
  static/images/ideas/activities/animate-a-character-modal.jpg
  static/images/ideas/activities/animate-a-character-thumb.jpg
  static/images/ideas/activities/animate-a-name-modal.jpg
  static/images/ideas/activities/animate-a-name-thumb.jpg
  static/images/ideas/activities/chase-game-modal.jpg
  static/images/ideas/activities/chase-game-thumb.jpg
  static/images/ideas/activities/create-a-story-modal.jpg
  static/images/ideas/activities/create-a-story-thumb.jpg
  static/images/ideas/activities/make-music-modal.jpg
  static/images/ideas/activities/make-music-thumb.jpg
  static/images/ideas/activities/video-sensing-modal.jpg
  static/images/ideas/activities/video-sensing-thumb.jpg
  static/images/ideas/bulb-icon.svg
  static/images/ideas/cards-illustration.svg
  static/images/ideas/coding-cards-icon.svg
  static/images/ideas/download-icon.svg
  static/images/ideas/educator-guide-icon.svg
  static/images/ideas/getting-started-illustration.svg
  static/images/ideas/left-juice.png
  static/images/ideas/masthead-illustration.svg
  static/images/ideas/right-juice.png
  static/images/ideas/starter-projects-illustration.svg
  static/images/ideas/try-it-icon.svg
Labels: pr - good to merge

#2479 don't use flex-row class to wrap instructions and credits
  src/views/preview/presentation.jsx
Labels: pr - good to merge

#2478 Add proper links to cards and guides instead of hard coding them.
  src/views/teachers/landing/l10n-static.json
  src/views/teachers/landing/landing.jsx
Labels: pr - good to merge

#2482 Update tests
  test/integration/smoke-testing/test_footer_links.js
  test/integration/smoke-testing/test_navbar_links.js
Labels: pr - good to merge

#2474 Download content updates
  src/views/download/download.jsx
  src/views/download/download.scss
  src/views/download/l10n.json
  static/images/download/icon.png
  static/images/download/mac-install.png
  static/images/download/windows-install.png
Labels: pr - needs review

#2487 Add ideas page to tx/config, and remove cards view
  .tx/config
Labels: localization, pr - good to merge

#2497 Add flag for dynamic meta tags in the template
  src/routes.json
  src/template.ejs
  webpack.config.js
Labels: pr - needs review

#2500 pass onUpdateProjectThumbnail to gui when on project page
  src/views/preview/presentation.jsx
  src/views/preview/project-view.jsx
Labels: pr - needs review

#2495 Remove tutorial for logged in users.
  src/views/splash/presentation.jsx
Labels: critical, pr - good to merge

#2505 Remove approx liking/favoriting format
  package.json
  src/views/preview/stats.jsx
Labels: pr - good to merge

#2506 added author username to moderation info area
  src/views/preview/mod-info.jsx
  src/views/preview/mod-info.scss
  src/views/preview/presentation.jsx
  src/views/preview/project-view.jsx
  static/svgs/project/username.svg
Labels: pr - good to merge

#2502 Fix the ideas page's getting started SVG
  static/images/ideas/getting-started-illustration.svg
Labels: pr - good to merge

#2498 Fix some spacing issues on the download page. Adds a more padding und…
  src/views/download/download.jsx
  src/views/download/download.scss
Labels: pr - good to merge

#2510 Show error ID and report React errors to Sentry
  src/components/crashmessage/crashmessage.jsx
  src/components/errorboundary/errorboundary.jsx
  src/l10n.json
Labels: pr - good to merge

#2509 admins should not see editable project title in editor
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2508 switch to editor after remixing from project page
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2511 Parents page
  src/views/parents/l10n.json
  src/views/parents/parents.jsx
Labels: pr - good to merge

#2515 Set isRemixing to true and then start remixing process
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2525 Update storage to get 3.0 projects.
  src/lib/storage.js
Labels: pr - good to merge

#2523 FAQ updates from Champikaf
  src/routes.json
  src/views/faq/faq.jsx
  src/views/faq/l10n.json
Labels: critical, pr - needs work

#2527 Add people to acknowledgements. Move credits from /info/credits to /cr…
  src/routes.json
  src/views/credits/credits.jsx
  src/views/credits/l10n.json
Labels: pr - good to merge

#2526 Implement new Intro masthead
  src/_colors.scss
  src/components/intro/intro.jsx
  src/components/intro/intro.scss
  src/components/video/video.jsx
  src/components/video/video.scss
  src/views/splash/feature/top-banner.jsx
  src/views/splash/l10n.json
  src/views/splash/presentation.jsx
  static/svgs/intro/background-cropped.svg
  static/svgs/intro/background.svg
  static/svgs/intro/create.svg
  static/svgs/intro/hat-block.svg
  static/svgs/intro/join.svg
  static/svgs/intro/video-image.svg
Labels: critical, needs discussion

#2530 Use sentry webpack instead of Raven
  .travis.yml
  package.json
  src/components/errorboundary/errorboundary.jsx
  src/init.js
  src/template.ejs
  src/views/preview/project-view.jsx
  webpack.config.js
Labels: pr - needs review

#2531 Add a staging GA tracker for testing
  .travis.yml
Labels: pr - good to merge

#2533 Add an illustrator
  src/views/credits/credits.jsx
Labels: pr - good to merge

#2536 Credits link has changed
  test/integration/smoke-testing/test_footer_links.js
Labels: pr - good to merge

#2542 Fix the studio links to use the correct URL
  src/views/preview/studio-list.jsx
Labels: pr - needs review

#2543 Bring in the min sizes for GUI to allow scrollable UI
  src/views/preview/preview.scss
Labels: pr - good to merge

#2546 Pin to a specific version of scratch-gui
  package.json
Labels: critical, pr - good to merge
