Repository scratchfoundation/scratch-www, pull requests merged in 2018-03, with the labels that each got.

#1822 February 2018 Release
  src/components/footer/www/footer.jsx
  src/l10n.json
  src/views/conference/2018/index/index.jsx
  src/views/conference/2018/index/index.scss
  src/views/conference/2018/index/l10n.json
  src/views/search/search.jsx
  src/views/search/search.scss
  test/integration/smoke-testing/test_footer_links.js
  webpack.config.js
Labels: pr - needs review

#1830 Fix gh-1824: Add note about real names
  src/components/registration/steps.jsx
  src/l10n.json
Labels: needs-qa, pr - good to merge

#1835 Fix gh-1825: Remove filled jobs
  src/views/jobs/jobs.jsx
Labels: needs-qa

#1690 Don't run UglifyJS unless it's a production build
  webpack.config.js
Labels: ergonomics, pr - good to merge

#1833 Feature/preview project
  .babelrc
  package.json
  src/_colors.scss
  src/components/cappednumber/cappednumber.jsx
  src/components/remixlist/remixlist.jsx
  src/components/remixlist/remixlist.scss
  src/components/share-banner/share-banner.jsx
  src/components/share-banner/share-banner.scss
  src/components/thumbnailcolumn/thumbnailcolumn.jsx
  src/components/thumbnailcolumn/thumbnailcolumn.scss
  src/redux/preview.js
  src/routes.json
  src/views/preview/gui-placeholder.png
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  src/views/preview/preview.scss
Labels: pr - good to merge

#1836 Add cypress tests
  .eslintignore
  .gitignore
  package.json
  test/integration-cypress/.eslintrc
  test/integration-cypress/README.md
  test/integration-cypress/cypress.json
  test/integration-cypress/cypress/smoke-tests/test-footer-links.js
  test/integration-cypress/cypress/smoke-tests/test-navbar-links.js
  test/integration-cypress/package.json
Labels: pr - good to merge

#1826 Clarify README and fix link on README to testing guide
  README.md
Labels: pr - good to merge
