Repository scratchfoundation/scratch-www, pull requests merged in 2018-09, with the labels that each got.

#2064 Added Katelyn to credits page
  src/views/credits/credits.jsx
Labels: pr - good to merge

#2022 split account nav into its own component, pass logout callback to GUI
  src/components/navigation/www/accountnav.jsx
  src/components/navigation/www/accountnav.scss
  src/components/navigation/www/navigation.jsx
  src/components/navigation/www/navigation.scss
  src/views/preview/preview.jsx
Labels: needs-qa, pr - good to merge

#2068 moved dispatched navigation function calls to mapDispatchToProps
  src/components/navigation/www/navigation.jsx
Labels: needs-qa, pr - good to merge

#2052 pass project title to GUI, and disable submit when editing title
  src/lib/render.jsx
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
Labels: feature, pr - good to merge

#2043 Keep title on preview project page from overflowing or otherwise messing up the layout
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
Labels: pr - good to merge

#2046 Fix appearance of studio thumbnails on preview project page
  src/components/thumbnail/thumbnail.jsx
  src/components/thumbnailcolumn/thumbnailcolumn.scss
  src/views/preview/preview.scss
  src/views/preview/remix-list.jsx
  src/views/preview/studio-list.jsx
Labels: needs-qa, pr - good to merge

#2073 Animate add-to-studio-buttons on preview project page
  src/components/login/login.jsx
  src/components/login/login.scss
  src/components/modal/addtostudio/animate-hoc.jsx
  src/components/modal/addtostudio/modal.scss
  src/components/modal/addtostudio/presentation.jsx
  src/components/modal/addtostudio/studio-button.jsx
  src/components/modal/report/modal.jsx
  src/components/spinner/spinner.jsx
  src/components/spinner/spinner.scss
  src/views/components/components.jsx
  src/views/preview/preview.jsx
  src/views/studentcompleteregistration/studentcompleteregistration.jsx
  static/svgs/modal/spinner-blue.svg
  static/svgs/modal/spinner-transparent-gray.svg
  static/svgs/modal/spinner-white.svg
  static/svgs/modal/spinner.svg
Labels: needs-qa, pr - good to merge

#2083 Fix notfications box, player box, buttons and icons alignments
  src/views/preview/preview.scss
  src/views/preview/remix-credit.jsx
Labels: pr - good to merge

#2078 move login/registration functions and view state to session reducer, pass to gui
  src/components/dropdown/dropdown.scss
  src/components/intro/intro.jsx
  src/components/login/canceled-deletion-modal.jsx
  src/components/login/connected-login.jsx
  src/components/login/login-dropdown.jsx
  src/components/login/login-dropdown.scss
  src/components/login/login.jsx
  src/components/login/login.scss
  src/components/modal/base/modal.jsx
  src/components/navigation/www/accountnav.jsx
  src/components/navigation/www/navigation.jsx
  src/components/navigation/www/navigation.scss
  src/components/registration/registration.jsx
  src/redux/navigation.js
  src/redux/reducer.js
  src/views/preview/preview.jsx
  src/views/search/search.jsx
  src/views/studentcompleteregistration/studentcompleteregistration.jsx
Labels: needs-qa

#2077 fixed errors in splash page that appear in develop
  src/redux/splash.js
  src/views/splash/presentation.jsx
Labels: bug, pr - good to merge

#2102 fixed smoke tests to use non-exclusive class locators
  test/integration/smoke-testing/test-my-stuff.js
  test/integration/smoke-testing/test_project_rows.js
  test/integration/smoke-testing/test_signing_in_and_out_discuss.js
  test/integration/smoke-testing/test_signing_in_and_out_homepage.js
Labels: pr - good to merge

#2075 Fix gh-1934: Search bar special chars
  src/views/search/search.jsx
Labels: pr - good to merge

#2112 Removed moderator position from jobs page
  src/views/jobs/jobs.jsx
Labels: pr - good to merge

#2119 Track scratch-gui@develop
  package.json
Labels: pr - good to merge

#2120 Add placeholder share handler
  src/views/preview/preview.jsx
Labels: pr - good to merge

#2098 Fix gh-1930: Teacher registration dates
  src/components/registration/steps.jsx
Labels: needs-qa, pr - good to merge

#2099 Made comments fade out look nice in Safari too
  src/_colors.scss
  src/views/preview/comment/comment.scss
Labels: pr - good to merge

#2116 Thumbnailcolumns appear at bottom on mobile
  src/components/thumbnailcolumn/thumbnailcolumn.scss
  src/views/preview/preview.scss
Labels: pr - good to merge
