Repository scratchfoundation/scratch-www, pull requests merged in 2018-10, with the labels that each got.

#2117 Made comments look better on mobile
  src/views/preview/preview.scss
Labels: pr - good to merge

#2118 Made project notes look better on mobile
  src/views/preview/preview.scss
Labels: pr - good to merge

#2105 If in landscape format on mobile, switch to fullscreen mode
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
Labels: needs-qa, pr - good to merge

#2109 Stats and subactions are responsive and separate components
  src/components/modal/report/modal.scss
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
  src/views/preview/stats.jsx
  src/views/preview/stats.scss
  src/views/preview/subactions.jsx
  src/views/preview/subactions.scss
Labels: pr - good to merge

#2138 Positioning remix credit text correctly
  src/views/preview/preview.scss
Labels: pr - good to merge

#2136 New project page: See inside and remix buttons disappear on mobile
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
Labels: pr - good to merge

#2135 Make header of new project page look good on mobile
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
Labels: pr - good to merge

#2145 if the report or add to studio modals are open, don't switch to fulls…
  src/views/preview/preview.jsx
Labels: pr - good to merge

#2107 Make container smaller for mobile to allow for space left and right
  src/views/preview/preview.scss
Labels: pr - good to merge

#2152 [new project page] share date is passed as a prop to subactions component
  src/views/preview/presentation.jsx
  src/views/preview/subactions.jsx
Labels: pr - good to merge

#2146 storage.js can use PROJECT_HOST env setting
  src/lib/storage.js
Labels: pr - needs review

#2150 Add comments to projects and replies to comments
  src/components/forms/inplace-input.scss
  src/redux/preview.js
  src/views/preview/comment/comment.jsx
  src/views/preview/comment/comment.scss
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/comment/top-level-comment.jsx
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
Labels: pr - good to merge

#2153 Move media queries used in responsive project page to frameless
  src/_frameless.scss
  src/components/modal/addtostudio/modal.scss
  src/components/modal/base/modal.scss
  src/components/modal/report/modal.scss
  src/views/preview/preview.scss
  src/views/preview/stats.scss
  src/views/preview/subactions.scss
Labels: pr - good to merge

#2137 Change scratch link icon
  static/images/scratchlink/mac-toolbar.png
  static/images/scratchlink/windows-toolbar.png
  static/svgs/extensions/scratch-link.svg
Labels: pr - good to merge

#2165 fix modal prop
  src/components/modal/base/modal.jsx
Labels: needs-qa, pr - good to merge

#2170 Update API_HOST_STAGING to point to api.scratch.ly
  .travis.yml
Labels: pr - good to merge

#2171 Add comment toggling for the preview page
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  src/views/preview/preview.scss
Labels: needs-qa, pr - good to merge

#2164 Comment report action and modal flow for deleting
  src/components/modal/comments/delete-comment.jsx
  src/components/modal/comments/modal.scss
  src/components/modal/comments/report-comment.jsx
  src/l10n.json
  src/redux/preview.js
  src/views/preview/comment/comment.jsx
  src/views/preview/comment/comment.scss
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/comment/top-level-comment.jsx
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
Labels: needs-qa, pr - needs review

#2176 fix ReactModal bodyOpenClassName error so that it is entirely omitted…
  src/components/modal/base/modal.jsx
Labels: bug

#2174 Prevent replying when comments are turned off
  src/views/preview/presentation.jsx
Labels: pr - good to merge

#2179 Fix Select Menu in Messages Section
  src/components/forms/select.scss
Labels: pr - good to merge

#2161 Fix gh-2160: Search with %
  src/views/search/search.jsx
Labels: pr - needs review

#2181 made account menu have min-width, changed max-width to rem from px
  src/components/dropdown/dropdown.scss
Labels: pr - needs review

#2191 Fix comment delete endpoint
  src/redux/preview.js
Labels: pr - good to merge

#2190 Use the proper API route for reporting projects
  src/redux/preview.js
  src/views/preview/preview.jsx
Labels: pr - good to merge

#2173 Localize all the comment related strings
  src/l10n.json
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/comment/top-level-comment.jsx
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
Labels: pr - good to merge

#2187 set explicit capabilities like “can____” for GUI and project page
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  src/views/preview/subactions.jsx
Labels: pr - good to merge

#2196 Make share banner work on preview
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  src/views/preview/share-banner.jsx
  src/views/preview/share-banner.scss
Labels: pr - needs review

#2182 Fix gh-2156: Use variables for media queries for consistency
  src/_frameless.scss
  src/components/box/box.scss
  src/components/card/card.scss
  src/components/flex-row/flex-row.scss
  src/components/footer/conference/footer.scss
  src/components/grid/grid.scss
  src/components/masonrygrid/masonrygrid.scss
  src/components/modal/ttt/modal.scss
  src/components/navigation/conference/2016/navigation.scss
  src/components/navigation/conference/2018/navigation.scss
  src/components/navigation/www/accountnav.scss
  src/components/navigation/www/navigation.scss
  src/components/page/conference/page.scss
  src/components/registration/registration.scss
  src/components/registration/steps.scss
  src/components/slide/slide.scss
  src/components/social-message/social-message.scss
  src/components/tooltip/tooltip.scss
  src/views/conference/2016/details/details.scss
  src/views/conference/2016/expect/expect.scss
  src/views/conference/2016/index/index.scss
  src/views/conference/2016/plan/plan.scss
  src/views/conference/2016/schedule/schedule.scss
  src/views/conference/2017/index/index.scss
  src/views/conference/2018/details/details.scss
  src/views/conference/2018/expect/expect.scss
  src/views/conference/2018/index/index.scss
  src/views/conference/2018/plan/plan.scss
  src/views/conference/2018/schedule/schedule.scss
  src/views/developers/developers.scss
  src/views/download/download.scss
  src/views/explore/explore.scss
  src/views/guidelines/guidelines.scss
  src/views/messages/messages.scss
  src/views/search/search.scss
  src/views/splash/beta/middle-banner.scss
  src/views/splash/splash.scss
  src/views/teachers/landing/landing.scss
  src/views/tips/tips.scss
  src/views/wedo2-legacy/wedo2.scss
Labels: pr - good to merge

#2194 Add admin capabilities to preview project comments
  src/l10n.json
  src/redux/preview.js
  src/views/preview/comment/comment.jsx
  src/views/preview/comment/comment.scss
  src/views/preview/comment/top-level-comment.jsx
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
Labels: needs-qa

#2198 Comment minor fixes
  src/l10n.json
  src/views/preview/comment/comment.jsx
  src/views/preview/comment/top-level-comment.jsx
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
Labels: pr - good to merge

#2192 Add missing l10n files to tx config
  .tx/config
Labels: pr - good to merge

#2207 Show the username of the parent comment in replies
  src/views/preview/comment/comment.jsx
  src/views/preview/comment/top-level-comment.jsx
Labels: pr - good to merge

#2208 Use top level + replies count to control "Load More" comments button
  src/views/preview/presentation.jsx
Labels: pr - good to merge

#2206 Add * to comments from staff on preview
  src/views/preview/comment/comment.jsx
  src/views/preview/comment/top-level-comment.jsx
Labels: pr - good to merge

#2183 Japanese Character Fix
  src/components/thumbnail/thumbnail.scss
Labels: pr - good to merge

#2211 Connect the consolidated studio data directly
  src/components/modal/addtostudio/container.jsx
  src/views/preview/add-to-studio.jsx
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  src/views/preview/subactions.jsx
Labels: pr - good to merge

#2197 Pass to and receive from GUI info about project creation lifecycle; handle url changes
  src/redux/preview.js
  src/views/preview/preview.jsx
Labels: pr - good to merge

#2221 Use parent_id and commentee_id correctly when posting comments.
  src/views/preview/comment/comment.jsx
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/comment/top-level-comment.jsx
Labels: pr - good to merge

#2213 Integrate www-gui localization
  src/views/preview/preview.jsx
Labels: localization, needs-qa, pr - good to merge

#2121 Maintenance and trouble related static content
  static/cdn/README.txt
  static/cdn/maintenance.html
  static/cdn/trouble.html
Labels: pr - good to merge

#2228 Update the comment routes
  src/redux/preview.js
Labels: pr - good to merge

#2229 Do not rely on total comment number for load more functionality
  src/redux/preview.js
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
Labels: pr - good to merge

#2230 Showing specific comment by url hash on preview
  src/redux/preview.js
  src/views/preview/comment/comment.jsx
  src/views/preview/comment/comment.scss
  src/views/preview/comment/top-level-comment.jsx
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
Labels: pr - good to merge

#2226 Extract strings for localizing the preview page
  src/components/modal/comments/delete-comment.jsx
  src/components/modal/comments/report-comment.jsx
  src/l10n.json
  src/lib/extensions.js
  src/views/preview/extension-chip.jsx
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
  src/views/preview/remix-credit.jsx
  src/views/preview/remix-list.jsx
  src/views/preview/share-banner.jsx
  src/views/preview/studio-list.jsx
  src/views/preview/subactions.jsx
Labels: pr - good to merge

#2237 Keep each input in its own formsy wrapper to improve performance
  src/views/preview/comment/comment.scss
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/presentation.jsx
Labels: pr - good to merge

#2231 Decorate comment text to add @username links and scratch-domain links
  src/lib/decorate-text.jsx
  src/views/preview/comment/comment.jsx
  src/views/preview/presentation.jsx
Labels: pr - good to merge

#2232 moved getExtensions out of constructor, and out of projectInfo response
  src/views/preview/preview.jsx
Labels: bug, pr - good to merge

#2234 pass isShared to gui
  src/views/preview/preview.jsx
Labels: pr - good to merge

#2239 Use #comments-id instead of #comment-id for fetching single comments
  src/views/preview/comment/comment.jsx
  src/views/preview/preview.jsx
Labels: pr - needs review

#2223 Responsive about page!
  src/views/about/about.scss
Labels: pr - good to merge

#2242 remove obsolete code
  src/views/preview/preview.scss
Labels: pr - good to merge

#2235 Update README.md
  README.md
Labels: pr - needs work

#2250 removed erroneous share button icon
  src/views/preview/share-banner.scss
Labels: bug, pr - needs review
