Repository scratchfoundation/scratch-www, pull requests merged in 2018-02, with the labels that each got.

#1403 Fix gh-1400: Button Behavior for Search Result State
  src/l10n.json
  src/views/search/search.jsx
  src/views/search/search.scss
Labels: needs-qa, pr - good to merge

#1805 Add Full Stack Engineer job post
  src/views/jobs/jobs.jsx
Labels: pr - good to merge

#1806 [Develop] January 2018 Release
  src/views/jobs/jobs.jsx
Labels: pr - good to merge

#1809 Fixes #1808 | Updates scratch press link to point to Scratch Foundation Media Kit.
  src/components/footer/www/footer.jsx
Labels: pr - good to merge

#1816 Issue/gh 1814 update wiki link
  test/integration/smoke-testing/test_footer_links.js
Labels: QA, pr - needs review

#1818 Conference March 1 update
  src/views/conference/2018/index/index.jsx
  src/views/conference/2018/index/index.scss
  src/views/conference/2018/index/l10n.json
Labels: QA-OK, pr - good to merge
