Repository scratchfoundation/scratch-www, pull requests merged in 2018-05, with the labels that each got.

#1870 Add research view to transifex config
  .tx/config
Labels: localization, pr - good to merge

#1869 Initial GUI embed
  Makefile
  package.json
  src/routes.json
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  src/views/preview/preview.scss
  webpack.config.js
Labels: pr - needs work

#1875 Correct preview route for fastly
  bin/configure-fastly.js
  src/routes.json
  src/views/preview/preview.jsx
Labels: pr - good to merge

#1882 [Develop] April 2018 Release
  .tx/config
  Makefile
  bin/configure-fastly.js
  package.json
  src/routes.json
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  src/views/preview/preview.scss
  webpack.config.js
Labels: pr - good to merge

#1879 Verbose testing
  .gitignore
  Makefile
  package.json
  test/integration/package.json
  test/integration/selenium-helpers.js
  test/integration/smoke-testing/test-login-failures.js
  test/integration/smoke-testing/test-my-stuff.js
  test/integration/smoke-testing/test_footer_links.js
  test/integration/smoke-testing/test_navbar_links.js
  test/integration/smoke-testing/test_signing_in_and_out_discuss.js
  test/integration/smoke-testing/test_signing_in_and_out_homepage.js
  test/integration/smoke-testing/test_statistics_page.js
Labels: pr - good to merge

#1886 Remove references to Linux for the Scratch 2.0 offline editor
  src/components/news/news.json
  src/views/download/download.jsx
  src/views/download/l10n.json
Labels: pr - needs review

#1891 [Develop] Hotfix - Update Privacy Policy
  src/components/registration/steps.jsx
  src/views/privacypolicy/privacypolicy.jsx
Labels: critical, hotfix, pr - good to merge

#1894 [Master] Hotfix Privacy Policy updates
  src/components/registration/steps.jsx
  src/views/privacypolicy/privacypolicy.jsx
Labels: hotfix, pr - good to merge

#1888 Selenium login failure tests
  test/integration/selenium-helpers.js
  test/integration/smoke-testing/test-login-failures.js
Labels: pr - good to merge

#1908 Fix up favorites
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
Labels: pr - good to merge

#1900 Feature/preview presentation
  package.json
  src/_colors.scss
  src/components/forms/inplace-input.scss
  src/components/forms/textarea.scss
  src/components/modal/report/modal.jsx
  src/components/modal/report/modal.scss
  src/l10n.json
  src/redux/preview.js
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  src/views/preview/preview.scss
  src/views/preview/projectshape.jsx
  static/svgs/project/copy-link-gray.svg
  static/svgs/project/copy-link-white.svg
  static/svgs/project/delete-gray.svg
  static/svgs/project/fav-gray.svg
  static/svgs/project/fav-yellow.svg
  static/svgs/project/love-gray.svg
  static/svgs/project/love-red.svg
  static/svgs/project/remix-gray.svg
  static/svgs/project/remix-white.svg
  static/svgs/project/report-gray.svg
  static/svgs/project/report-white.svg
  static/svgs/project/restore-gray.svg
  static/svgs/project/revised-date-gray.svg
  static/svgs/project/scripts-gray.svg
  static/svgs/project/see-inside-white.svg
  static/svgs/project/share-white.svg
  static/svgs/project/studio-add-white.svg
  static/svgs/project/views-gray.svg
Labels: pr - needs work

#1910 Run smoke tests with Travis after deployment
  .travis.yml
  test/integration/package.json
  test/integration/selenium-helpers.js
  test/integration/smoke-testing/test_project_rows.js
Labels: pr - good to merge
