Repository scratchfoundation/scratch-www, pull requests merged in 2018-11, with the labels that each got.

#2274 make share banner appear only if user has the power to share this project
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
Labels: pr - good to merge

#2269 fix small typo
  src/views/microbit/l10n.json
Labels: pr - good to merge

#2287 Add new strings in preparation for Hour of Code
  src/views/splash/l10n.json
Labels: localization, pr - good to merge

#2288 Add IP Mute message to project comment errors
  src/l10n.json
  src/views/preview/comment/compose-comment.jsx
Labels: pr - good to merge

#2286 Update chromedriver so tests pass more reliably
  test/integration/package.json
  test/integration/selenium-helpers.js
Labels: pr - good to merge

#2284 Avoid displaying an error when /news returns a 500
  src/views/splash/splash.jsx
Labels: pr - good to merge

#2290 Add "project not available" view for when project body cannot be loaded
  src/components/not-available/not-available.jsx
  src/components/not-available/not-available.scss
  src/l10n.json
  src/redux/preview.js
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  static/images/404-giga.png
Labels: pr - good to merge

#2294 point to scratch-gui latest npm release, not develop
  package.json
Labels: pr - good to merge

#2300 Use https for ScratchJR links
  src/components/footer/conference/2016/footer.jsx
  src/components/footer/conference/2017/footer.jsx
  src/components/footer/conference/2018/footer.jsx
  src/components/footer/www/footer.jsx
  test/integration-cypress/cypress/smoke-tests/test-footer-links.js
  test/integration/smoke-testing/test_footer_links.js
Labels: pr - good to merge

#2289 Pass authorId and authorUsername to gui
  .travis.yml
  src/lib/user-thumbnail.js
  src/views/preview/preview.jsx
  webpack.config.js
Labels: pr - good to merge

#2307 Update microbit hex file version
  src/views/microbit/microbit.jsx
Labels: pr - good to merge

#2293 Hide backpack for logged out users
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
Labels: pr - good to merge

#2220 Redo the credits page.
  src/views/credits/credits.jsx
  src/views/credits/credits.scss
  src/views/credits/l10n.json
  src/views/credits/people.json
  src/views/credits/supporters.json
  static/images/credits/brainpop.png
  static/images/credits/lego-education.png
  static/images/credits/legofoundation.png
  static/images/credits/lemann.png
  static/images/credits/siegelfamily.png
  static/images/credits/smilegate.png
  static/images/credits/taledu.png
  static/svgs/credits/amazonws.svg
  static/svgs/credits/cartoonnetwork.svg
  static/svgs/credits/fastly.svg
  static/svgs/credits/google.svg
Labels: pr - good to merge

#2303 Fix wedo-legacy translations
  src/routes.json
Labels: localization, pr - good to merge

#2291 2018 Hour of Code Banners
  src/views/splash/hoc/hoc-banner.scss
  src/views/splash/hoc/middle-banner.jsx
  src/views/splash/hoc/top-banner.jsx
  src/views/splash/presentation.jsx
  static/images/hoc/bg-pattern.png
  static/images/hoc/create-an-adventure-game.jpg
  static/images/hoc/create-animations-that-talk.png
  static/images/hoc/getting-started.jpg
  static/svgs/tutorials.svg
Labels: pr - good to merge

#2302 Issue/2281 gettingstarted
  src/components/intro/intro.jsx
  src/components/navigation/www/navigation.jsx
  src/components/welcome/welcome.jsx
  src/routes.json
  src/views/faq/l10n.json
  src/views/messages/message-rows/user-join.jsx
  test/integration-cypress/cypress/smoke-tests/test-navbar-links.js
  test/integration/smoke-testing/test_navbar_links.js
Labels: pr - good to merge

#2313 Add missing extensions and images
  src/lib/extensions.js
  src/views/preview/l10n.json
  src/views/preview/preview.jsx
  static/svgs/project/extension-ev3.svg
  static/svgs/project/extension-text2speech.svg
Labels: pr - good to merge

#2316 Add a unit test covering the trickier parts of the preview reducer
  test/unit/redux/preview-test.js
Labels: pr - good to merge

#2324 enable remix button; format remix, see inside button css
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  src/views/preview/preview.scss
  src/views/preview/subactions.scss
Labels: pr - good to merge

#2332 Show projectNotAvailable view in editor mode also
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
Labels: pr - good to merge

#2322 use cdn.scratch.ly in staging
  .travis.yml
  src/components/grid/grid.jsx
  src/components/thumbnailcolumn/thumbnailcolumn.jsx
  src/lib/user-thumbnail.js
  src/views/messages/message-rows/comment-message.jsx
  src/views/preview/presentation.jsx
  src/views/preview/remix-credit.jsx
Labels: pr - good to merge

#2336 Allow user to exit "single comment mode" and see all comments.
  src/l10n.json
  src/redux/preview.js
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
Labels: pr - good to merge

#2329 App store badges for Link download
  src/components/extension-landing/extension-landing.scss
  src/components/extension-landing/install-scratch-link.jsx
  src/l10n.json
  static/images/scratchlink/mac-store-badge.svg
  static/images/scratchlink/windows-store-badge.svg
Labels: pr - good to merge

#2334 Rename /preview to /projects
  src/routes.json
  src/views/preview/preview.jsx
  src/views/preview/remix-credit.jsx
Labels: blocked, pr - good to merge

#2325 redirect hash urls to url pathnames
  src/views/preview/preview.jsx
Labels: pr - good to merge

#2341 Revert "use cdn.scratch.ly in staging"
  .travis.yml
  src/components/grid/grid.jsx
  src/components/thumbnailcolumn/thumbnailcolumn.jsx
  src/lib/user-thumbnail.js
  src/views/messages/message-rows/comment-message.jsx
  src/views/preview/presentation.jsx
  src/views/preview/remix-credit.jsx
Labels: pr - good to merge

#2333 Tutorial shortcut redirects
  src/routes.json
Labels: needs discussion

#2340 Show details about why a project is not public
  src/_colors.scss
  src/redux/preview.js
  src/views/preview/banner.jsx
  src/views/preview/banner.scss
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  src/views/preview/share-banner.jsx
  src/views/preview/share-banner.scss
Labels: blocked, pr - good to merge

#2347 Project page - unsupported browser view
  package.json
  src/l10n.json
  src/lib/supported-browser.js
  src/views/preview/preview.jsx
  src/views/preview/project-view.jsx
  src/views/preview/unsupported-browser.jsx
  src/views/preview/unsupported-browser.scss
  static/images/unsupported.png
Labels: pr - good to merge

#2344 Show comment actions on hover and fix report translation
  src/views/preview/comment/comment.jsx
  src/views/preview/comment/comment.scss
Labels: pr - needs work

#2350 Remove comments when remixing, they do not exist on the new project
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2351 Get integration tests to pass after preview to project change
  test/integration/selenium-helpers.js
  test/integration/smoke-testing/test-my-stuff.js
Labels: pr - good to merge

#2353 Revised unsupported browser info
  src/l10n.json
  src/views/preview/unsupported-browser.jsx
Labels: pr - good to merge

#2327 Hotfix/hoc banner
  src/views/splash/hoc/hoc-banner.scss
  src/views/splash/hoc/middle-banner.jsx
  src/views/splash/hoc/top-banner.jsx
  src/views/splash/l10n.json
  src/views/splash/presentation.jsx
  static/images/hoc/bg-pattern.png
  static/images/hoc/create-an-adventure-game.jpg
  static/images/hoc/create-animations-that-talk.png
  static/images/hoc/getting-started.jpg
  static/svgs/tutorials.svg
Labels: pr - good to merge

#2361 [Master] show intro for logged out users
  src/views/splash/presentation.jsx
Labels: pr - good to merge

#2365 Add project thumbnail update action to pass into GUI
  src/redux/preview.js
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2368 Add Makey Makey extension chip
  src/lib/extensions.js
  static/svgs/project/extension-makeymakey.svg
Labels: pr - needs review

#2367 Additional project data for Moderators/Admins on the project page
  src/views/preview/l10n.json
  src/views/preview/mod-info.jsx
  src/views/preview/mod-info.scss
  src/views/preview/presentation.jsx
  src/views/preview/project-view.jsx
  static/svgs/project/block-count.svg
  static/svgs/project/last-revised.svg
  static/svgs/project/sprite-count.svg
Labels: needs-qa, pr - good to merge
