Repository scratchfoundation/scratch-www, pull requests merged in 2018-08, with the labels that each got.

#2007 Remove Darken and Ligthen SCSS
  src/_colors.scss
  src/components/forms/charcount.scss
  src/components/forms/input.scss
  src/components/social-message/social-message.scss
  src/components/spinner/spinner.scss
  src/components/ttt-tile/ttt-tile.scss
  src/main.scss
  src/views/conference/2016/schedule/schedule.scss
  src/views/conference/2017/index/index.scss
  src/views/messages/messages.scss
  src/views/tips/tips.scss
  static/images/tips/blocks-icon.svg
Labels: pr - good to merge

#2010 [DEVELOP] Fix top banner centering on android chrome
  src/views/splash/beta/top-banner.scss
Labels: pr - good to merge

#2011 [MASTER] Fix top banner centering on android chrome
  src/views/splash/beta/top-banner.scss
Labels: hotfix, pr - good to merge

#2006 Refactor Extension Landing Pages
  src/components/extension-landing/extension-header.jsx
  src/components/extension-landing/extension-landing.jsx
  src/components/extension-landing/extension-landing.scss
  src/components/extension-landing/extension-requirements.jsx
  src/components/extension-landing/extension-section.jsx
  src/components/extension-landing/install-scratch-link.jsx
  src/components/extension-landing/os-enum.js
  src/components/extension-landing/project-card.jsx
  src/components/extension-landing/tip-box.jsx
  src/components/os-chooser/os-chooser.jsx
  src/components/steps/step.jsx
  src/components/steps/steps.jsx
  src/components/steps/steps.scss
  src/l10n.json
  src/views/ev3/ev3.jsx
  src/views/ev3/ev3.scss
  src/views/ev3/l10n.json
  src/views/microbit/l10n.json
  src/views/microbit/microbit.jsx
  src/views/microbit/microbit.scss
Labels: pr - needs review

#1985 Add To Studio modal on project page
  Makefile
  docker-compose.yml
  package.json
  src/_colors.scss
  src/components/modal/addtostudio/container.jsx
  src/components/modal/addtostudio/modal.scss
  src/components/modal/addtostudio/presentation.jsx
  src/components/modal/addtostudio/studio-button.jsx
  src/components/modal/base/modal.scss
  src/components/modal/report/modal.jsx
  src/components/modal/report/modal.scss
  src/components/spinner/spinner.jsx
  src/components/spinner/spinner.scss
  src/l10n.json
  src/lib/truncate.js
  src/redux/preview.js
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  static/svgs/modal/add.svg
  static/svgs/modal/close-x.svg
  static/svgs/modal/confirm.svg
  static/svgs/modal/open-blue.svg
  static/svgs/modal/open-white.svg
  static/svgs/modal/spinner.svg
Labels: pr - good to merge

#2013 Add missing l10n strings to EV3 page
  src/views/ev3/ev3.jsx
  src/views/ev3/l10n.json
Labels: pr - good to merge

#1997 Initial implementation for displaying comments on project page
  src/redux/preview.js
  src/views/preview/comment/comment.jsx
  src/views/preview/comment/comment.scss
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/comment/top-level-comment.jsx
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  src/views/preview/preview.scss
  static/svgs/project/comment-reply.svg
Labels: pr - good to merge

#2015 report project POSTs to scratchr2, displays modal reactively
  src/components/forms/validations.jsx
  src/components/modal/addtostudio/modal.scss
  src/components/modal/base/modal.scss
  src/components/modal/report/modal.jsx
  src/components/modal/report/modal.scss
  src/l10n.json
  src/redux/preview.js
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
Labels: pr - good to merge

#2021 Hide intro modal in editor on new project page
  src/views/preview/preview.jsx
Labels: pr - good to merge

#2026 Configure backpack, project, and asset hosts for dev/staging/production
  .travis.yml
  README.md
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  webpack.config.js
Labels: pr - good to merge

#2027 Update packages after installing
  .travis.yml
Labels: pr - good to merge

#2009 Update the last updated date
  src/views/terms/terms.jsx
Labels: pr - good to merge

#2001 Add sort scheme dropdown to search results page
  src/views/search/l10n.json
  src/views/search/search.jsx
  src/views/search/search.scss
Labels: pr - good to merge

#2037 2016/add to studio dialog clip studio name
  package.json
  src/components/modal/addtostudio/modal.scss
  src/components/modal/addtostudio/studio-button.jsx
  src/lib/truncate.js
Labels: needs-qa, pr - good to merge

#2041 1991/accessibility extension landing
  src/components/extension-landing/extension-landing.scss
  src/components/extension-landing/install-scratch-link.jsx
  src/components/extension-landing/project-card.jsx
  src/init.js
  src/l10n.json
  src/views/ev3/ev3.jsx
  src/views/ev3/l10n.json
  src/views/microbit/l10n.json
  src/views/microbit/microbit.jsx
  src/views/wedo2/l10n.json
  src/views/wedo2/wedo2.jsx
Labels: needs-qa, pr - good to merge

#2048 2047/project page/white space next to comments
  src/views/preview/preview.scss
Labels: needs-qa, pr - good to merge

#2042 2038/add to studio dialog entries cursor
  src/components/modal/addtostudio/modal.scss
Labels: needs-qa, pr - good to merge

#2044 [Master] Release for August 2018
  .eslintignore
  .travis.yml
  Makefile
  README.md
  dev-server/index.js
  docker-compose.yml
  package.json
  src/_colors.scss
  src/components/footer/www/footer.jsx
  src/components/forms/charcount.scss
  src/components/forms/input.scss
  src/components/forms/validations.jsx
  src/components/modal/addtostudio/container.jsx
  src/components/modal/addtostudio/modal.scss
  src/components/modal/addtostudio/presentation.jsx
  src/components/modal/addtostudio/studio-button.jsx
  src/components/modal/base/modal.scss
  src/components/modal/report/modal.jsx
  src/components/modal/report/modal.scss
  src/components/navigation/www/navigation.jsx
  src/components/social-message/social-message.scss
  src/components/spinner/spinner.jsx
  src/components/spinner/spinner.scss
  src/components/ttt-tile/ttt-tile.scss
  src/l10n.json
  src/lib/truncate.js
  src/main.scss
  src/redux/preview.js
  src/views/conference/2016/schedule/schedule.scss
  src/views/conference/2017/index/index.scss
  src/views/credits/credits.jsx
  src/views/messages/messages.scss
  src/views/preview/comment/comment.jsx
  src/views/preview/comment/comment.scss
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/comment/top-level-comment.jsx
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  src/views/preview/preview.scss
  src/views/search/l10n.json
  src/views/search/search.jsx
  src/views/search/search.scss
  src/views/terms/terms.jsx
  src/views/tips/tips.scss
  static/images/tips/blocks-icon.svg
  static/svgs/modal/add.svg
  static/svgs/modal/close-x.svg
  static/svgs/modal/confirm.svg
  static/svgs/modal/open-blue.svg
  static/svgs/modal/open-white.svg
  static/svgs/modal/spinner.svg
  static/svgs/project/comment-reply.svg
  test/integration/selenium-helpers.js
  webpack.config.js
Labels: QA-OK, pr - needs review

#2057 [Master] Hotfix: Use popular for the default sort mode
  src/views/search/search.jsx
Labels: pr - good to merge
