Repository scratchfoundation/scratch-www, pull requests merged in 2018-07, with the labels that each got.

#1944 Selenium helper update
  package.json
  test/integration/selenium-helpers.js
  test/integration/smoke-testing/test-login-failures.js
  test/integration/smoke-testing/test-my-stuff.js
  test/integration/smoke-testing/test_footer_links.js
  test/integration/smoke-testing/test_navbar_links.js
  test/integration/smoke-testing/test_project_rows.js
  test/integration/smoke-testing/test_signing_in_and_out_discuss.js
  test/integration/smoke-testing/test_signing_in_and_out_homepage.js
  test/integration/smoke-testing/test_statistics_page.js
Labels: pr - good to merge

#1951 Fix gh-1950: Update parent email age on FAQ page
  src/views/faq/l10n.json
Labels: pr - good to merge

#1953 Update integration readme with Sauce Labs information
  package.json
  test/integration/README.md
Labels: pr - good to merge

#1967 [Develop] Release for June 2018
  src/components/footer/conference/2018/footer.jsx
  src/components/footer/conference/footer.scss
  src/views/conference/2018/details/details.jsx
  src/views/conference/2018/expect/expect.jsx
  src/views/conference/2018/expect/expect.scss
  src/views/conference/2018/schedule/schedule.jsx
  static/images/conference/footer/2018/cartoon-network.png
  static/images/conference/footer/2018/lego-education.png
  static/images/conference/footer/2018/lego-foundation.png
Labels: pr - good to merge

#1965 Update to track changes in docker-compose behavior
  docker-compose.yml
Labels: pr - good to merge

#1970 Update WWW to unify color and typography with scratch-gui
  src/_colors.scss
  src/components/forms/button.scss
  src/components/grid/grid.scss
  src/components/informationpage/informationpage.scss
  src/components/intro/intro.scss
  src/components/spinner/spinner.scss
  src/components/thumbnailcolumn/thumbnailcolumn.scss
  src/components/welcome/welcome.scss
  src/main.scss
  src/views/components/components.jsx
  src/views/components/components.scss
  src/views/conference/2018/schedule/schedule.scss
  src/views/download/download.scss
  src/views/explore/explore.jsx
  src/views/explore/explore.scss
  src/views/messages/messages.scss
  src/views/messages/presentation.jsx
  src/views/preview/preview.scss
  src/views/search/search.jsx
  src/views/search/search.scss
  src/views/studentcompleteregistration/studentcompleteregistration.scss
  src/views/studentregistration/studentregistration.scss
  src/views/teacherregistration/teacherregistration.scss
  src/views/teachers/landing/landing.scss
  src/views/teacherwaitingroom/teacherwaitingroom.scss
  src/views/wedo2/wedo2.scss
Labels: pr - good to merge

#1956 Add top and middle splash page banners for beta launch
  src/routes.json
  src/views/preview-faq/l10n.json
  src/views/splash/beta/middle-banner.jsx
  src/views/splash/beta/middle-banner.scss
  src/views/splash/beta/small-top-banner.jsx
  src/views/splash/beta/small-top-banner.scss
  src/views/splash/beta/top-banner.jsx
  src/views/splash/beta/top-banner.scss
  src/views/splash/l10n.json
  src/views/splash/presentation.jsx
  static/images/beta/bg-pattern.png
  static/images/beta/left-illustration.png
  static/images/beta/right-illustration.png
Labels: pr - good to merge

#1971 Remove extra characters from preview faq routeAlias
  src/routes.json
Labels: pr - needs review

#1973 Added Community Moderator job listing
  src/views/jobs/jobs.jsx
Labels: pr - good to merge

#1976 remove obsolete tx/config for conference
  .tx/config
Labels: ergonomics, localization, pr - needs review

#1981 Add landing pages for the micro:bit and EV3 extensions
  .tx/config
  src/components/os-chooser/os-chooser.jsx
  src/components/os-chooser/os-chooser.scss
  src/l10n.json
  src/routes.json
  src/views/ev3/ev3.jsx
  src/views/ev3/ev3.scss
  src/views/ev3/l10n.json
  src/views/microbit/l10n.json
  src/views/microbit/microbit.jsx
  src/views/microbit/microbit.scss
  static/images/ev3/ev3-accept-connection.png
  static/images/ev3/ev3-connect-1.png
  static/images/ev3/ev3-connect-2.png
  static/images/ev3/ev3-connect-3.png
  static/images/ev3/ev3-enter-pin.png
  static/images/ev3/ev3-illustration.png
  static/images/ev3/ev3-motor-port-a.png
  static/images/ev3/ev3-pattern.svg
  static/images/ev3/ev3-pin.png
  static/images/ev3/ev3.svg
  static/images/ev3/mac-bluetooth-on.png
  static/images/ev3/mac-enter-passcode.png
  static/images/ev3/mac-rename-ev3-1.png
  static/images/ev3/mac-rename-ev3-2.png
  static/images/ev3/mac-rename-ev3-3.png
  static/images/ev3/mac-toolbar.png
  static/images/ev3/motor-turn-block.png
  static/images/ev3/starter-distance-instrument.png
  static/images/ev3/starter-flying-game.png
  static/images/ev3/starter-wave-hello.png
  static/images/ev3/win-device-ready.png
  static/images/microbit/display-hello-block.png
  static/images/microbit/mac-bluetooth-on.png
  static/images/microbit/mac-copy-hex.png
  static/images/microbit/mac-toolbar.png
  static/images/microbit/mbit-connect-1.png
  static/images/microbit/mbit-connect-2.png
  static/images/microbit/mbit-connect-3.png
  static/images/microbit/mbit-display-h.png
  static/images/microbit/mbit-hex-download.png
  static/images/microbit/mbit-pattern.svg
  static/images/microbit/mbit-usb.png
  static/images/microbit/microbit-heart.png
  static/images/microbit/microbit.svg
  static/images/microbit/starter-fish.png
  static/images/microbit/starter-guitar.png
  static/images/microbit/starter-heart.png
  static/images/microbit/win-copy-hex.png
  static/images/scratchlink/mac-toolbar.png
  static/images/scratchlink/windows-toolbar.png
  static/svgs/app-store-badges/apple-app-store-badge.svg
  static/svgs/app-store-badges/microsoft-app-store-badge.svg
  static/svgs/extensions/bluetooth.svg
  static/svgs/extensions/download-white.svg
  static/svgs/extensions/download.svg
  static/svgs/extensions/mac.svg
  static/svgs/extensions/offsite-link.svg
  static/svgs/extensions/scratch-link.svg
  static/svgs/extensions/windows.svg
Labels: needs-qa, pr - good to merge

#1990 Fix new message highlight
  src/components/social-message/social-message.scss
Labels: pr - needs review

#1993 [HOTFIX] Fix new message highlight.
  src/components/social-message/social-message.scss
Labels: hotfix, pr - good to merge

#1975 watchOptions required for use in docker environment
  .eslintignore
  dev-server/index.js
  docker-compose.yml
Labels: pr - good to merge

#1968 Make Travis run smoke tests with Saucelabs
  .travis.yml
  test/integration/selenium-helpers.js
Labels: pr - good to merge

#1994 [Master] Conference 2018 Livestream
  src/views/conference/2018/index/index.jsx
  src/views/conference/2018/index/index.scss
Labels: hotfix, pr - needs review

#1995 [Develop] Conference 2018 Livestream
  src/views/conference/2018/index/index.jsx
  src/views/conference/2018/index/index.scss
Labels: hotfix, pr - good to merge

#1980 Add Kathy Wu to Credits
  src/views/credits/credits.jsx
Labels: pr - good to merge

#1979 Add brycedtea to Credits page
  src/views/credits/credits.jsx
Labels: pr - good to merge

#1964 Fix gh-1962: Update footer wiki link
  src/components/footer/www/footer.jsx
Labels: pr - good to merge
