Repository scratchfoundation/scratch-www, pull requests merged in 2018-06, with the labels that each got.

#1906 [MASTER]:Hotfix/conference 2018
  src/components/footer/conference/2018/footer.jsx
  src/components/footer/conference/footer.scss
  src/components/navigation/conference/2018/navigation.jsx
  src/redux/conference-schedule.js
  src/routes.json
  src/views/conference/2018/details/details.jsx
  src/views/conference/2018/details/details.scss
  src/views/conference/2018/expect/expect.jsx
  src/views/conference/2018/expect/expect.scss
  src/views/conference/2018/index/index.jsx
  src/views/conference/2018/index/index.scss
  src/views/conference/2018/index/l10n.json
  src/views/conference/2018/plan/plan.jsx
  src/views/conference/2018/plan/plan.scss
  src/views/conference/2018/schedule/schedule.jsx
  src/views/conference/2018/schedule/schedule.scss
  static/images/conference/expect/2016/karen.jpg
  static/images/conference/expect/2016/mimi-nichole.jpg
  static/images/conference/expect/2016/mitch.jpg
  static/images/conference/expect/2018/austin_kleon.png
  static/images/conference/expect/2018/growing-up-with-scratch-presenters.png
  static/images/conference/expect/2018/karen.jpg
  static/images/conference/expect/2018/mitch.jpg
  static/images/conference/expect/2018/ricarose.png
  static/images/conference/footer/2016/google.png
  static/images/conference/footer/2016/intel.png
  static/images/conference/footer/2016/lego-foundation.png
  static/images/conference/footer/2016/mit-odl.png
  static/images/conference/footer/2016/no-starch.png
  static/images/conference/footer/2016/scratch-foundation.png
  static/images/conference/footer/2016/siegel-endowment.png
  static/images/conference/footer/2018/epam.png
  static/images/conference/footer/2018/google.png
  static/images/conference/footer/2018/intel.png
  static/images/conference/footer/2018/lego-foundation.png
  static/images/conference/footer/2018/mit-odl.png
  static/images/conference/footer/2018/scratch-foundation.png
  static/images/conference/footer/2018/siegel.png
  static/images/conference/footer/shopify-white.svg
  static/images/conference/index/2018/title-banner.jpg
  static/images/conference/schedule/2016/schedule.png
  static/images/conference/schedule/2018/schedule.png
  static/images/conference/schedule/coming-soon.png
  static/svgs/conference/expect/aug3-icon.svg
  static/svgs/conference/expect/aug4-icon.svg
  static/svgs/conference/expect/aug5-icon.svg
  static/svgs/conference/expect/aug6-icon.svg
  static/svgs/conference/expect/july25-icon.svg
  static/svgs/conference/expect/july26-icon.svg
  static/svgs/conference/expect/july27-icon.svg
  static/svgs/conference/expect/july28-icon.svg
Labels: hotfix, pr - good to merge

#1914 Fix search bar's handling of special characters
  src/views/search/search.jsx
Labels: pr - good to merge

#1904 Updated link to Scratch Wiki - to new domain
  src/views/about/about.jsx
Labels: needs-qa, pr - good to merge

#1902 Fix the /about research page link
  src/views/about/about.jsx
Labels: needs-qa, pr - good to merge

#1915 Changed link from /help to /tips
  src/views/about/about.jsx
Labels: needs-qa, pr - good to merge

#1839 Dockerization
  Dockerfile
  README.md
  docker-compose.yml
  docker_entrypoint.sh
Labels: pr - good to merge

#1922 [Develop] Add donate and connect (email list) redirects
  src/routes.json
Labels: hotfix, needs-qa, pr - good to merge

#1921 [Master] Add donate and connect (email list) redirects
  src/routes.json
Labels: QA-OK, hotfix, pr - good to merge

#1923 Change splash to use 30000000
  src/views/splash/splash.jsx
Labels: needs-qa, pr - needs review

#1924 [HOTFIX] - Content updates for Scratch Conference 2018 website (sponsor logos and keynote descriptions)
  src/components/footer/conference/2018/footer.jsx
  src/views/conference/2018/expect/expect.jsx
  static/images/conference/footer/2018/mit-odl.png
  static/images/conference/footer/2018/mit-ol-logo.png
  static/images/conference/footer/2018/siegel.png
Labels: hotfix, pr - good to merge

#1925 [HOTFIX] [DEVELOP] - Content updates for Scratch Conference 2018 website (sponsor logos and keynote descriptions)
  src/components/footer/conference/2018/footer.jsx
  src/views/conference/2018/expect/expect.jsx
  static/images/conference/footer/2018/mit-odl.png
  static/images/conference/footer/2018/mit-ol-logo.png
  static/images/conference/footer/2018/siegel.png
Labels: hotfix, pr - good to merge

#1912 Feature/preview restructure
  package.json
  src/components/forms/inplace-input.jsx
  src/components/modal/report/modal.jsx
  src/components/modal/report/modal.scss
  src/components/share-banner/share-banner.jsx
  src/components/share-banner/share-banner.scss
  src/components/thumbnailcolumn/thumbnailcolumn.jsx
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  src/views/preview/preview.scss
  src/views/preview/remix-credit.jsx
  src/views/preview/remix-list.jsx
  src/views/preview/share-banner.jsx
  src/views/preview/share-banner.scss
  src/views/preview/studio-list.jsx
Labels: pr - good to merge

#1928 Pin scratch-gui to `latest`
  package.json
Labels: pr - good to merge

#1927 added sentence of detail on deployment
  README.md
Labels: pr - good to merge

#1931 Fix issue with error copy to match new teacher age limit.
  src/views/teacherregistration/l10n.json
Labels: pr - good to merge

#1937 Fix notes/instructions layout on Firefox
  src/views/preview/preview.scss
Labels: pr - good to merge

#1942 [MASTER] Remove Keys from .travis.yml
  .travis.yml
Labels: hotfix, pr - good to merge, security

#1939 [MASTER] Conference site updates
  src/components/footer/conference/2018/footer.jsx
  src/views/conference/2018/expect/expect.jsx
  static/images/conference/footer/2018/lego-education.png
  static/images/conference/footer/2018/lego-foundation.png
Labels: hotfix, pr - good to merge

#1932 Preview - Implement extension info strip
  .tx/config
  package.json
  src/lib/extensions.js
  src/lib/storage.js
  src/views/preview/extension-chip.jsx
  src/views/preview/extension-chip.scss
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  src/views/preview/preview.scss
  static/svgs/project/extension-microbit.svg
  static/svgs/project/extension-music.svg
  static/svgs/project/extension-pen.svg
  static/svgs/project/extension-translate.svg
  static/svgs/project/extension-videosensing.svg
  static/svgs/project/extension-wedo2.svg
  webpack.config.js
Labels: pr - good to merge

#1946 Fix gh-1899: Add Console Warning
  src/init.js
Labels: needs-qa, pr - good to merge
