Repository scratchfoundation/scratch-www, pull requests merged in 2018-04, with the labels that each got.

#1843 Upgrade to React 16
  dev-server/index.js
  package.json
  src/components/carousel/carousel.jsx
  src/components/carousel/legacy-carousel.jsx
  src/components/crashmessage/crashmessage.jsx
  src/components/crashmessage/crashmessage.scss
  src/components/errorboundary/errorboundary.jsx
  src/components/forms/checkbox.jsx
  src/components/forms/form.jsx
  src/components/forms/general-error.jsx
  src/components/forms/input.jsx
  src/components/forms/phone-input.jsx
  src/components/nestedcarousel/nestedcarousel.jsx
  src/components/page/www/page.jsx
  src/components/registration/steps.jsx
  src/l10n.json
  src/views/about/about.jsx
  src/views/studentregistration/studentregistration.jsx
  src/views/teacherregistration/teacherregistration.jsx
  static/images/unhandled.png
  static/js/polyfill.min.js
  webpack.config.js
Labels: needs-qa, pr - good to merge

#1740 Migrate /research page
  src/routes.json
  src/views/research/l10n.json
  src/views/research/research.jsx
Labels: pr - good to merge

#1841 [Master] March 2018 Release
  .babelrc
  .eslintignore
  .gitignore
  README.md
  dev-server/index.js
  package.json
  src/_colors.scss
  src/components/cappednumber/cappednumber.jsx
  src/components/carousel/carousel.jsx
  src/components/carousel/legacy-carousel.jsx
  src/components/crashmessage/crashmessage.jsx
  src/components/crashmessage/crashmessage.scss
  src/components/errorboundary/errorboundary.jsx
  src/components/forms/checkbox.jsx
  src/components/forms/form.jsx
  src/components/forms/general-error.jsx
  src/components/forms/input.jsx
  src/components/forms/phone-input.jsx
  src/components/nestedcarousel/nestedcarousel.jsx
  src/components/page/www/page.jsx
  src/components/registration/steps.jsx
  src/components/remixlist/remixlist.jsx
  src/components/remixlist/remixlist.scss
  src/components/share-banner/share-banner.jsx
  src/components/share-banner/share-banner.scss
  src/components/thumbnailcolumn/thumbnailcolumn.jsx
  src/components/thumbnailcolumn/thumbnailcolumn.scss
  src/l10n.json
  src/redux/preview.js
  src/routes.json
  src/views/about/about.jsx
  src/views/jobs/jobs.jsx
  src/views/messages/presentation.jsx
  src/views/preview/gui-placeholder.png
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  src/views/preview/preview.scss
  src/views/privacypolicy/privacypolicy.jsx
  src/views/studentregistration/studentregistration.jsx
  src/views/teacherregistration/teacherregistration.jsx
  static/images/unhandled.png
  static/js/polyfill.min.js
  test/integration-cypress/.eslintrc
  test/integration-cypress/README.md
  test/integration-cypress/cypress.json
  test/integration-cypress/cypress/smoke-tests/test-footer-links.js
  test/integration-cypress/cypress/smoke-tests/test-navbar-links.js
  test/integration-cypress/package.json
  webpack.config.js
Labels: pr - good to merge

#1849 [Develop] March 2018 Release
  dev-server/index.js
  package.json
  src/components/carousel/carousel.jsx
  src/components/carousel/legacy-carousel.jsx
  src/components/crashmessage/crashmessage.jsx
  src/components/crashmessage/crashmessage.scss
  src/components/errorboundary/errorboundary.jsx
  src/components/forms/checkbox.jsx
  src/components/forms/form.jsx
  src/components/forms/general-error.jsx
  src/components/forms/input.jsx
  src/components/forms/phone-input.jsx
  src/components/nestedcarousel/nestedcarousel.jsx
  src/components/page/www/page.jsx
  src/components/registration/steps.jsx
  src/l10n.json
  src/views/about/about.jsx
  src/views/messages/presentation.jsx
  src/views/studentregistration/studentregistration.jsx
  src/views/teacherregistration/teacherregistration.jsx
  static/images/unhandled.png
  static/js/polyfill.min.js
  webpack.config.js
Labels: pr - good to merge

#1846 Added Giga
  src/views/faq/l10n.json
Labels: pr - needs review

#1853 Update DMCA copy
  src/views/dmca/dmca.jsx
  src/views/dmca/l10n.json
Labels: pr - good to merge

#1862 [Develop] remove recent projects row
  src/views/splash/l10n.json
  src/views/splash/presentation.jsx
  src/views/splash/splash.jsx
Labels: hotfix

#1861 [Develop] Remove dorm information from 2018 Conference page
  src/views/conference/2018/index/index.jsx
  src/views/conference/2018/index/l10n.json
Labels: critical, hotfix

#1863 [Master] remove recent projects row
  src/views/splash/l10n.json
  src/views/splash/presentation.jsx
  src/views/splash/splash.jsx
Labels: pr - good to merge

#1864 [Master] Remove dorm information from 2018 Conference page
  src/views/conference/2018/index/index.jsx
  src/views/conference/2018/index/l10n.json
Labels: pr - good to merge

#1859 Gh 1834/add kazahk to language menu
  languages.json
Labels: needs-qa, pr - good to merge

#1856 Feature/preview project2
  package.json
  src/components/forms/inplace-input.jsx
  src/components/forms/inplace-input.scss
  src/components/remixlist/remixlist.jsx
  src/components/remixlist/remixlist.scss
  src/lib/decorate-text.jsx
  src/redux/preview.js
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  src/views/preview/preview.scss
Labels: pr - good to merge

#1868 [DEVELOP] Close registration when full
  src/components/navigation/conference/2018/navigation.jsx
  src/views/conference/2018/index/index.jsx
  src/views/conference/2018/index/index.scss
  src/views/conference/2018/index/l10n.json
Labels: hotfix, pr - good to merge
