Repository scratchfoundation/scratch-www, pull requests merged in 2019-08, with the labels that each got.

#3197 [Master] Release/2019 08 01
  README.md
  package-lock.json
  package.json
  src/components/formik-forms/formik-select.jsx
  src/components/forms/validation-message.scss
  src/components/join-flow/birthdate-step.jsx
  src/components/join-flow/email-step.jsx
  src/components/join-flow/join-flow-step.scss
  src/components/join-flow/join-flow-steps.scss
  src/components/join-flow/join-flow.jsx
  src/components/join-flow/username-step.jsx
  src/components/join-flow/welcome-step.jsx
  src/l10n.json
  src/views/preview/comment/comment.jsx
Labels: release

#3191 [Master] Adjust height when displaying reCAPTCHA challenge
  src/components/registration/registration.jsx
  src/components/registration/registration.scss
Labels: blocked, hotfix

#3205 [Develop] update download link for Scratch Desktop -> 3.5.0
  src/views/download/download.jsx
Labels: hotfix, pr - good to merge

#3206 [Master] update download link for Scratch Desktop -> 3.5.0
  src/views/download/download.jsx
Labels: hotfix, pr - needs review

#3200 Add Enzyme to www and add a test for the NextStepButton. This takes o…
  .babelrc
  package-lock.json
  package.json
  test/.eslintrc.js
  test/__mocks__/fileMock.js
  test/__mocks__/styleMock.js
  test/helpers/enzyme-setup.js
  test/helpers/intl-helpers.jsx
  test/unit/components/next-step-button.test.jsx
Labels: pr - good to merge

#3208 format next button, use correct strings
  src/components/join-flow/join-flow-step.jsx
  src/components/join-flow/join-flow-steps.scss
  src/components/join-flow/next-step-button.jsx
  src/components/join-flow/next-step-button.scss
  src/components/join-flow/welcome-step.jsx
  src/components/modal/base/modal-title.jsx
  src/l10n.json
Labels: pr - good to merge

#3207 add instructions text to join flow welcome step
  src/components/join-flow/join-flow-steps.scss
  src/components/join-flow/join-flow.jsx
  src/components/join-flow/welcome-step.jsx
  src/l10n.json
Labels: pr - good to merge

#3178 Join flow gender step
  src/components/formik-forms/formik-input.jsx
  src/components/formik-forms/formik-radio-button.jsx
  src/components/formik-forms/formik-radio-button.scss
  src/components/forms/row.scss
  src/components/join-flow/gender-step.jsx
  src/components/join-flow/join-flow-step.jsx
  src/components/join-flow/join-flow-steps.scss
  src/components/join-flow/join-flow.jsx
  src/l10n.json
Labels: pr - good to merge

#3218 [Master] Add concurrency limits to async Fastly API requests
  bin/configure-fastly.js
Labels: hotfix, pr - good to merge

#3199 Consolidate country lists, fix country field in teacher account registration
  src/components/registration/steps.jsx
  src/l10n.json
  src/lib/country-data.js
  src/views/teacherregistration/teacherregistration.jsx
  test/unit/lib/country-data.test.js
Labels: pr - good to merge

#3230 Fix locale data
  custom-locales.json
  package-lock.json
  src/lib/intl.jsx
  src/lib/require-all.js
Labels: critical, pr - good to merge

#3231 Bump scratch-gui version
  package-lock.json
  package.json
Labels: pr - good to merge

#3161 Add join flow country step
  src/components/formik-forms/formik-select.jsx
  src/components/join-flow/country-step.jsx
  src/components/join-flow/join-flow-steps.scss
  src/components/join-flow/join-flow.jsx
Labels: pr - good to merge

#3232 Fix click not working on highlighted comment avatar
  src/views/preview/comment/comment.scss
Labels: pr - good to merge

#3243 Add back the max_old_space_size flag.
  package.json
Labels: pr - good to merge

#3204 formatted email step, added input
  package-lock.json
  package.json
  src/components/formik-forms/formik-input.jsx
  src/components/formik-forms/input.scss
  src/components/join-flow/email-step.jsx
  src/components/join-flow/join-flow-step.jsx
  src/components/join-flow/join-flow-steps.scss
  src/l10n.json
Labels: pr - needs work

#3244 Allow admins to delete comments without confirmation
  src/views/preview/comment/comment.jsx
  src/views/preview/comment/top-level-comment.jsx
  src/views/preview/presentation.jsx
Labels: pr - good to merge

#3242 Standalone join flow page.
  package-lock.json
  src/routes.json
  src/views/join/join.jsx
Labels: pr - good to merge

#3241 Join flow info button
  src/components/info-button/info-button.jsx
  src/components/info-button/info-button.scss
  src/components/join-flow/birthdate-step.jsx
  src/components/join-flow/gender-step.jsx
  src/components/join-flow/join-flow-step.jsx
  src/l10n.json
  test/unit/components/info-button.test.jsx
Labels: pr - good to merge

#3185 Revised and added several join flow strings
  src/components/join-flow/birthdate-step.jsx
  src/components/join-flow/country-step.jsx
  src/components/registration/steps.jsx
  src/l10n.json
  src/lib/validate.js
  test/unit/lib/validate.test.js
Labels: pr - good to merge

#3236 handle username validation errors states better
  src/components/formik-forms/formik-input.jsx
  src/components/formik-forms/formik-input.scss
  src/components/join-flow/username-step.jsx
  src/lib/validate.js
  test/unit/lib/validate.test.js
Labels: pr - good to merge

#3239 Add ToS footer to email step, make next button Create Account
  src/components/join-flow/email-step.jsx
  src/components/join-flow/join-flow-step.jsx
  src/components/join-flow/join-flow-step.scss
  src/components/join-flow/join-flow-steps.scss
  src/l10n.json
Labels: pr - good to merge

#3237 Add formik checkbox component, Show password checkbox
  src/components/formik-forms/formik-checkbox.jsx
  src/components/formik-forms/formik-checkbox.scss
  src/components/formik-forms/formik-forms.scss
  src/components/formik-forms/formik-radio-button.jsx
  src/components/formik-forms/formik-radio-button.scss
  src/components/join-flow/join-flow-steps.scss
  src/components/join-flow/username-step.jsx
Labels: pr - good to merge

#3216 Add unittest for JoinFlowStep.
  test/unit/components/join-flow-step.test.jsx
Labels: pr - good to merge, pr - needs work

#3261 add nonbinary option to gender step of join flow
  src/components/join-flow/gender-step.jsx
  src/l10n.json
Labels: pr - good to merge

#3240 make join flow steps' vertical size consistent, make vertical spacing more flexible
  src/components/join-flow/birthdate-step.jsx
  src/components/join-flow/country-step.jsx
  src/components/join-flow/email-step.jsx
  src/components/join-flow/gender-step.jsx
  src/components/join-flow/join-flow-step.jsx
  src/components/join-flow/join-flow-step.scss
  src/components/join-flow/join-flow-steps.scss
  src/components/join-flow/username-step.jsx
  src/components/join-flow/welcome-step.jsx
Labels: pr - good to merge

#3265 Join flow email improvements
  src/components/formik-forms/formik-checkbox.jsx
  src/components/formik-forms/formik-checkbox.scss
  src/components/formik-forms/formik-input.scss
  src/components/formik-forms/input.scss
  src/components/join-flow/email-step.jsx
  src/components/join-flow/join-flow-steps.scss
  src/l10n.json
Labels: pr - good to merge

#3186 Join flow add images
  src/components/join-flow/birthdate-step.jsx
  src/components/join-flow/country-step.jsx
  src/components/join-flow/email-step.jsx
  src/components/join-flow/join-flow-step.jsx
  src/components/join-flow/join-flow-step.scss
  src/components/join-flow/welcome-step.jsx
  static/images/join-flow/birthdate-header.png
  static/images/join-flow/country-header.png
  static/images/join-flow/email-header.png
  static/images/join-flow/welcome-header.png
  test/unit/components/join-flow-step.test.jsx
Labels: pr - good to merge

#3267 added placeholders to username step
  src/components/join-flow/username-step.jsx
  src/l10n.json
Labels: pr - good to merge

#3260 Add simple tests for a couple of Formik components.
  test/unit/components/formik-input.test.jsx
  test/unit/components/formik-select.test.jsx
Labels: pr - good to merge

#3266 use media queries to make info message responsive
  src/components/info-button/info-button.jsx
  src/components/info-button/info-button.scss
  test/__mocks__/react-responsive.js
  test/unit/components/info-button.test.jsx
Labels: pr - good to merge

#3272 Join flow various images
  src/components/formik-forms/formik-checkbox.scss
  src/components/info-button/info-button.scss
  static/images/join-flow/birthdate-header.png
  static/svgs/forms/checkmark.svg
  static/svgs/info-button/info-button.svg
Labels: pr - good to merge

#3251 Join flow: show positive blue tooltips when you focus an input that is empty
  src/components/formik-forms/formik-input.jsx
  src/components/formik-forms/formik-select.jsx
  src/components/forms/validation-message.jsx
  src/components/forms/validation-message.scss
  src/components/join-flow/username-step.jsx
  src/l10n.json
  test/unit/components/formik-input.test.jsx
Labels: pr - good to merge

#3250 Join flow gender custom focus
  src/components/formik-forms/formik-input.jsx
  src/components/formik-forms/formik-radio-button.jsx
  src/components/join-flow/gender-step.jsx
Labels: pr - good to merge

#3274 Join flow misc UI improvements
  src/components/join-flow/birthdate-step.jsx
  src/components/join-flow/country-step.jsx
  src/components/join-flow/join-flow-steps.scss
Labels: pr - good to merge

#3263 Microbit add cards
  src/components/extension-landing/extension-landing.scss
  src/components/modal/ttt/modal.jsx
  src/l10n.json
  src/views/ideas/l10n.json
  src/views/microbit/l10n-static.json
  src/views/microbit/l10n.json
  src/views/microbit/microbit.jsx
  src/views/microbit/microbit.scss
  src/views/tips/l10n.json
  src/views/tips/tips.jsx
  static/images/microbit/microbit-with-scratch.png
Labels: pr - needs review

#3281 add missing initial values, remove unnecessary one
  src/components/join-flow/email-step.jsx
  src/components/join-flow/welcome-step.jsx
Labels: pr - good to merge, pr - needs review

#3280 formik-select handles fail state with orange border
  src/components/formik-forms/formik-select.jsx
  src/components/formik-forms/formik-select.scss
Labels: pr - good to merge

#3279 improve top and bottom positioning for multiple steps
  src/components/join-flow/country-step.jsx
  src/components/join-flow/join-flow-steps.scss
Labels: pr - good to merge

#3278 make gender radio rows center themselves horizontally within the modal
  src/components/join-flow/join-flow-steps.scss
Labels: pr - good to merge

#3286 Update credits page
  src/views/credits/credits.jsx
Labels: pr - needs review

#3318 Use new tab for PDF download button
  src/views/microbit/microbit.jsx
Labels: pr - needs review

#3319 Add missing string
  src/views/ideas/ideas.jsx
Labels: pr - needs review

#3276 Initial work for captcha in new join flow.
  .travis.yml
  src/components/join-flow/email-step.jsx
  webpack.config.js
Labels: pr - good to merge

#3247 Move sign in and out integration tests to jest
  package-lock.json
  package.json
  test/integration-legacy/selenium-helpers.js
  test/integration-legacy/smoke-testing/test_signing_in_and_out_discuss.js
  test/integration-legacy/smoke-testing/test_signing_in_and_out_homepage.js
  test/integration/selenium-helpers.js
  test/integration/sign-in-and-out.test.js
  test/integration/test-integration.test.js
Labels: pr - good to merge
