Repository scratchfoundation/scratch-www, pull requests merged in 2019-01, with the labels that each got.

#2555 [Develop] Remove "CappedNumber" from view count on project page.
  src/views/preview/stats.jsx
Labels: hotfix, pr - good to merge

#2552 [Develop] fix downloads 3faq routes
  src/routes.json
Labels: hotfix

#2551 [RELEASE] fix downloads 3faq routes
  src/routes.json
Labels: hotfix, pr - needs review

#2560 Fix the regexp that allows for query params on faq and download
  src/routes.json
Labels: pr - needs review

#2562 Bump scratch-gui
  package.json
Labels: pr - good to merge

#2567 Only track green flag once per session
  src/views/preview/project-view.jsx
Labels: hotfix, pr - needs review

#2569 Remove the project count request since it is no longer being used
  src/views/splash/presentation.jsx
  src/views/splash/splash.jsx
Labels: pr - good to merge

#2568 [Master] Only track green flag once
  src/views/preview/project-view.jsx
Labels: hotfix, pr - good to merge

#2583 collapse empty project instructions or notes and credits
  src/views/preview/presentation.jsx
Labels: pr - good to merge

#2574 Fix font in add to studio modal
  src/components/modal/addtostudio/modal.scss
Labels: pr - needs review

#2594 Bump scratch-gui
  package.json
Labels: pr - good to merge

#2595 Release to master 1/3/2018
  package.json
  src/components/modal/addtostudio/modal.scss
  src/views/preview/presentation.jsx
Labels: pr - good to merge

#2598 Capitalize URL
  src/l10n.json
Labels: pr - good to merge

#2599 [Develop] Fix hashtag search
  src/lib/decorate-text.jsx
Labels: hotfix, pr - good to merge

#2600 [Develop] Show link to view all remixes on project page
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
  src/views/preview/remix-list.jsx
  src/views/preview/studio-list.jsx
Labels: hotfix, pr - good to merge

#2596 [Master] Show link to view all remixes on project page
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
  src/views/preview/remix-list.jsx
  src/views/preview/studio-list.jsx
Labels: hotfix, pr - good to merge

#2613 restore 5000 character limit for description fields
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
Labels: pr - needs review

#2612 Disallow comments on unshared projects
  src/views/preview/presentation.jsx
Labels: pr - needs review

#2616 [Develop] love and favorite proxy, and use x-requested-with header
  src/lib/api.js
  src/redux/preview.js
  src/views/preview/project-view.jsx
Labels: hotfix, pr - good to merge

#2615 [MASTER] love and favorite proxy, and use x-requested-with header
  src/l10n.json
  src/lib/api.js
  src/redux/preview.js
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
  src/views/preview/project-view.jsx
Labels: hotfix, pr - good to merge

#2635 Disable global error handling for sentry
  src/views/preview/project-view.jsx
Labels: pr - needs review

#2639 Bump scratch-gui to bring in reversions after smoke testing
  package.json
Labels: pr - good to merge

#2620 Set title for 404 pages
  src/components/not-available/not-available.jsx
Labels: pr - needs review

#2645 Revise unsupported browser
  src/lib/supported-browser.js
Labels: pr - needs review

#2654 [MASTER] Deploy sentry fix to stop noisy errors
  src/views/preview/project-view.jsx
Labels: pr - needs work

#2653 Change Mobile Chrome supported ver to 63+
  src/views/faq/l10n.json
Labels: pr - good to merge

#2656 Don’t allow remixing if the project is not loaded
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2664 bump gui version so that scratch-gui #4319
  package.json
Labels: pr - needs review

#2666 Don't create a separate test for each l10n json
  test/localization/check_valid_json.js
Labels: pr - good to merge

#2667 Don't create a separate test for each l10n json
  test/localization/check_valid_json.js
Labels: pr - good to merge

#2624 Raise z-index of navbar
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2688 Remove Scratch Wiki test from integration tests
  test/integration/smoke-testing/test_footer_links.js
Labels: pr - good to merge

#2682 Add to studio modal should only show studios user can actually change
  src/components/modal/addtostudio/modal.scss
  src/components/modal/addtostudio/presentation.jsx
  src/components/modal/addtostudio/studio-button.jsx
  src/views/preview/add-to-studio.jsx
  src/views/preview/presentation.jsx
  src/views/preview/project-view.jsx
  src/views/preview/subactions.jsx
Labels: pr - good to merge

#2694 Deploy language, layering updates
  package.json
  src/components/footer/www/footer.jsx
  src/views/developers/developers.jsx
  src/views/preview/extension-chip.jsx
  src/views/preview/extension-chip.scss
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
  src/views/preview/project-view.jsx
  static/svgs/project/clouddata.svg
  static/svgs/project/r-arrow.svg
  test/integration/smoke-testing/test_footer_links.js
Labels: pr - needs review

#2691 Don't link if destination is null
  src/views/credits/credits.jsx
Labels: pr - needs review

#2621 Sound credits
  src/views/credits/credits.jsx
  src/views/credits/l10n.json
Labels: pr - good to merge

#2701 LEGO branding updates
  src/lib/extensions.js
  src/routes.json
  src/views/wedo2/l10n.json
  src/views/wedo2/wedo2.jsx
Labels: pr - good to merge

#2703 Revert "Revert "Add to studio modal should only show studios user can actually change""
  src/components/modal/addtostudio/modal.scss
  src/components/modal/addtostudio/presentation.jsx
  src/components/modal/addtostudio/studio-button.jsx
  src/views/preview/add-to-studio.jsx
  src/views/preview/presentation.jsx
  src/views/preview/project-view.jsx
  src/views/preview/subactions.jsx
Labels: blocked, pr - needs review

#2704 Update extension chips
  src/lib/extensions.js
  src/views/preview/l10n.json
  static/svgs/project/extension-microbit.png
  static/svgs/project/extension-microbit.svg
  static/svgs/project/extension-translate.png
  static/svgs/project/extension-translate.svg
  static/svgs/project/extension-videosensing.svg
  static/svgs/project/extension-wedo2.svg
Labels: pr - good to merge

#2711 [Develop] Wrap project update inputs to show server validation
  src/views/preview/formsy-project-updater.jsx
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
  src/views/preview/project-view.jsx
Labels: hotfix, pr - needs review

#2714 [Master] Wrap project inputs to show server validation
  src/views/preview/formsy-project-updater.jsx
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
  src/views/preview/project-view.jsx
Labels: hotfix, pr - good to merge

#2719 [master] Pass updates up from project updater to top-level redux store
  src/views/preview/formsy-project-updater.jsx
Labels: hotfix, pr - good to merge

#2720 Add missing resource to .tx/config
  .tx/config
  src/routes.json
Labels: pr - good to merge

#2535 Migrate FAQ page to FormattedMessage
  src/views/faq/faq.jsx
  src/views/faq/l10n.json
Labels: needs-qa, pr - good to merge

#2728 Add route for `/tutorials` shortcut
  src/routes.json
Labels: pr - good to merge

#2731 Make www modal z-index consitent with gui
  src/components/modal/base/modal.scss
Labels: pr - needs review

#2622 About video
  src/views/about/about.jsx
  src/views/about/about.scss
Labels: pr - good to merge

#2732 reenable commenting on mobile, which was disabled in #2512
  src/views/preview/comment/comment.scss
Labels: pr - good to merge

#2738 include informationpage.jsx after render.jsx, so CSS overrides in cor…
  src/views/jobs/moderator/moderator.jsx
Labels: pr - good to merge
