Repository scratchfoundation/scratch-www, pull requests merged in 2019-11, with the labels that each got.

#3498 Greenkeeper/scratch gui 0.1.0 prerelease.20191031171928
  package-lock.json
  package.json
Labels: pr - good to merge

#3499 Greenkeeper/eslint plugin json 2.0.1
  package-lock.json
  package.json
Labels: greenkeeper, pr - needs review

#3496 correct misspelled join flow intl id
  src/components/join-flow/email-step.jsx
  test/unit/components/email-step.test.jsx
Labels: pr - good to merge

#3483 revise join flow username validation tests
  test/unit/lib/validate.test.js
Labels: pr - good to merge

#3473 Join flow: custom error messages, retry rules for various particular registration error causes
  src/components/join-flow/email-step.jsx
  src/components/join-flow/join-flow-steps.scss
  src/components/join-flow/join-flow.jsx
  src/components/join-flow/registration-error-step.jsx
  src/components/join-flow/welcome-step.jsx
  src/l10n.json
  src/lib/validate.js
  test/unit/components/email-step.test.jsx
  test/unit/components/join-flow.test.jsx
  test/unit/components/registration-error-step.test.jsx
  test/unit/lib/validate.test.js
Labels: pr - good to merge

#3485 username step and email step caches ignore api failures
  src/components/join-flow/email-step.jsx
  src/components/join-flow/username-step.jsx
  src/lib/validate.js
  test/unit/components/email-step.test.jsx
  test/unit/components/username-step.test.jsx
Labels: pr - good to merge

#3505 Revert "Revert "fixed country options to use full country name string as option value""
  src/components/join-flow/country-step.jsx
  src/components/registration/steps.jsx
  src/lib/country-data.js
  test/unit/lib/country-data.test.js
Labels: pr - good to merge

#3503 Add analytics logging to join flow.
  src/components/join-flow/birthdate-step.jsx
  src/components/join-flow/country-step.jsx
  src/components/join-flow/email-step.jsx
  src/components/join-flow/gender-step.jsx
  src/components/join-flow/join-flow.jsx
  src/components/join-flow/registration-error-step.jsx
  src/components/join-flow/username-step.jsx
  src/components/join-flow/welcome-step.jsx
  test/unit/components/email-step.test.jsx
  test/unit/components/join-flow.test.jsx
  test/unit/components/registration-error-step.test.jsx
  test/unit/components/username-step.test.jsx
Labels: pr - good to merge

#3507 Switch to using scratchr2 check_username endpoint instead of api.
  src/lib/validate.js
Labels: pr - good to merge

#3508 Add privacy policy and link to the email step.
  src/components/join-flow/email-step.jsx
  src/l10n.json
Labels: pr - good to merge

#3512 remove truncation of password, passwordConfirm
  src/components/join-flow/username-step.jsx
Labels: pr - good to merge

#3516 Put the right value in the password field. This got mixed up in #3512.
  src/components/join-flow/username-step.jsx
Labels: pr - good to merge

#3513 Additional ChromeOS/Android FAQs for the download page
  src/views/download/download.jsx
  src/views/download/l10n.json
Labels: pr - good to merge

#3536 Take user to the homepage when finishing the join flow (unless they c…
  src/components/join-flow/welcome-step.jsx
  src/redux/navigation.js
Labels: pr - good to merge

#3538 Take user to the homepage when finishing the join flow (unless they c…
  src/components/join-flow/welcome-step.jsx
  src/redux/navigation.js
Labels: pr - good to merge

#3537 Roll out new Join Flow.
  src/redux/navigation.js
  test/unit/redux/navigation.test.js
Labels: pr - good to merge

#3541 [Master] Hotfix/join flow
  src/components/join-flow/welcome-step.jsx
  src/redux/navigation.js
  test/integration-legacy/smoke-testing/test-join.js
  test/unit/redux/navigation.test.js
Labels: pr - needs review

#3540 [Develop] Hotfix/join Merge hotfix that enables join flow back to develop
  src/redux/navigation.js
  test/integration-legacy/smoke-testing/test-join.js
  test/unit/redux/navigation.test.js
Labels: pr - needs review

#3546 Add Imagine a World, Make it Fly, & Pong to Ideas Page, and reorder activities
  src/views/ideas/l10n-static.json
  src/views/ideas/l10n.json
  src/views/ideas/ttt.json
  static/images/ideas/activities/fly-modal.jpg
  static/images/ideas/activities/fly-thumb.jpg
  static/images/ideas/activities/imagine-modal.jpg
  static/images/ideas/activities/imagine-thumb.jpg
  static/images/ideas/activities/pong-modal.jpg
  static/images/ideas/activities/pong-thumb.jpg
Labels: pr - good to merge

#3547 Use indexOf instead of includes because of old browsers.
  src/components/join-flow/username-step.jsx
Labels: pr - good to merge

#3553 if username has spaces, provide validation message specifically mentioning that
  src/l10n.json
  src/lib/validate.js
  test/unit/lib/validate.test.js
Labels: pr - good to merge

#3545 Goodbye jobs page
  src/components/footer/www/footer.jsx
  src/routes.json
  src/views/developers/developers.jsx
  src/views/jobs/jobs.jsx
  src/views/jobs/jobs.scss
  src/views/jobs/l10n.json
  src/views/jobs/moderator/moderator.jsx
  test/integration-legacy/smoke-testing/test_footer_links.js
Labels: pr - needs review

#3564 [Master] Work around replication lag problems on project creation
  package-lock.json
  package.json
  src/views/preview/presentation.jsx
  src/views/preview/project-view.jsx
Labels: hotfix, pr - good to merge

#3565 [Develop] Work around replication lag problems on project creation
  package-lock.json
  package.json
  src/views/preview/presentation.jsx
  src/views/preview/project-view.jsx
Labels: hotfix, pr - good to merge

#3567 [Develop] Support url parameters for 3 redirects
  src/routes.json
Labels: hotfix, pr - good to merge

#3566 [Master] Support url parameters for 3 redirects
  src/routes.json
Labels: hotfix, pr - good to merge

#3572 [Master] CSEdWeek 2019 homepage banners
  src/views/splash/feature/middle-banner.jsx
  src/views/splash/feature/middle-banner.scss
  src/views/splash/feature/small-top-banner.jsx
  src/views/splash/feature/small-top-banner.scss
  src/views/splash/feature/top-banner.jsx
  src/views/splash/feature/top-banner.scss
  src/views/splash/hoc/hoc-banner.scss
  src/views/splash/hoc/middle-banner.jsx
  src/views/splash/hoc/top-banner.jsx
  src/views/splash/l10n.json
  src/views/splash/presentation.jsx
  static/images/hoc/code-a-cartoon.jpg
  static/images/hoc/imagine.jpg
  static/images/hoc/talking.png
  test/integration-legacy/smoke-testing/test-my-stuff.js
Labels: hotfix, pr - good to merge

#3573 [Develop] CSEdWeek 2019 homepage banners
  src/views/splash/feature/middle-banner.jsx
  src/views/splash/feature/middle-banner.scss
  src/views/splash/feature/small-top-banner.jsx
  src/views/splash/feature/small-top-banner.scss
  src/views/splash/feature/top-banner.jsx
  src/views/splash/feature/top-banner.scss
  src/views/splash/hoc/hoc-banner.scss
  src/views/splash/hoc/middle-banner.jsx
  src/views/splash/hoc/top-banner.jsx
  src/views/splash/l10n.json
  src/views/splash/presentation.jsx
  static/images/hoc/code-a-cartoon.jpg
  static/images/hoc/imagine.jpg
  static/images/hoc/talking.png
  test/integration-legacy/smoke-testing/test-my-stuff.js
Labels: hotfix, pr - good to merge
