Repository scratchfoundation/scratch-www, pull requests merged in 2019-05, with the labels that each got.

#2932 LEGO BOOST extension landing page
  src/components/extension-landing/extension-landing.scss
  src/lib/extensions.js
  src/routes.json
  src/views/boost/boost.jsx
  src/views/boost/boost.scss
  src/views/boost/l10n.json
  static/images/boost/boost-connect-1.png
  static/images/boost/boost-connect-2.png
  static/images/boost/boost-connect-lego-beam.svg
  static/images/boost/boost-header.svg
  static/images/boost/boost-pattern.svg
  static/images/boost/boost-starter1.png
  static/images/boost/boost-starter2.png
  static/images/boost/boost-starter3.png
  static/images/boost/boost-turn-motor-on-block.png
  static/images/boost/boost.svg
  static/svgs/project/extension-boost.svg
Labels: pr - good to merge

#2938 chore(package): update scratch-gui to version 0.1.0-prerelease.201905…
  package.json
Labels: greenkeeper

#2924 Embed/social sharing modal
  src/components/modal/social/container.jsx
  src/components/modal/social/modal.scss
  src/components/modal/social/presentation.jsx
  src/l10n.json
  src/lib/social.js
  src/views/preview/presentation.jsx
  src/views/preview/project-view.jsx
  src/views/preview/subactions.jsx
Labels: pr - needs review

#2964 only show copy link button if project is shared
  src/views/preview/presentation.jsx
  src/views/preview/subactions.jsx
Labels: critical, pr - good to merge

#2952 revised conference page to postpone kenya, change sur title, eu desc
  src/views/conference/2019/index/index.jsx
  src/views/conference/2019/index/index.scss
  src/views/conference/2019/index/l10n.json
Labels: pr - needs review

#2969 fix "make translations" command
  bin/build-locales
Labels: critical, pr - good to merge

#2971 change /story redirect from tutorial=story to tutorial=tell-a-story
  src/routes.json
Labels: pr - good to merge

#2977 Add rapa nui to www custom locales
  custom-locales.json
Labels: localization, pr - needs review

#2984 Rapanui fixes
  package.json
Labels: localization, pr - needs review

#2982 Make Add to studio test in test-my-stuff integration test look in shared projects
  test/integration/smoke-testing/test-my-stuff.js
Labels: pr - good to merge

#2973 fix alignment of remix credit avatar, text
  src/views/preview/preview.scss
Labels: pr - good to merge

#2966 make search urls use consistent encoding
  src/components/navigation/www/navigation.jsx
  src/views/search/search.jsx
  test/integration/selenium-helpers.js
  test/integration/smoke-testing/test_search.js
Labels: pr - good to merge

#2994 fix last instructions notes and credits alignment
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
Labels: pr - good to merge

#3005 added missing slash to images link, to fix intermittent CDN issue
  src/views/teachers/landing/landing.jsx
Labels: pr - good to merge

#3012 fix firefox instructions height overflow issue
  src/views/preview/preview.scss
Labels: pr - good to merge

#3014 set min-height of remix credit to max-content
  src/views/preview/preview.scss
Labels: pr - good to merge

#3022 [Master] Release/2019-05-29
  package.json
  src/views/preview/preview.scss
Labels: QA-OK, release

#3021 [Develop] Release/2019-05-29
  package.json
Labels: QA-OK, release

#2987 update react-modal
  package.json
  test/integration/selenium-helpers.js
  test/integration/smoke-testing/test_project_page.js
Labels: pr - good to merge
