Repository scratchfoundation/scratch-www, pull requests merged in 2019-06, with the labels that each got.

#2925 change studios for project API request to use admin status, owner status and token
  src/redux/preview.js
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#3024 in (unused) Cypress test file, removed all footer link tests for external sites
  test/integration-cypress/cypress/smoke-tests/test-footer-links.js
Labels: pr - good to merge

#3025 Skip flakey tests
  package.json
  test/integration/selenium-helpers.js
  test/integration/smoke-testing/test-my-stuff.js
  test/integration/smoke-testing/test_footer_links.js
  test/integration/smoke-testing/test_project_page.js
  test/integration/smoke-testing/test_search.js
Labels: pr - good to merge

#3071 [Master] Hotfix for Africa Code Week resources
  package.json
Labels: hotfix, pr - good to merge

#3054 introduce stub components for new scratch3 join modal
  src/components/modal/join/modal.jsx
  src/components/modal/join/modal.scss
  src/components/navigation/www/navigation.jsx
  src/components/registration/scratch3-registration.jsx
Labels: pr - good to merge

#3073 Moved validation message css from card to own file
  src/components/card/card.jsx
  src/components/card/card.scss
  src/components/forms/validation-message.scss
Labels: pr - good to merge

#3074 stub for join-flow component within modal
  src/components/join-flow/join-flow.jsx
  src/components/modal/join/modal.jsx
Labels: pr - good to merge

#3066 Add Boost and Vernier landing pages to the transifex configuration
  .tx/config
Labels: localization, pr - good to merge

#3069 pass owner username and token to comment endpoints
  src/redux/preview.js
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#3075 added formik dependency, join flow steps using it
  package.json
  src/components/join-flow/join-flow.jsx
  src/components/registration/join-flow-steps.jsx
Labels: pr - good to merge

#3076 added initial formik input component, form validation message component
  src/components/formik-forms/formik-input.jsx
  src/components/forms/validation-message.jsx
Labels: pr - good to merge

#3077 introduce join-flow-step, next-step-button
  src/components/join-flow/join-flow-step.jsx
  src/components/join-flow/join-flow.jsx
  src/components/join-flow/next-step-button.jsx
  src/components/registration/join-flow-steps.jsx
Labels: pr - good to merge

#3070 [Develop] Hotfix for Africa Code Week resources
  package.json
Labels: hotfix, pr - good to merge

#3080 moved join-flow-steps to join flow dir
  src/components/join-flow/join-flow-steps.jsx
  src/components/join-flow/join-flow.jsx
Labels: pr - good to merge

#3079 added test to check that join window shows scratchr2 join flow
  test/integration/smoke-testing/test-join.js
Labels: pr - good to merge

#3084 Skip tests that occasionally failed on travis
  test/integration/smoke-testing/test-my-stuff.js
  test/integration/smoke-testing/test_project_page.js
  test/integration/smoke-testing/test_signing_in_and_out_homepage.js
Labels: pr - good to merge

#3081 fix passing text to validation message
  src/components/formik-forms/formik-input.jsx
Labels: pr - good to merge

#3083 update download links for Scratch Desktop 3.4.0
  src/views/download/download.jsx
Labels: pr - good to merge, release

#3092 fix see all comments and load more replies, by passing author username
  src/views/preview/project-view.jsx
Labels: pr - needs review
