Repository scratchfoundation/scratch-www, pull requests merged in 2019-07, with the labels that each got.

#3099 [master] Add troubleshooting item for boost firmware update
  src/views/boost/boost.jsx
  src/views/boost/l10n.json
Labels: hotfix, pr - good to merge

#3098 [develop] Add troubleshooting item for boost firmware update
  src/views/boost/boost.jsx
  src/views/boost/l10n.json
Labels: hotfix, pr - good to merge

#3082 working username step of join flow
  src/components/join-flow/join-flow-steps.jsx
  src/lib/validate.js
  test/unit/lib/validate.js
Labels: pr - good to merge

#3086 use html form instead of formik form
  src/components/join-flow/join-flow-step.jsx
Labels: pr - good to merge

#3107 created ModalTitle component
  src/components/modal/addtostudio/presentation.jsx
  src/components/modal/base/modal-title.jsx
  src/components/modal/base/modal-title.scss
  src/components/modal/base/modal.scss
  src/components/modal/report/modal.jsx
  src/components/modal/social/presentation.jsx
Labels: pr - good to merge

#3113 add ModalInnerContent component, use it in modals
  src/components/modal/addtostudio/presentation.jsx
  src/components/modal/base/modal-inner-content.jsx
  src/components/modal/base/modal-inner-content.scss
  src/components/modal/base/modal.scss
  src/components/modal/report/modal.jsx
  src/components/modal/social/presentation.jsx
Labels: pr - good to merge

#3116 Format and position validation error messages in join flow
  src/components/formik-forms/formik-input.jsx
  src/components/forms/row.scss
  src/components/join-flow/join-flow-steps.jsx
  src/components/join-flow/join-flow-steps.scss
  src/components/modal/base/modal-inner-content.scss
Labels: pr - good to merge

#3132 add ModalInnerContent component, use it in modals
  src/components/modal/addtostudio/presentation.jsx
  src/components/modal/base/modal-inner-content.jsx
  src/components/modal/base/modal-inner-content.scss
  src/components/modal/base/modal.scss
  src/components/modal/report/modal.jsx
  src/components/modal/social/presentation.jsx
Labels: pr - good to merge

#3119 handle join flow state for tracking, advancing current step
  src/components/join-flow/join-flow.jsx
Labels: pr - good to merge

#3134 Upgrade file-loader, url-loader and async packages, add package-lock.json
  .travis.yml
  bin/configure-fastly.js
  package-lock.json
  package.json
  src/redux/preview.js
  webpack.config.js
Labels: greenkeeper, pr - good to merge

#3135 update package-lock.json with newer google-libphonenumber
  package-lock.json
Labels: pr - good to merge

#3121 introduce formik select component
  src/components/formik-forms/formik-select.jsx
Labels: pr - good to merge

#3117 Format join flow using ModalTitle, ModalInnerContent, NextStepButton components
  src/components/join-flow/join-flow-step.jsx
  src/components/join-flow/join-flow-step.scss
  src/components/join-flow/next-step-button.jsx
  src/components/join-flow/next-step-button.scss
  src/components/modal/join/modal.scss
Labels: pr - good to merge

#3137 Move Makefile into package.json, remove Docker config
  .travis.yml
  Dockerfile
  Makefile
  README.md
  dev-server/index.js
  docker-compose.yml
  docker_entrypoint.sh
  package-lock.json
  package.json
  test/integration/README.md
Labels: pr - good to merge

#3140 use padding to avoid margin collapse; drop approach that used `overflow: auto`
  src/components/join-flow/join-flow-step.scss
  src/components/modal/base/modal-inner-content.jsx
  src/components/modal/base/modal-inner-content.scss
Labels: pr - good to merge

#3138 Improve formatting of join flow title, description, next step button
  src/components/join-flow/join-flow-step.jsx
  src/components/join-flow/join-flow-step.scss
  src/components/join-flow/join-flow-steps.jsx
  src/components/join-flow/join-flow-steps.scss
  src/components/join-flow/next-step-button.jsx
  src/components/join-flow/next-step-button.scss
Labels: pr - good to merge

#3133 Format validation; redo of PR 3116
  src/components/formik-forms/formik-input.jsx
  src/components/forms/row.scss
  src/components/join-flow/join-flow-steps.jsx
Labels: pr - good to merge

#3144 Join flow add birth date step
  src/components/formik-forms/formik-select.jsx
  src/components/join-flow/birthdate-step.jsx
  src/components/join-flow/join-flow-step.jsx
  src/components/join-flow/join-flow-step.scss
  src/components/join-flow/join-flow-steps.scss
  src/components/join-flow/join-flow.jsx
  src/components/join-flow/username-step.jsx
Labels: pr - good to merge

#3162 rewrote validate legacy unit test from using tap, to using jest
  package.json
  test/unit-legacy/lib/validate.js
  test/unit/lib/validate.test.js
  test/unit/test-unit.test.js
Labels: pr - good to merge, pr - needs review

#3156 updated several eslint-related packages, fixed lint errors
  package-lock.json
  package.json
  src/.eslintrc.js
  src/components/extension-landing/install-scratch-link.jsx
  src/components/extension-landing/project-card.jsx
  src/components/grid/grid.jsx
  src/components/microworld/microworld.jsx
  src/components/modal/ttt/modal.jsx
  src/components/thumbnailcolumn/thumbnailcolumn.jsx
  src/views/ideas/ideas.jsx
Labels: needs discussion, pr - good to merge

#3136 fix add-to-studio modal height, gradient interference
  src/components/modal/addtostudio/modal.scss
  src/components/modal/addtostudio/presentation.jsx
Labels: pr - good to merge

#3169 Update scratch-gui to version 0.1.0-prerelease.20190724175453
  package-lock.json
  package.json
Labels: greenkeeper, pr - good to merge

#3176 Update scratch-gui to version 0.1.0-prerelease.20190725155313
  package-lock.json
  package.json
Labels: greenkeeper, pr - good to merge

#3171 [Master] Release for 2019-07-24
  .travis.yml
  README.md
  package-lock.json
  package.json
  src/.eslintrc.js
  src/components/extension-landing/install-scratch-link.jsx
  src/components/extension-landing/project-card.jsx
  src/components/formik-forms/formik-input.jsx
  src/components/formik-forms/formik-select.jsx
  src/components/forms/row.scss
  src/components/grid/grid.jsx
  src/components/join-flow/birthdate-step.jsx
  src/components/join-flow/join-flow-step.jsx
  src/components/join-flow/join-flow-step.scss
  src/components/join-flow/join-flow-steps.scss
  src/components/join-flow/join-flow.jsx
  src/components/join-flow/username-step.jsx
  src/components/microworld/microworld.jsx
  src/components/modal/addtostudio/modal.scss
  src/components/modal/addtostudio/presentation.jsx
  src/components/modal/ttt/modal.jsx
  src/components/thumbnailcolumn/thumbnailcolumn.jsx
  src/views/ideas/ideas.jsx
  test/.eslintrc.js
  test/README.md
  test/integration-legacy/selenium-helpers.js
  test/integration-legacy/smoke-testing/test-join.js
  test/integration-legacy/smoke-testing/test-login-failures.js
  test/integration-legacy/smoke-testing/test-my-stuff.js
  test/integration-legacy/smoke-testing/test_footer_links.js
  test/integration-legacy/smoke-testing/test_navbar_links.js
  test/integration-legacy/smoke-testing/test_project_page.js
  test/integration-legacy/smoke-testing/test_project_rows.js
  test/integration-legacy/smoke-testing/test_search.js
  test/integration-legacy/smoke-testing/test_signing_in_and_out_discuss.js
  test/integration-legacy/smoke-testing/test_signing_in_and_out_homepage.js
  test/integration-legacy/smoke-testing/test_statistics_page.js
  test/integration-legacy/teacher-registration/teacher_registration_utils.js
  test/integration-legacy/teacher-registration/test_teacher_registration_address_step.js
  test/integration-legacy/teacher-registration/test_teacher_registration_demographics_step.js
  test/integration-legacy/teacher-registration/test_teacher_registration_name_step.js
  test/integration-legacy/teacher-registration/test_teacher_registration_organization_step.js
  test/integration-legacy/teacher-registration/test_teacher_registration_phone_step.js
  test/integration-legacy/teacher-registration/test_teacher_registration_username_step.js
  test/integration-legacy/teacher-registration/test_teacher_registration_usescratch_step.js
  test/integration/package.json
  test/integration/test-integration.test.js
  test/localization-legacy/check_duplicate_strings.js
  test/localization-legacy/check_string_ids.js
  test/localization-legacy/check_valid_json.js
  test/localization/test-localization.test.js
  test/unit-legacy/redux/preview-test.js
  test/unit-legacy/test_fastly_config_methods.js
  test/unit/lib/validate.js
  test/unit/lib/validate.test.js
Labels: pr - good to merge, release

#3172 [Develop] Release for 2019-07-24
  package-lock.json
  package.json
Labels: pr - good to merge

#3180 Join flow design tweaks
  src/components/join-flow/join-flow-step.scss
  src/components/join-flow/join-flow-steps.scss
Labels: pr - good to merge

#3179 added missing strings to join flow
  src/components/join-flow/birthdate-step.jsx
  src/components/join-flow/username-step.jsx
  src/l10n.json
Labels: pr - good to merge

#3181 better validation positioning on birthdate step
  src/components/formik-forms/formik-select.jsx
  src/components/forms/validation-message.scss
  src/components/join-flow/birthdate-step.jsx
  src/components/join-flow/join-flow-steps.scss
Labels: pr - good to merge

#3131 provide key to comments
  src/views/preview/comment/comment.jsx
Labels: pr - needs review

#3184 added stubs for email step, welcome step
  src/components/join-flow/email-step.jsx
  src/components/join-flow/join-flow.jsx
  src/components/join-flow/welcome-step.jsx
  src/l10n.json
Labels: pr - needs work

#3188 update translation command to npm run translate
  README.md
Labels: pr - good to merge

#3192 [Develop] Adjust height when displaying reCAPTCHA challenge
  src/components/registration/registration.jsx
  src/components/registration/registration.scss
Labels: hotfix, pr - good to merge
