Repository scratchfoundation/scratch-www, pull requests merged in 2019-02, with the labels that each got.

#2741 use slider toggle for turning comments on and off
  src/components/forms/toggle-slider.jsx
  src/components/forms/toggle-slider.scss
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
Labels: pr - good to merge

#2739 Wrap ‘need help?’ link when translation is too long
  src/components/login/login.jsx
  src/components/login/login.scss
Labels: localization, pr - good to merge

#2745 [Master] Bump GUI to fix loading editor in different language
  package.json
Labels: pr - good to merge

#2766 Prevent seeing /projects/0/fullscreen URL
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2765 Use a dummy form submission instead of logging out via xhr.
  src/redux/navigation.js
Labels: pr - good to merge

#2767 show autocensored message if API indicates project was autocensored
  src/views/preview/censored-message.jsx
  src/views/preview/presentation.jsx
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2782 Updating Privacy Policy
  src/views/privacypolicy/privacypolicy.jsx
Labels: pr - good to merge

#2764 Don't refer to a section which does not exist
  src/views/faq/faq.jsx
  src/views/faq/l10n.json
Labels: pr - good to merge

#2789 Get thumbnails from the project for reporting
  src/redux/preview.js
  src/views/preview/presentation.jsx
  src/views/preview/project-view.jsx
Labels: pr - good to merge

#2795 Add 2019 Regional conferences page
  src/components/footer/conference/2019/footer.jsx
  src/components/footer/conference/footer.scss
  src/components/navigation/conference/2019/navigation.jsx
  src/components/navigation/conference/2019/navigation.scss
  src/components/page/conference/2019/page.jsx
  src/l10n.json
  src/routes.json
  src/views/conference/2019/index/index.jsx
  src/views/conference/2019/index/index.scss
  src/views/conference/2019/index/l10n.json
  static/images/conference/footer/instagram.png
  static/images/conference/index/2019/title-banner-2.jpg
  static/images/conference/index/2019/title-banner-3.jpg
  static/images/conference/index/2019/title-banner.jpg
  static/svgs/conference/flags/cl.svg
  static/svgs/conference/flags/eu.svg
  static/svgs/conference/flags/ke.svg
  static/svgs/conference/index/audience-icon-solid.svg
  static/svgs/conference/index/calendar-icon-color.svg
  static/svgs/conference/index/calendar-icon-solid.svg
  static/svgs/conference/index/envelope-icon.svg
  static/svgs/conference/index/hashtag-icon-solid.svg
  static/svgs/conference/index/language-icon-solid.svg
  static/svgs/conference/index/map-icon-solid.svg
Labels: pr - good to merge

#2812 corrected mail list form; links use _blank; redirect conference url; logo links to main site
  src/components/navigation/conference/2019/navigation.jsx
  src/routes.json
  src/views/conference/2019/index/index.jsx
Labels: pr - good to merge

#2773 Update moderator requirements.
  src/views/jobs/moderator/moderator.jsx
Labels: pr - needs review
