Repository scratchfoundation/scratch-www, pull requests merged in 2019-12, with the labels that each got.

#3568 major reformat of README, with changes to indenting and testing instructions
  README.md
Labels: pr - good to merge

#3482 fixed the issue "Create a Username" has different font weight
  src/components/registration/steps.jsx
Labels: pr - needs review

#3591 added robyn bosic to credits page; alphebeatized credits, contributors
  src/views/credits/credits.jsx
  src/views/credits/people.json
Labels: pr - good to merge

#3597 [Master] Hotfix/conference2020
  src/components/footer/conference/2020/footer.jsx
  src/components/navigation/conference/2020/navigation.jsx
  src/components/navigation/conference/2020/navigation.scss
  src/components/page/conference/2020/page.jsx
  src/routes.json
  src/views/conference/2020/index/index.jsx
  src/views/conference/2020/index/index.scss
  src/views/conference/2020/index/l10n.json
  static/images/conference/index/2020/title-banner.jpg
Labels: pr - needs review

#3576 Retry fetching session until it succeeds, when registering using join flow
  src/components/join-flow/join-flow.jsx
  src/lib/session.js
  src/redux/navigation.js
  src/redux/session.js
  test/unit/components/join-flow.test.jsx
Labels: pr - needs review

#3601 [MASTER] Update troubleshooting and FAQ sections for Scratch App and hardware extensions
  src/l10n.json
  src/views/boost/boost.jsx
  src/views/download/download.jsx
  src/views/download/l10n.json
  src/views/ev3/ev3.jsx
  src/views/gdxfor/gdxfor.jsx
  src/views/microbit/microbit.jsx
  src/views/wedo2/wedo2.jsx
Labels: hotfix, pr - good to merge

#3599 break word in project description
  src/views/preview/preview.scss
Labels: pr - good to merge

#3604 Refactor session fetching to reduce code duplication, make more testable
  src/lib/session.js
  src/redux/session.js
  test/unit/lib/session.test.js
Labels: pr - good to merge

#3615 Greenkeeper/url loader 2.3.0
  package-lock.json
  package.json
Labels: greenkeeper
