Repository scratchfoundation/scratch-www, pull requests merged in 2019-04, with the labels that each got.

#2865 Remove dependency on scratchr2_translations
  .tx/config
  Makefile
  bin/build-locales
  package.json
  test/localization/check_valid_json.js
Labels: localization, pr - good to merge

#2869 Revert April Fools
  .travis.yml
  package.json
  src/components/cats/cats.jsx
  src/components/cats/cats.scss
  src/components/footer/www/footer.jsx
  src/components/grid/grid.jsx
  src/components/grid/grid.scss
  src/components/thumbnail/thumbnail.jsx
  src/components/thumbnail/thumbnail.scss
  src/lib/piano.js
  src/views/explore/explore.jsx
  src/views/search/computer-cat.jpg
  src/views/search/fish.svg
  src/views/search/search.jsx
  src/views/search/search.scss
  static/images/cats/1.jpg
  static/images/cats/2.jpg
  static/images/cats/3.jpg
  static/images/cats/4.jpg
  static/images/cats/Cat1.jpg
  static/images/cats/Cat2.jpg
  static/images/cats/Cat3.jpg
  static/images/cats/Cat4.jpg
  static/images/cats/IMG_0071.jpg
  static/images/cats/IMG_0122.jpg
  static/images/cats/IMG_0135.jpg
  static/images/cats/IMG_0288.jpg
  static/images/cats/IMG_0504.jpg
  static/images/cats/IMG_0681.jpg
  static/images/cats/IMG_0684.jpg
  static/images/cats/IMG_0698.jpg
  static/images/cats/IMG_1092.jpg
  static/images/cats/IMG_1157.jpg
  static/images/cats/IMG_1463.jpg
  static/images/cats/IMG_1696.jpg
  static/images/cats/IMG_1977.jpg
  static/images/cats/IMG_2507.jpg
  static/images/cats/IMG_2681.jpg
  static/images/cats/IMG_2775.jpg
  static/images/cats/IMG_2776.jpg
  static/images/cats/IMG_3218.jpg
  static/images/cats/IMG_5880.jpg
  static/images/cats/IMG_6020.jpg
  static/images/cats/IMG_6521.jpg
  static/images/cats/IMG_6558.jpg
  static/images/cats/IMG_9587.jpg
  static/images/cats/IMG_9766.jpg
  static/images/cats/IMG_9775.jpg
Labels: pr - good to merge

#2871 pass ownerUsername in three places it was left out
  src/redux/preview.js
Labels: bug, pr - good to merge

#2852 Update SiegelFamily Endowment Logo
  static/images/credits/siegelfamily.png
Labels: pr - needs review

#2876 chore(package): update scratch-gui to version 0.1.0-prerelease.201904…
  package.json
Labels: pr - good to merge

#2881 [develop] Hotfix/revert comments studios urls
  src/redux/preview.js
  src/views/preview/project-view.jsx
Labels: hotfix

#2880 [master] Hotfix/revert comments studios urls
  src/redux/preview.js
  src/views/preview/project-view.jsx
Labels: QA-OK, hotfix, pr - good to merge

#2875 reduce size of two credits logos
  static/images/credits/lemann.png
  static/images/credits/siegelfamily.png
Labels: pr - good to merge

#2817 Add Vernier Force and Accel extension landing page
  src/lib/extensions.js
  src/routes.json
  src/views/gdxfor/gdxfor.jsx
  src/views/gdxfor/gdxfor.scss
  src/views/gdxfor/l10n.json
  static/images/gdxfor/gdxfor-connect-1.svg
  static/images/gdxfor/gdxfor-connect-2.png
  static/images/gdxfor/gdxfor-connect-3.png
  static/images/gdxfor/gdxfor-force-pushed-stack.png
  static/images/gdxfor/gdxfor-header.svg
  static/images/gdxfor/gdxfor-pattern.svg
  static/images/gdxfor/gdxfor-push-force.svg
  static/images/gdxfor/gdxfor-starter1.png
  static/images/gdxfor/gdxfor-starter2.png
  static/images/gdxfor/gdxfor-starter3.png
  static/images/gdxfor/gdxfor.svg
  static/svgs/project/extension-gdxfor.svg
Labels: pr - needs work

#2902 Update react-intl to bring in māori locale-data
  package.json
Labels: localization, pr - good to merge

#2912 Fix Vernier Go Direct branding
  src/routes.json
  src/views/gdxfor/gdxfor.jsx
  src/views/gdxfor/l10n.json
Labels: pr - good to merge
