Repository scratchfoundation/scratch-www, pull requests merged in 2019-09, with the labels that each got.

#3322 Add a unittest for the EmailStep.
  test/unit/components/email-step.test.jsx
Labels: pr - good to merge

#3329 Join flow standalone page
  src/routes.json
  src/views/join/join.jsx
Labels: pr - good to merge

#3306 restyle next button to remove border, add hover color
  src/_colors.scss
  src/components/join-flow/next-step-button.scss
Labels: pr - good to merge

#3297 on complete join flow, take user to new project
  src/components/navigation/www/navigation.jsx
  src/components/registration/scratch3-registration.jsx
  src/redux/navigation.js
Labels: pr - good to merge

#3289 Join flow validate email remotely
  src/components/join-flow/email-step.jsx
  src/lib/validate.js
  test/unit/lib/validate.test.js
Labels: pr - good to merge

#3291 join flow register user function, registration error component
  package-lock.json
  package.json
  src/components/formik-forms/formik-checkbox.jsx
  src/components/join-flow/country-step.jsx
  src/components/join-flow/email-step.jsx
  src/components/join-flow/join-flow-steps.scss
  src/components/join-flow/join-flow.jsx
  src/components/join-flow/registration-error-step.jsx
  src/l10n.json
  test/unit/components/join-flow.test.jsx
  test/unit/components/registration-error-step.test.jsx
Labels: pr - good to merge

#3334 Add captcha token to ther request. It was left out of #3291.
  src/components/join-flow/join-flow.jsx
Labels: pr - good to merge

#3337 Merge develop to release branch
  .travis.yml
  package-lock.json
  package.json
  src/_colors.scss
  src/components/formik-forms/formik-checkbox.jsx
  src/components/join-flow/country-step.jsx
  src/components/join-flow/email-step.jsx
  src/components/join-flow/join-flow-steps.scss
  src/components/join-flow/join-flow.jsx
  src/components/join-flow/next-step-button.scss
  src/components/join-flow/registration-error-step.jsx
  src/components/navigation/www/navigation.jsx
  src/components/registration/scratch3-registration.jsx
  src/l10n.json
  src/lib/validate.js
  src/redux/navigation.js
  src/routes.json
  src/views/join/join.jsx
  test/integration-legacy/selenium-helpers.js
  test/integration-legacy/smoke-testing/test_signing_in_and_out_discuss.js
  test/integration-legacy/smoke-testing/test_signing_in_and_out_homepage.js
  test/integration/selenium-helpers.js
  test/integration/sign-in-and-out.test.js
  test/integration/test-integration.test.js
  test/unit/components/email-step.test.jsx
  test/unit/components/join-flow.test.jsx
  test/unit/components/registration-error-step.test.jsx
  test/unit/lib/validate.test.js
  webpack.config.js
Labels: pr - good to merge, release

#3351 move info button down, and give its message a shadow
  src/components/info-button/info-button.scss
Labels: pr - good to merge

#3352 Join flow revise descriptions and privacy messages
  src/_colors.scss
  src/components/info-button/info-button.scss
  src/components/join-flow/birthdate-step.jsx
  src/components/join-flow/country-step.jsx
  src/components/join-flow/email-step.jsx
  src/components/join-flow/gender-step.jsx
  src/components/join-flow/join-flow-step.jsx
  src/components/join-flow/join-flow-step.scss
  src/components/join-flow/join-flow-steps.scss
  src/l10n.json
  static/svgs/info-button/info-button.svg
  test/unit/components/email-step.test.jsx
Labels: pr - good to merge

#3360 fix welcome vertical spacing in Welcome step, make it flexible for localization
  src/components/join-flow/join-flow-steps.scss
  src/components/join-flow/welcome-step.jsx
Labels: pr - good to merge

#3359 Join flow placeholder fixes
  src/components/formik-forms/formik-input.jsx
  src/components/formik-forms/formik-input.scss
  src/components/join-flow/birthdate-step.jsx
  src/components/join-flow/country-step.jsx
Labels: pr - good to merge

#3365 Remove tagline from site footer
  src/components/footer/conference/2016/footer.jsx
  src/components/footer/conference/2017/footer.jsx
  src/components/footer/conference/2018/footer.jsx
  src/components/footer/conference/2019/footer.jsx
  src/components/footer/www/footer.jsx
  src/l10n.json
Labels: pr - good to merge

#3373 Hopefully fix captcha site key in prod. I think I made a copy/paste e…
  .travis.yml
Labels: pr - good to merge

#3385 Update Code Club Link
  src/views/teachers/landing/landing.jsx
Labels: pr - good to merge

#3381 Join flow handle text overflow more flexibly
  src/components/info-button/info-button.scss
  src/components/join-flow/join-flow-step.scss
  src/components/join-flow/join-flow-steps.scss
Labels: pr - good to merge

#3361 when select dropdown is focused, clear any validation errors
  src/components/join-flow/birthdate-step.jsx
  src/components/join-flow/country-step.jsx
Labels: pr - good to merge

#3375 Include canonical link in project meta tags
  src/views/preview/meta.jsx
Labels: pr - good to merge

#3387 [Master] Contain zalgo text
  src/views/preview/comment/comment.scss
Labels: hotfix, pr - good to merge

#3388 [Develop] Contain zalgo text
  src/views/preview/comment/comment.scss
Labels: pr - good to merge

#3391 Update BOOST troubleshooting to suggest updating Scratch Link
  src/views/boost/boost.jsx
  src/views/boost/l10n.json
Labels: pr - good to merge

#3367 Handle errors of captcha loading by setting error state on JoinFlow.
  src/components/join-flow/email-step.jsx
  src/components/join-flow/join-flow.jsx
  src/l10n.json
  test/unit/components/email-step.test.jsx
  test/unit/components/join-flow.test.jsx
Labels: pr - good to merge

#3394 set modal close icon to draggable false
  src/components/modal/base/modal.jsx
Labels: pr - good to merge

#3395 make validations be the same width as inputs…
  src/components/join-flow/birthdate-step.jsx
  src/components/join-flow/country-step.jsx
  src/components/join-flow/join-flow-steps.scss
Labels: pr - good to merge

#3392 Join Flow validation positioning/spacing fixes
  src/components/join-flow/join-flow-steps.scss
Labels: pr - good to merge

#3386 new join flow modal stays open on click outside
  src/components/modal/join/modal.jsx
Labels: pr - good to merge

#3357 One approach to hiding the close button in the modal.
  src/components/modal/base/modal.jsx
  src/components/modal/join/modal.jsx
  src/views/join/join.jsx
  test/unit/components/modal.test.jsx
Labels: pr - good to merge

#3396 Add Logo to join flow standalone page.
  src/views/join/join.jsx
  src/views/join/join.scss
Labels: pr - good to merge

#3389 Join flow navigate when finished
  src/components/join-flow/join-flow.jsx
  src/components/join-flow/welcome-step.jsx
  src/components/modal/join/modal.jsx
  src/components/registration/scratch3-registration.jsx
  src/l10n.json
  src/views/join/join.jsx
Labels: pr - good to merge

#3393 Join flow country placeholder
  src/components/join-flow/country-step.jsx
  src/l10n.json
Labels: pr - good to merge

#3397 Download and initial extension pages for forthcoming ChromeOS app launch
  src/components/extension-landing/extension-landing.jsx
  src/components/extension-landing/extension-requirements.jsx
  src/components/extension-landing/install-scratch-link.jsx
  src/components/install-scratch/install-scratch.jsx
  src/components/install-scratch/install-scratch.scss
  src/components/install-scratch/install-util.js
  src/components/os-chooser/os-chooser.jsx
  src/l10n.json
  src/lib/detect-os.js
  src/lib/feature-flags.js
  src/lib/os-enum.js
  src/views/boost/boost.jsx
  src/views/download/download.jsx
  src/views/download/download.scss
  src/views/download/l10n.json
  src/views/ev3/ev3.jsx
  src/views/ev3/ev3.scss
  src/views/ev3/l10n.json
  src/views/gdxfor/gdxfor.jsx
  src/views/microbit/l10n.json
  src/views/microbit/microbit.jsx
  src/views/wedo2/wedo2.jsx
  static/images/badges/google-play-badge.png
  static/images/badges/mac-store-badge.svg
  static/images/badges/windows-store-badge.svg
  static/images/ev3/chromeos-enter-passcode.png
  static/images/microbit/chromeos-copy-hex.png
  static/svgs/download/mac-badge.svg
  static/svgs/download/ms-badge.svg
  static/svgs/extensions/android.svg
  static/svgs/extensions/chromeos.svg
Labels: pr - needs review

#3384 gender step uses blank default, lcase values
  src/components/join-flow/gender-step.jsx
Labels: pr - good to merge

#3414 join flow bold text and related design tweaks
  src/components/formik-forms/formik-checkbox.scss
  src/components/join-flow/join-flow-step.scss
  src/components/join-flow/username-step.jsx
Labels: pr - good to merge

#3415 make validations semi-bold
  src/components/forms/validation-message.scss
Labels: pr - good to merge

#3416 change password default; remove unused state var
  src/components/join-flow/username-step.jsx
Labels: pr - good to merge

#3383 scratch3 join flow redirects to /join, outside editor
  src/components/navigation/www/navigation.jsx
  src/redux/navigation.js
  test/unit/components/navigation.test.jsx
Labels: pr - good to merge

#3362 format and update timing of join flow spinner
  src/components/join-flow/next-step-button.jsx
  src/components/join-flow/next-step-button.scss
  src/components/spinner/spinner.scss
Labels: pr - good to merge

#3418 move join flow modal down in small window widths
  src/components/modal/join/modal.scss
Labels: pr - good to merge
