Repository scratchfoundation/scratch-www, pull requests merged in 2019-10, with the labels that each got.

#3422 turn off automplete and autocorrect for join-flow inputs
  src/components/formik-forms/formik-radio-button.jsx
  src/components/join-flow/email-step.jsx
  src/components/join-flow/join-flow-step.jsx
  src/components/join-flow/username-step.jsx
Labels: pr - needs review

#3377 embed view with minimal functionality, route
  src/lib/sentry.js
  src/routes.json
  src/views/preview/embed-view.jsx
  src/views/preview/embed.jsx
  src/views/preview/project-view.jsx
Labels: pr - needs review

#3431 adjust join flow email centering
  src/components/join-flow/join-flow-steps.scss
Labels: pr - good to merge

#3430 Join flow responsive fixes
  src/components/join-flow/join-flow-step.scss
  src/components/join-flow/next-step-button.scss
  src/components/modal/join/modal.scss
  src/views/join/join.scss
Labels: pr - good to merge

#3425 truncate custom gender, and other inputs
  src/components/join-flow/email-step.jsx
  src/components/join-flow/gender-step.jsx
  src/components/join-flow/username-step.jsx
Labels: pr - good to merge

#3374 when looking for latest fastly VCL to clone, use only active VCLs
  bin/configure-fastly.js
  bin/lib/fastly-extended.js
  test/unit/lib/fastly-extended.test.js
Labels: pr - good to merge

#3445 Remove reference to Chrome/Android in FAQ
  src/views/faq/l10n.json
Labels: pr - good to merge

#3447 update gui with swahili changes
  package-lock.json
  package.json
Labels: localization

#3435 Join flow image preview using background color
  src/_colors.scss
  src/components/join-flow/birthdate-step.jsx
  src/components/join-flow/country-step.jsx
  src/components/join-flow/email-step.jsx
  src/components/join-flow/join-flow-step.jsx
  src/components/join-flow/join-flow-step.scss
  src/components/join-flow/join-flow-steps.scss
  src/components/join-flow/welcome-step.jsx
Labels: pr - good to merge

#3427 turn off automplete and autocorrect for join-flow inputs
  src/components/formik-forms/formik-radio-button.jsx
  src/components/join-flow/email-step.jsx
  src/components/join-flow/join-flow-step.jsx
  src/components/join-flow/username-step.jsx
Labels: pr - good to merge

#3434 Join flow responsive changes for input, button and select widths
  src/components/formik-forms/formik-radio-button.scss
  src/components/join-flow/join-flow-step.scss
  src/components/join-flow/join-flow-steps.scss
Labels: pr - good to merge

#3444 Add Sentry to Join Flow; set Sentry tags on various ErrorBoundaries
  src/components/errorboundary/errorboundary.jsx
  src/components/page/www/page.jsx
  src/views/join/join.jsx
  src/views/preview/embed-view.jsx
  src/views/preview/embed.jsx
  test/unit/components/errorboundary.test.jsx
Labels: needs discussion, pr - good to merge

#3417 Join flow cache remote
  src/components/join-flow/email-step.jsx
  src/components/join-flow/username-step.jsx
  test/unit/components/email-step.test.jsx
  test/unit/components/username-step.test.jsx
Labels: pr - good to merge

#3456 Hotfix TEST ONLY: artificially throw errors in 2 places to test Sentry changes
  src/components/join-flow/country-step.jsx
  src/views/preview/project-view.jsx
Labels: testing

#3458 [Master] Add redirects for Make it Fly and Imagine If tutorials
  src/routes.json
Labels: hotfix, pr - good to merge

#3459 [Develop] Add redirects for Make it Fly and Imagine If tutorials
  src/routes.json
Labels: hotfix, pr - good to merge

#3462 Join flow error state limit one retry
  src/components/join-flow/email-step.jsx
  src/components/join-flow/join-flow.jsx
  src/components/join-flow/registration-error-step.jsx
  src/l10n.json
  test/unit/components/join-flow.test.jsx
  test/unit/components/registration-error-step.test.jsx
Labels: pr - good to merge

#3423 make text selectable, so users can copy errors
  src/components/join-flow/join-flow-steps.scss
Labels: pr - good to merge

#3424 splash page join button works with new join flow
  src/components/intro/intro.jsx
  src/components/navigation/www/navigation.jsx
  src/redux/navigation.js
  test/unit/components/navigation.test.jsx
  test/unit/redux/navigation.test.js
Labels: pr - good to merge

#3468 fixed country options to use full country name string as option value
  src/lib/country-data.js
  test/unit/lib/country-data.test.js
Labels: pr - good to merge

#3469 Fix dev server by splitting up redirect regex
  src/routes.json
Labels: pr - good to merge

#3477 [Master] Update GUI to add 2 HoC tutorials
  package-lock.json
  package.json
Labels: hotfix, pr - needs review

#3486 Add translation resource mapping
  bin/build-locales
Labels: pr - good to merge

#3488 HoC Redirect to Talking Tales and Code a Cartoon
  src/routes.json
Labels: pr - good to merge

#3478 [Develop] Update GUI to add 2 HoC tutorials
  package-lock.json
  package.json
Labels: hotfix, pr - good to merge

#3495 Revert "fixed country options to use full country name string as option value"
  src/lib/country-data.js
  test/unit/lib/country-data.test.js
Labels: pr - needs review
