Repository scratchfoundation/scratch-www, pull requests merged in 2020-06, with the labels that each got.

#4071 [Master] update scratch-desktop download links for 3.11.1
  src/components/install-scratch/install-scratch.jsx
Labels: hotfix, pr - good to merge

#4070 [Develop] update scratch-desktop download links for 3.11.1
  src/components/install-scratch/install-scratch.jsx
Labels: hotfix, pr - good to merge

#2518 Fix page width by hiding overflow, letting stage width be flexible
  src/views/preview/preview.scss
Labels: pr - needs review

#4096 [Master] remove email opt-in from join flow
  src/components/join-flow/email-step.jsx
  src/components/join-flow/join-flow.jsx
  src/l10n.json
  test/unit/components/email-step.test.jsx
Labels: hotfix

#4097 [Develop] remove email opt-in from join flow
  src/components/join-flow/email-step.jsx
  src/components/join-flow/join-flow.jsx
  src/l10n.json
  test/unit/components/email-step.test.jsx
Labels: hotfix

#3974 move country name lookup to library
  src/components/registration/steps.jsx
  src/lib/country-data.js
  test/unit/lib/country-data.test.js
Labels: pr - good to merge, tech debt

#4026 Add node12 support, Fix #4025
  package-lock.json
  package.json
Labels: Low Severity, Medium Impact, developer facing, priority 3

#3776 Always apply min-height: 0
  src/components/modal/addtostudio/modal.scss
Labels: pr - changes requested, pr - needs review, priority 3

#4149 fix Safari fullscreen CSS bugs
  src/views/preview/preview.scss
Labels: pr - needs review

#4146 [Master] use 'evergreen' URLs for Scratch Desktop downloads
  src/components/install-scratch/install-scratch.jsx
Labels: hotfix, pr - needs review

#4145 [Develop] use 'evergreen' URLs for Scratch Desktop downloads
  src/components/install-scratch/install-scratch.jsx
Labels: hotfix, pr - good to merge

#4156 Redirect the old join flow to the new one.
  src/routes.json
Labels: pr - good to merge
