Repository scratchfoundation/scratch-www, pull requests merged in 2020-11, with the labels that each got.

#4588 [Master] Hotfix minor changes to annual report
  static/images/annual-report/reach/community-growth-graph.svg
Labels: hotfix, pr - good to merge

#4587 [Develop] Hotfix minor changes to annual report
  static/images/annual-report/reach/community-growth-graph.svg
Labels: hotfix, pr - good to merge

#4287 Replace "Tips Page" with "Ideas Page"
  src/views/about/l10n.json
Labels: pr - needs review

#4580 A few small upates to the muting modal
  src/components/modal/mute/modal.jsx
  src/components/modal/mute/modal.scss
  static/svgs/commenting/comment_feedback.svg
  static/svgs/commenting/mute_time.svg
Labels: pr - good to merge

#4616 Skeleton of code to show mute modal and comment status.
  src/views/preview/comment/compose-comment.jsx
  test/unit/components/compose-comment.test.jsx
Labels: pr - good to merge

#4286 Delete all Community Blocks Interview related files
  src/routes.json
  src/views/communityblocks-interviews/communityblocks-interviews.jsx
  static/pdfs/interviews/communityblocks/assent_form.pdf
  static/pdfs/interviews/communityblocks/consent_for_over_18.pdf
  static/pdfs/interviews/communityblocks/consent_for_parent.pdf
Labels: pr - needs review

#4284 update translation URL
  src/views/about/about.jsx
  src/views/about/l10n.json
Labels: blocked, pr - good to merge

#4615 Add link to annual report from about page
  src/views/about/about.jsx
  src/views/about/l10n.json
Labels: pr - good to merge

#4617 Annual Report - Break out supporters list into separate JSON
  src/views/annual-report/annual-report.jsx
  src/views/annual-report/supporters.json
Labels: pr - good to merge

#4637 Convert mute timestamp to always show in minutes.
  src/views/preview/comment/compose-comment.jsx
Labels: pr - good to merge

#4644 remove version number from micro:bit firmware URL
  src/views/microbit/microbit.jsx
Labels: pr - good to merge

#4643 [Hotfix/Master] Add the SEC page
  src/routes.json
  src/views/sec/l10n.json
  src/views/sec/sec.jsx
  src/views/sec/sec.scss
  static/images/sec/SEC-Top-img.svg
  static/images/sec/SEC-bottom-img.svg
Labels: pr - good to merge

#4653 [Master] HoC banner 2020
  src/views/splash/hoc/hoc-banner.scss
  src/views/splash/hoc/top-banner.jsx
  src/views/splash/l10n.json
  src/views/splash/presentation.jsx
  static/images/hoc/make-it-fly.jpg
Labels: hotfix, pr - good to merge

#4654 [Release] HOC banner 2020
  src/views/splash/hoc/hoc-banner.scss
  src/views/splash/hoc/top-banner.jsx
  src/views/splash/l10n.json
  src/views/splash/presentation.jsx
  static/images/hoc/make-it-fly.jpg
Labels: pr - good to merge

#4664 [Develop] HOC banner 2020
  src/views/splash/hoc/hoc-banner.scss
  src/views/splash/hoc/top-banner.jsx
  src/views/splash/l10n.json
  src/views/splash/presentation.jsx
  static/images/hoc/make-it-fly.jpg
Labels: hotfix, pr - good to merge

#4665 Change link to Teacher Account Setup Guide on Educators page
  src/views/teachers/landing/landing.jsx
Labels: pr - good to merge

#4655 Disable comment box functionality when you've just been muted.
  src/views/preview/comment/comment.scss
  src/views/preview/comment/compose-comment.jsx
  test/unit/components/compose-comment.test.jsx
Labels: pr - good to merge

#4683 Fix title metadata in financials pdf
  static/pdfs/annual-report/2019/2019_audited_financials.pdf
Labels: pr - good to merge

#4682 Add loading spinner in Annual Report
  src/components/video-preview/video-preview.jsx
  src/components/video-preview/video-preview.scss
  src/components/video/video.jsx
Labels: pr - good to merge
