Repository scratchfoundation/scratch-www, pull requests merged in 2020-05, with the labels that each got.

#3836 Alphabetize the credits page
  src/views/credits/people.json
Labels: pr - needs review

#3817 Helpwidget update
  src/components/helpform/helpform.jsx
  src/components/helpwidget/helpwidget.jsx
  src/components/helpwidget/helpwidget.scss
  src/l10n.json
  src/lib/feature-flags.js
  src/views/contact-us/contact-us.jsx
  src/views/contact-us/contact-us.scss
  src/views/contact-us/l10n.json
  test/localization-legacy/check_duplicate_strings.js
Labels: pr - good to merge

#3854 [Develop] release Scratch Desktop 3.10.2
  src/components/install-scratch/install-scratch.jsx
Labels: hotfix, pr - good to merge

#3855 [Master] release Scratch Desktop 3.10.2
  src/components/install-scratch/install-scratch.jsx
Labels: hotfix, pr - good to merge

#3847 Educator page mini update
  src/views/teachers/landing/l10n.json
  src/views/teachers/landing/landing.jsx
Labels: needs discussion, pr - good to merge

#3849 Move Andrew and Abisola to past contributors
  src/views/credits/credits.jsx
  src/views/credits/people.json
Labels: pr - good to merge

#3857 Second, smaller round of updates to the FAQ page.
  src/views/teachers/faq/faq.jsx
  src/views/teachers/faq/l10n.json
Labels: pr - good to merge, question

#3867 Put new help widget back behind feature flag
  src/views/contact-us/contact-us.jsx
Labels: critical, pr - good to merge

#3863 [Develop] Release 2020-05-07
  src/views/contact-us/contact-us.jsx
Labels: release

#3871 Enable Help widget
  src/views/contact-us/contact-us.jsx
Labels: pr - good to merge

#3856 default student's country to educator's during reg
  src/components/registration/steps.jsx
  src/views/studentregistration/studentregistration.jsx
Labels: pr - good to merge

#3973 Add disrespectful report option, reorder options
  src/components/modal/report/report-options.jsx
  src/l10n.json
Labels: pr - good to merge
