Repository scratchfoundation/scratch-www, pull requests merged in 2020-07, with the labels that each got.

#4179 add overflow settings to css for remix credit
  src/views/preview/preview.scss
Labels: pr - good to merge

#4144 updated blocks new scratcher sees
  src/components/welcome/welcome.scss
  static/images/welcome-learn.png
Labels: needs discussion, question

#4121 Set wiki link per user's selected language
  src/components/footer/www/footer.jsx
  src/lib/scratch-wiki.js
  test/unit/lib/scratch-wiki.test.js
Labels: Low Severity, Medium Impact, localization

#3799 Fix editor title when not logged in
  src/views/preview/meta.jsx
  src/views/preview/project-view.jsx
Labels: pr - needs review, priority 4

#4219 Make the cookie library set the SameSite cookie value to strict by default
  src/lib/jar.js
  test/unit/lib/jar.test.js
Labels: pr - good to merge

#4241 Removed skipped footer integration tests
  test/integration-legacy/smoke-testing/test_footer_links.js
Labels: pr - good to merge

#4249 Remove tap.plan() from footer links test
  test/integration-legacy/smoke-testing/test_footer_links.js
Labels: pr - needs review
