Repository scratchfoundation/scratch-www, pull requests merged in 2020-10, with the labels that each got.

#4263 [Develop] finish renaming 'Scratch Desktop' to 'Scratch'
  src/components/install-scratch/install-scratch.jsx
  src/views/download/l10n.json
  static/images/download/mac-install.png
Labels: pr - good to merge

#4456 Only run integration/smoke tests on specific branches
  .travis.yml
Labels: pr - good to merge

#4469 Move join integration tests to Jest, add some tests
  test/integration-legacy/smoke-testing/test-join.js
  test/integration/join.test.js
Labels: pr - good to merge

#4465 Move project page tests
  .travis.yml
  README.md
  test/integration-legacy/smoke-testing/test_project_page.js
  test/integration/project-page.test.js
Labels: pr - good to merge

#4498 [Master] Hotfix/remove onerror
  package-lock.json
  package.json
Labels: hotfix, pr - needs review

#4497 [Develop] Hotfix/remove onerror
  package-lock.json
  package.json
Labels: hotfix

#4482 Initial skeleton of mute modal.
  src/components/modal/mute/modal.jsx
  src/components/modal/mute/modal.scss
  src/components/modal/mute/mute-step.jsx
  test/unit/components/mute-modal.test.jsx
  test/unit/components/mute-step.test.jsx
Labels: pr - good to merge

#4495 Commenting status component.
  src/components/commenting-status/commenting-status.jsx
  src/components/commenting-status/commenting-status.scss
  static/svgs/project/comment-status.svg
  test/unit/components/commenting-status.test.jsx
Labels: pr - good to merge

#4318 Minor grammar fix in FAQ
  src/views/faq/l10n.json
Labels: priority 4

#4496 Skip failing project page test
  package-lock.json
  package.json
  test/integration/project-page.test.js
Labels: pr - needs review

#4477 Pull out the credit page's grid of people into a separate component
  src/components/people-grid/people-grid.jsx
  src/components/people-grid/people-grid.scss
  src/views/credits/credits.jsx
  src/views/credits/credits.scss
Labels: pr - good to merge

#4479 Move footer integration tests to jest
  test/integration-legacy/smoke-testing/test_footer_links.js
  test/integration/footer-links.test.js
Labels: pr - good to merge
