Repository scratchfoundation/scratch-www, pull requests merged in 2020-01, with the labels that each got.

#3484 count unicode characters as single characters
  src/lib/validate.js
  test/unit/lib/validate.test.js
Labels: pr - good to merge

#3590 corrected error messages that wrongly mentioned session
  src/redux/messages.js
  src/redux/splash.js
Labels: pr - needs review

#3634 [Master] Hotfix/mandrill outage page banner
  src/components/page/www/page.jsx
  src/components/title-banner/warning-banner.jsx
  src/components/title-banner/warning-banner.scss
  src/views/splash/presentation.jsx
Labels: pr - good to merge

#3624 [Develop] Hotfix/mandrill outage page banner
  src/components/page/www/page.jsx
  src/components/title-banner/warning-banner.jsx
  src/components/title-banner/warning-banner.scss
  src/views/splash/presentation.jsx
Labels: blocked, pr - good to merge

#3638 [DEVELOP] Hotfix/be fuzzles
  package-lock.json
Labels: hotfix, pr - good to merge

#3639 [MASTER] Bring in render hotfix to fix updateSilhouette doing nothing on SVGSkin before getTexture is called
  package-lock.json
  package.json
Labels: hotfix, pr - good to merge

#3643 Introduce new tx-push-www script to automate string push to transifex
  .travis.yml
  .tx/config
  bin/init-l10n-src
  bin/tx-push-www
  package.json
  src/views/preview-faq/l10n.json
  src/views/preview-faq/preview-faq.jsx
  src/views/preview-faq/preview-faq.scss
  src/views/tips/l10n-static.json
  src/views/tips/l10n.json
  src/views/tips/tips.jsx
  src/views/tips/tips.scss
  src/views/tips/ttt.json
Labels: pr - good to merge

#3640 Retry of the change that retries fetching session
  src/components/join-flow/join-flow.jsx
  src/lib/session.js
  src/redux/navigation.js
  src/redux/session.js
  test/unit/components/join-flow.test.jsx
  test/unit/lib/session.test.js
Labels: pr - good to merge

#3646 Merge develop to release branch
  .travis.yml
  .tx/config
  bin/init-l10n-src
  bin/tx-push-www
  package.json
  src/components/join-flow/join-flow.jsx
  src/lib/session.js
  src/redux/navigation.js
  src/redux/session.js
  src/views/preview-faq/l10n.json
  src/views/preview-faq/preview-faq.jsx
  src/views/preview-faq/preview-faq.scss
  src/views/tips/l10n-static.json
  src/views/tips/l10n.json
  src/views/tips/tips.jsx
  src/views/tips/tips.scss
  src/views/tips/ttt.json
  test/unit/components/join-flow.test.jsx
  test/unit/lib/session.test.js
Labels: release

#3650 Greenkeeper/scratch gui 0.1.0 prerelease.20200122215224
  package-lock.json
  package.json
Labels: pr - good to merge, release

#3649 [Master] Release for 2020-01-22
  .travis.yml
  .tx/config
  bin/init-l10n-src
  bin/tx-push-www
  package-lock.json
  package.json
  src/components/join-flow/join-flow.jsx
  src/lib/session.js
  src/redux/navigation.js
  src/redux/session.js
  src/views/preview-faq/l10n.json
  src/views/preview-faq/preview-faq.jsx
  src/views/preview-faq/preview-faq.scss
  src/views/tips/l10n-static.json
  src/views/tips/l10n.json
  src/views/tips/tips.jsx
  src/views/tips/tips.scss
  src/views/tips/ttt.json
  test/unit/components/join-flow.test.jsx
  test/unit/lib/session.test.js
Labels: pr - good to merge, release

#3648 [Develop] Release for 2020-01-22
  package-lock.json
  package.json
Labels: pr - good to merge, release

#3651 attempt to get travis cron job to only run translations
  .travis.yml
Labels: localization, pr - good to merge

#3647 Set language cookie domain to allow for cross-domain cookies
  src/components/languagechooser/languagechooser.jsx
Labels: localization, pr - good to merge

#3658 correct file location of tx-push-www script
  package.json
Labels: ergonomics, localization, pr - good to merge

#3663 Ensure that the old scratchlanguage cookie is removed if it exists.
  src/init.js
  src/views/preview/project-view.jsx
Labels: localization, pr - good to merge

#3667 Really delete the cookie
  src/init.js
Labels: pr - good to merge
