Repository scratchfoundation/scratch-www, pull requests merged in 2020-12, with the labels that each got.

#4709 Update the SeC page wording
  src/views/sec/l10n.json
Labels: pr - good to merge

#4635 Add a time formatting utility that formats a relative time in the future.
  src/components/modal/mute/modal.jsx
  src/lib/format-time.js
  src/views/preview/comment/compose-comment.jsx
  test/unit/components/compose-comment.test.jsx
  test/unit/lib/format-time.test.js
Labels: pr - changes requested

#4642 Circleci project setup
  .circleci/config.yml
  package.json
Labels: pr - good to merge

#4721 Show the comment status box on project page loads if the user is muted.
  src/views/preview/comment/compose-comment.jsx
  test/unit/components/compose-comment.test.jsx
Labels: pr - good to merge

#2763 Change min height
  src/main.scss
Labels: pr - needs review, question

#4752 Localize mute
  src/components/modal/mute/modal.jsx
  src/l10n.json
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/l10n.json
  test/unit/components/compose-comment.test.jsx
  test/unit/components/mute-modal.test.jsx
Labels: localization, pr - good to merge

#4751 Fix isMuted so it doesn't do an extra unit conversion.
  src/views/preview/comment/compose-comment.jsx
  test/unit/components/compose-comment.test.jsx
Labels: pr - good to merge

#4686 switch educator registration checkusername endpoint from scratchr2 to api
  src/components/registration/steps.jsx
  src/lib/validate.js
Labels: pr - good to merge

#4768 Fix prop type. muteStepContent is an array not a string.
  src/components/modal/mute/modal.jsx
Labels: pr - needs review

#4563 Add "FloralSunset" to Credits Page
  src/views/credits/people.json
Labels: pr - changes requested

#4774 Show warning message when user has been muted several times.
  src/components/modal/mute/modal.jsx
  src/l10n.json
  src/views/preview/comment/compose-comment.jsx
  static/svgs/commenting/warning.svg
  test/unit/components/compose-comment.test.jsx
  test/unit/components/mute-modal.test.jsx
Labels: pr - good to merge
