Repository scratchfoundation/scratch-www, pull requests merged in 2020-09, with the labels that each got.

#4370 Revert "Revert "Move my stuff tests to jest""
  README.md
  test/integration-legacy/smoke-testing/test-my-stuff.js
  test/integration/my-stuff.test.js
  test/integration/selenium-helpers.js
Labels: pr - good to merge

#4352 Fix my stuff tests
  test/integration/my-stuff.test.js
  test/integration/selenium-helpers.js
Labels: pr - changes requested

#4291 Add redirects for Animate a Character and Video Sensing Tutorials
  src/routes.json
Labels: pr - good to merge

#4435 Stop running smoke tests unless the branch pushes to prod or staging.
  .travis.yml
Labels: pr - good to merge

#4420 Pin chrome version for saucelabs to chromedriver version
  test/integration/selenium-helpers.js
Labels: pr - good to merge, testing
