Repository scratchfoundation/scratch-www, pull requests merged in 2020-08, with the labels that each got.

#4265 Update node version used by travis and node-sass
  .travis.yml
  package-lock.json
  package.json
Labels: pr - good to merge

#4266 Hotfix/cookie rollback Revert samesite cookie change
  src/lib/jar.js
  test/unit/lib/jar.test.js
Labels: hotfix

#4274 Fix bad variable interpolation/calculation in frameless scss
  src/_frameless.scss
Labels: pr - good to merge

#4279 [Master] Release 2020-08-06
  .travis.yml
  package-lock.json
  package.json
  src/_frameless.scss
Labels: release

#4280 [Develop] Release 2020-08-06
  package-lock.json
  package.json
Labels: release

#4281 Make the cookie library set the SameSite cookie value to Lax by default
  src/lib/jar.js
  test/unit/lib/jar.test.js
Labels: pr - good to merge

#4290 Update sign-in-and-out integration tests for new chromedriver
  test/integration/sign-in-and-out.test.js
Labels: pr - good to merge

#4169 Exponentially back off the time between message polling instead of do…
  src/components/navigation/www/navigation.jsx
  test/unit/components/navigation.test.jsx
Labels: pr - good to merge

#4216 Add overflow, white-space and text-overflow CSS elements
  src/components/thumbnail/thumbnail.scss
Labels: High Impact, Low Severity, pr - good to merge

#4261 Move my stuff tests to jest
  README.md
  test/integration-legacy/smoke-testing/test-my-stuff.js
  test/integration/my-stuff.test.js
Labels: pr - good to merge

#4356 Revert "Move my stuff tests to jest"
  README.md
  test/integration-legacy/smoke-testing/test-my-stuff.js
  test/integration/my-stuff.test.js
Labels: pr - good to merge
