Repository scratchfoundation/scratch-www, pull requests merged in 2020-03, with the labels that each got.

#3723 [Master] Update conference page to open registration
  src/views/conference/2020/index/index.jsx
  src/views/conference/2020/index/l10n.json
Labels: hotfix, pr - good to merge

#3724 [Develop] Update conference page to open registration
  src/views/conference/2020/index/index.jsx
  src/views/conference/2020/index/l10n.json
Labels: hotfix, pr - good to merge

#3729 [Master] Split out message about conference registration delay
  src/views/conference/2020/index/index.jsx
  src/views/conference/2020/index/l10n.json
Labels: hotfix, pr - good to merge

#3730 [Develop] Split out message about conference registration delay
  src/views/conference/2020/index/index.jsx
  src/views/conference/2020/index/l10n.json
Labels: hotfix, pr - good to merge

#3731 Bump scratch-gui for release
  package-lock.json
  package.json
Labels: pr - good to merge

#3733 [Master] Release for 2020-03-03
  package-lock.json
  package.json
Labels: pr - good to merge, release

#3719 Add new Contact Us information page
  src/components/helpform/helpform.jsx
  src/components/informationpage/informationpage.scss
  src/routes.json
  src/views/contact-us/contact-us.jsx
  src/views/contact-us/l10n.json
Labels: pr - good to merge

#3737 [Develop] hotfix/scratch desktop 3.9.0
  src/components/install-scratch/install-scratch.jsx
Labels: hotfix, pr - good to merge

#3738 [Master] hotfix/scratch desktop 3.9.0
  src/components/install-scratch/install-scratch.jsx
Labels: hotfix, pr - good to merge

#3746 Fix contact-us mistakes
  src/components/helpform/helpform.jsx
  src/routes.json
  src/views/contact-us/contact-us.jsx
Labels: pr - good to merge

#3750 revert gui to previous version
  package-lock.json
  package.json
Labels: pr - good to merge

#3749 Fix image links
  src/components/extension-landing/extension-requirements.jsx
  src/components/install-scratch/install-scratch.jsx
  src/views/download/download.jsx
  src/views/ideas/ideas.jsx
Labels: pr - needs review

#3747 [Hotfix/Master] Split project report flow into two steps
  src/components/modal/base/modal.scss
  src/components/modal/report/form-step.jsx
  src/components/modal/report/modal.jsx
  src/components/modal/report/modal.scss
  src/components/modal/report/report-options.js
Labels: pr - good to merge

#3740 Educator faq updates
  src/views/teachers/faq/faq.jsx
  src/views/teachers/faq/l10n.json
Labels: pr - good to merge

#3765 Move reCaptcha code to a component
  src/components/captcha/captcha.jsx
  src/components/join-flow/email-step.jsx
  test/unit/components/captcha.test.jsx
  test/unit/components/email-step.test.jsx
Labels: pr - good to merge

#3774 Captcha adjustments to teacher registration
  src/components/registration/steps.jsx
  src/views/teacherregistration/teacherregistration.jsx
Labels: pr - good to merge
