Repository scratchfoundation/scratch-www, pull requests merged in 2020-02, with the labels that each got.

#3668 Add comments.isNotPermitted string
  src/l10n.json
Labels: pr - good to merge

#3672 Add FAQ about updating the app
  src/views/download/download.jsx
  src/views/download/l10n.json
Labels: pr - needs review

#3691 [Master] Release 2020-02-13
  package-lock.json
  package.json
Labels: release

#3692 [Develop] Release 2020-02-13
  package-lock.json
  package.json
Labels: release

#3676 use api instead of scratchr2 to validate usernames
  src/lib/validate.js
Labels: pr - good to merge
