Repository scratchfoundation/scratch-www, pull requests merged in 2020-04, with the labels that each got.

#3789 [Master] Report subcategories
  src/components/modal/report/modal.jsx
  src/components/modal/report/modal.scss
  src/components/modal/report/report-options.js
  src/components/modal/report/report-options.jsx
  src/l10n.json
Labels: hotfix

#3785 [Develop] Add nested categories to project report module
  src/components/modal/report/modal.jsx
  src/components/modal/report/modal.scss
  src/components/modal/report/report-options.js
  src/components/modal/report/report-options.jsx
  src/l10n.json
Labels: pr - good to merge

#3790 Update project report copy
  src/components/modal/report/modal.jsx
  src/components/modal/report/report-options.jsx
  src/l10n.json
Labels: pr - good to merge

#3788 added /signup/TOKEN route; handle route alongside existing student signup route
  src/lib/route.js
  src/routes.json
  src/views/studentregistration/studentregistration.jsx
  test/unit/lib/route.test.js
Labels: pr - good to merge

#3801 Fix gh-3781: Delay Scratch Conference
  src/views/conference/2020/index/index.jsx
  src/views/conference/2020/index/l10n.json
Labels: pr - good to merge

#3710 Localize activity messages
  src/views/splash/l10n.json
  src/views/splash/presentation.jsx
Labels: localization, pr - good to merge

#3800 Freshdesk widget
  src/components/helpform/helpform.jsx
  src/components/helpwidget/helpwidget.jsx
  src/l10n.json
  src/lib/feature-flags.js
  src/views/contact-us/contact-us.jsx
  src/views/contact-us/contact-us.scss
  src/views/contact-us/l10n.json
Labels: pr - good to merge

#3804 remove extraneous parenthesis from student signup route
  src/routes.json
Labels: pr - needs review

#3805 [Master] Hotfix: Remove last names from credits page
  src/views/credits/people.json
Labels: pr - good to merge

#3786 Split follow splash into FollowUser and FollowStudio
  src/views/splash/activity-rows/follow-studio.jsx
  src/views/splash/activity-rows/follow-user.jsx
  src/views/splash/activity-rows/follow.jsx
  src/views/splash/l10n.json
  src/views/splash/presentation.jsx
Labels: pr - good to merge

#3436 Join flow info button has larger touch target, can be clicked to toggle
  src/components/info-button/info-button.jsx
  src/components/info-button/info-button.scss
  src/components/join-flow/join-flow-steps.scss
  static/svgs/info-button/info-button.svg
  test/unit/components/info-button.test.jsx
Labels: pr - good to merge

#3807 Change up the messaging in student registration.
  src/components/registration/steps.jsx
  src/components/registration/steps.scss
  src/l10n.json
  src/views/studentregistration/studentregistration.jsx
Labels: pr - good to merge

#3569 Remove app flag
  src/components/extension-landing/extension-requirements.jsx
  src/components/install-scratch/install-scratch.jsx
  src/components/os-chooser/os-chooser.jsx
  src/l10n.json
  src/lib/detect-os.js
  src/lib/feature-flags.js
  src/views/download/download.jsx
  src/views/download/l10n.json
Labels: pr - good to merge

#3819 Add subcategories for scary project report
  src/components/modal/report/report-options.jsx
  src/l10n.json
Labels: pr - good to merge

#3830 Add new member's name
  src/views/credits/people.json
Labels: pr - needs work
