Repository scratchfoundation/scratch-www, pull requests merged in 2021-11, with the labels that each got.

#6243 Replace static plural rule and relative time polyfills with a dynamic import
  package-lock.json
  package.json
  src/init.js
  src/lib/format-time.js
  src/lib/intl-polyfill.js
  src/lib/relative-time-polyfill.js
  static/js/polyfill.min.js
Labels: pr - needs review

#6179 Copy changes to research page
  src/views/research/l10n.json
  src/views/research/research.jsx
Labels: pr - good to merge

#6233 Add project and studio reply integration tests
  test/integration/comments.test.js
Labels: pr - good to merge

#6204 Removed a broken link from the For Parents page
  src/views/parents/l10n.json
  src/views/parents/parents.jsx
Labels: pr - good to merge

#6285 Take 2: Replace static plural rule and relative time polyfills with a dynamic import
  .babelrc
  package-lock.json
  package.json
  src/init.js
  src/lib/format-time.js
  src/lib/intl-polyfill.js
  src/lib/relative-time-polyfill.js
  static/js/polyfill.min.js
Labels: pr - needs review

#6254 Update About page copy
  src/views/about/about.jsx
  src/views/about/l10n.json
Labels: pr - good to merge

#6284 Add a partial profile reply integration test
  test/integration/comments.test.js
Labels: pr - good to merge

#6287 Convert login failure integration tests from tap to jest
  package-lock.json
  package.json
  test/integration-legacy/smoke-testing/test-login-failures.js
  test/integration/selenium-helpers.js
  test/integration/sign-in-and-out.test.js
Labels: pr - good to merge

#6292 Move Search integration tests from Tap to Jest
  test/integration-legacy/smoke-testing/test_search.js
  test/integration/search.test.js
Labels: pr - good to merge

#6295 Convert integration tests for statistics page from Tap to Jest
  test/integration-legacy/smoke-testing/test_statistics_page.js
  test/integration/statistics.test.js
Labels: pr - good to merge

#6298 Don't try to run non-existent tap integration tests
  .circleci/config.yml
  package.json
Labels: pr - good to merge

#6302 CircleCI use correct integration test command
  .circleci/config.yml
Labels: pr - good to merge

#6300 [Hotfix] Annual Report 2020
  src/components/text-and-media-snippet/text-and-media-snippet.jsx
  src/components/text-and-media-snippet/text-and-media-snippet.scss
  src/components/timeline-card/timeline-card.jsx
  src/components/timeline-card/timeline-card.scss
  src/lib/frameless.js
  src/routes.json
  src/views/annual-report/2020/annual-report.jsx
  src/views/annual-report/2020/annual-report.scss
  src/views/annual-report/2020/country-blurb/country-blurb.jsx
  src/views/annual-report/2020/country-blurb/country-blurb.scss
  src/views/annual-report/2020/l10n.json
  src/views/annual-report/2020/people.json
  src/views/annual-report/2020/supporters.json
  static/images/annual-report/2020/connectivity/isiXhosa_scratcheditor.jpg
  static/images/annual-report/2020/connectivity/isiXhosa_scratcheditor.png
Labels: pr - good to merge, hotfix, release

#6301 [Develop] Annual report fixes
  src/components/text-and-media-snippet/text-and-media-snippet.jsx
  src/components/text-and-media-snippet/text-and-media-snippet.scss
  src/components/timeline-card/timeline-card.jsx
  src/components/timeline-card/timeline-card.scss
  src/lib/frameless.js
  src/routes.json
  src/views/annual-report/2020/annual-report.jsx
  src/views/annual-report/2020/annual-report.scss
  src/views/annual-report/2020/country-blurb/country-blurb.jsx
  src/views/annual-report/2020/country-blurb/country-blurb.scss
  src/views/annual-report/2020/l10n.json
  src/views/annual-report/2020/people.json
  src/views/annual-report/2020/supporters.json
  static/images/annual-report/2020/connectivity/isiXhosa_scratcheditor.jpg
  static/images/annual-report/2020/connectivity/isiXhosa_scratcheditor.png
Labels: hotfix, release

#6330 [Master][Hotfix] HOC Banner 2021
  src/views/splash/donate/donate-banner.scss
  src/views/splash/hoc/hoc-banner.scss
  src/views/splash/hoc/top-banner.jsx
  src/views/splash/l10n.json
  src/views/splash/presentation.jsx
  src/views/splash/splash.jsx
  static/images/hoc/chase-game.jpg
  static/images/hoc/make-music.jpg
Labels: pr - good to merge, hotfix, release

#6337 Updated parents page with information about scratch foundation
  src/views/parents/l10n.json
  src/views/parents/parents.jsx
Labels: pr - good to merge
