Repository scratchfoundation/scratch-www, pull requests merged in 2021-06, with the labels that each got.

#5500 Add comments not allowed box
  src/views/preview/comment/comment.scss
  src/views/preview/comment/compose-comment.jsx
  src/views/studio/icons/edit-icon.svg
  src/views/studio/l10n.json
  src/views/studio/studio-comments-not-allowed.jsx
  src/views/studio/studio-comments.jsx
  src/views/studio/studio.scss
Labels: pr - good to merge

#5503 Add "Promote to manager" modal
  src/views/studio/l10n.json
  src/views/studio/modals/promote-modal.jsx
  src/views/studio/modals/promote-modal.scss
  src/views/studio/studio-member-tile.jsx
  static/svgs/studio/promote-illustration.svg
Labels: pr - good to merge

#5495 Comment thread limit
  src/l10n.json
  src/views/preview/comment/comment.jsx
  src/views/preview/comment/comment.scss
  src/views/preview/comment/top-level-comment.jsx
  src/views/studio/studio-comments.jsx
Labels: pr - needs review

#5538 Fix l10n string ID where it previously got missed.
  src/views/preview/comment/top-level-comment.jsx
Labels: pr - good to merge

#5541 Fix reply status box alignment.
  src/views/preview/comment/comment.scss
Labels: pr - good to merge

#5539 Use reply_count to check whether reply limit is reached
  src/views/preview/comment/top-level-comment.jsx
  src/views/studio/studio-comments.jsx
Labels: pr - good to merge

#5567 When a user gets muted, update mute status in the session
  src/redux/session.js
  src/views/preview/comment/compose-comment.jsx
Labels: pr - good to merge

#5561 handle project comments turned off
  src/components/commenting-status/commenting-status.scss
  src/redux/session.js
  src/views/preview/l10n.json
  src/views/preview/presentation.jsx
  src/views/preview/preview.scss
  src/views/preview/project-view.jsx
  static/images/comments/comment-placeholder.png
Labels: pr - good to merge

#5585 "Add to studio" modal empty states and done button
  src/views/studio/l10n.json
  src/views/studio/modals/user-projects-modal.jsx
  src/views/studio/modals/user-projects-modal.scss
  static/svgs/studio/add-to-studio-empty.svg
Labels: pr - needs review

#5588 Studio Manager Limit
  src/redux/studio.js
  src/views/studio/l10n.json
  src/views/studio/lib/studio-member-actions.js
  src/views/studio/modals/manager-limit-modal.jsx
  src/views/studio/modals/manager-limit-modal.scss
  src/views/studio/modals/promote-modal.jsx
  src/views/studio/modals/promote-modal.scss
  src/views/studio/studio-curator-invite.jsx
  src/views/studio/studio-info-box.jsx
  src/views/studio/studio-managers.jsx
  src/views/studio/studio-member-tile.jsx
  src/views/studio/studio.scss
  static/svgs/studio/manager-limit-illustration.svg
Labels: pr - good to merge

#5580 Make the title scroll after a certain length, and long words wrap
  src/views/studio/studio.scss
Labels: pr - good to merge

#5578 Make the default nav button state white
  src/views/studio/studio-tab-nav.jsx
  src/views/studio/studio.scss
Labels: pr - good to merge

#5496 Bump Conference 2020 to 2021 (Take 2)
  src/components/footer/conference/2021/footer.jsx
  src/components/navigation/conference/2021/navigation.jsx
  src/components/navigation/conference/2021/navigation.scss
  src/components/page/conference/2021/page.jsx
  src/routes.json
  src/views/conference/2020/index/l10n.json
  src/views/conference/2021/index/index.jsx
  src/views/conference/2021/index/index.scss
  src/views/conference/2021/index/l10n.json
  static/images/conference/index/2021/title-banner.jpg
  test/integration/footer-links.test.js
Labels: pr - good to merge

#5577 Show errors when studio edit gets a muted response from backend
  src/redux/studio-mutations.js
  src/views/studio/l10n.json
  src/views/studio/lib/studio-member-actions.js
  src/views/studio/lib/studio-project-actions.js
  src/views/studio/studio-comments-allowed.jsx
  src/views/studio/studio-curator-inviter.jsx
  src/views/studio/studio-description.jsx
  src/views/studio/studio-image.jsx
  src/views/studio/studio-mute-edit-message.jsx
  src/views/studio/studio-open-to-all.jsx
  src/views/studio/studio-project-adder.jsx
  src/views/studio/studio-projects.jsx
  src/views/studio/studio-title.jsx
  src/views/studio/studio.jsx
Labels: pr - good to merge

#5608 Adjust thumbnail css
  src/views/studio/modals/studio-report-modal.scss
  src/views/studio/studio.scss
Labels: pr - good to merge

#5573 Muted users can’t add projects to studio via project page
  src/redux/session.js
  src/views/preview/l10n.json
  src/views/preview/preview.scss
  src/views/preview/subactions.jsx
  src/views/preview/subactions.scss
  src/views/studio/studio-mute-edit-message.jsx
Labels: pr - good to merge

#5614 run jest integration tests with --runInBand
  package.json
Labels: pr - good to merge

#5594 update maintenance and trouble page static content
  static/cdn/maintenance.html
  static/cdn/trouble.html
Labels: pr - good to merge

#5621 Studio creators and managers can delete their own comments
  src/redux/studio-permissions.js
  src/views/studio/studio-comments.jsx
  test/unit/redux/studio-permissions.test.js
Labels: pr - good to merge

#5620 Admins can view deleted studios
  src/lib/admin-requests.js
  src/redux/studio.js
  src/views/studio/l10n.json
  src/views/studio/lib/studio-activity-actions.js
  src/views/studio/lib/studio-member-actions.js
  src/views/studio/lib/studio-project-actions.js
  src/views/studio/studio-deleted.jsx
  src/views/studio/studio-info.jsx
  src/views/studio/studio.jsx
  src/views/studio/studio.scss
Labels: pr - good to merge

#5626 Studio single comment view
  src/views/studio/studio-comments.jsx
  src/views/studio/studio.scss
Labels: pr - needs review

#5587 Studio comments off
  src/redux/session.js
  src/redux/studio-permissions.js
  src/views/studio/l10n.json
  src/views/studio/studio-comments.jsx
  src/views/studio/studio.scss
  test/unit/components/studio-comments.test.jsx
  test/unit/redux/studio-permissions.test.js
Labels: pr - good to merge

#5627 Fix preventing muted users from adding projects via project page
  src/redux/session.js
  src/views/preview/l10n.json
  src/views/preview/preview.scss
  src/views/preview/subactions.jsx
  src/views/preview/subactions.scss
  src/views/studio/studio-mute-edit-message.jsx
Labels: pr - good to merge

#5635 [Master] Hotfix new emojis
  static/images/emoji/blm.png
  static/images/emoji/pride.png
Labels: pr - needs review

#5636 [Develop] Hotfix new emojis
  static/images/emoji/blm.png
  static/images/emoji/pride.png
Labels: pr - needs review

#5607 Make the border of editable fields dashed gray for studios. Otherwise, make them match the fields on project pages
  src/views/studio/studio-description.jsx
  src/views/studio/studio-title.jsx
  src/views/studio/studio.scss
Labels: pr - good to merge

#5609 Adjust responsive boundaries for grid reflow
  src/views/studio/studio.scss
Labels: pr - good to merge

#5633 Improve errors around following studios
  package-lock.json
  package.json
  src/.eslintrc.js
  src/views/studio/debug.jsx
  src/views/studio/l10n.json
  src/views/studio/studio-activity.jsx
  src/views/studio/studio-curators.jsx
  src/views/studio/studio-follow.jsx
  src/views/studio/studio-managers.jsx
  src/views/studio/studio-projects.jsx
  src/views/studio/studio.scss
Labels: pr - needs review

#5631 Switch studios route to real version for testing on staging
  src/routes.json
Labels: pr - good to merge

#5632 Style fixes for "add to studio" modal
  src/views/studio/modals/user-projects-modal.jsx
  src/views/studio/modals/user-projects-modal.scss
Labels: pr - needs review

#5647 Only show reply button when comments are allowed on a studio
  src/views/studio/studio-comments.jsx
Labels: pr - good to merge

#5645 Fix admin panel space remaining after logging out
  src/views/studio/studio-admin-panel.jsx
  test/unit/components/studio-admin-panel.test.jsx
Labels: pr - good to merge

#5652 Replace pngs with svgs
  src/views/studio/studio-curators.jsx
  src/views/studio/studio-projects.jsx
  static/images/studios/curators-empty-image.svg
  static/images/studios/curators-empty.png
  static/images/studios/empty-state-image-mini.svg
  static/images/studios/empty-state-image.svg
  static/images/studios/projects-empty-can-add.png
  static/images/studios/projects-empty.png
Labels: pr - good to merge

#5653 Studio tab nav button styling
  src/views/studio/studio.scss
Labels: pr - good to merge

#5649 Fix permissions issues on studio comments
  src/redux/studio-permissions.js
  src/views/preview/comment/top-level-comment.jsx
  src/views/studio/studio-comment.js
  src/views/studio/studio-comments.jsx
  test/unit/components/studio-comments.test.jsx
  test/unit/redux/studio-permissions.test.js
Labels: pr - needs review

#5651 Update the reply_count when you leave a reply
  src/redux/comments.js
  test/unit-legacy/redux/comments-test.js
Labels: pr - good to merge

#5630 Only request replies if reply_count > 0
  src/redux/project-comment-actions.js
  src/redux/studio-comment-actions.js
Labels: blocked

#5658 Match Add Project placeholder & button text to old studios
  src/views/studio/l10n.json
  src/views/studio/studio-project-adder.jsx
Labels: pr - good to merge

#5659 Change manager modal width
  src/views/studio/modals/promote-modal.scss
Labels: pr - good to merge

#5670 Use errors from project adder in the add to studio modal
  src/views/studio/modals/user-projects-tile.jsx
  src/views/studio/studio-project-adder.jsx
Labels: pr - needs review

#5671 Studio page integration tests
  package-lock.json
  package.json
  test/integration/homepage-rows.test.js
  test/integration/my-stuff.test.js
  test/integration/studios-page.test.js
Labels: pr - good to merge
