Repository scratchfoundation/scratch-www, pull requests merged in 2021-07, with the labels that each got.

#5697 Load full rows for projects, curators, managers
  src/views/studio/lib/studio-member-actions.js
  src/views/studio/lib/studio-project-actions.js
  src/views/studio/modals/user-projects-modal.jsx
  src/views/studio/modals/user-projects-modal.scss
  src/views/studio/studio-activity.jsx
  src/views/studio/studio-curators.jsx
  src/views/studio/studio-managers.jsx
  src/views/studio/studio-projects.jsx
  src/views/studio/studio.scss
Labels: pr - good to merge

#5662 Create detailed unit tests for studio-member-actions
  src/lib/configure-store.js
  src/lib/render.jsx
  src/views/studio/lib/studio-activity-actions.js
  src/views/studio/lib/studio-member-actions.js
  src/views/studio/lib/studio-project-actions.js
  src/views/studio/studio-redux.js
  src/views/studio/studio.jsx
  test/unit/redux/project-comment-actions.test.js
  test/unit/redux/studio-activity-actions.test.js
  test/unit/redux/studio-comment-actions.test.js
  test/unit/redux/studio-member-actions.test.js
  test/unit/redux/studio-project-actions.test.js
Labels: pr - needs review

#5711 check rate limit for studio creation integration test
  test/integration/my-stuff.test.js
Labels: pr - good to merge, pr - needs review

#5718 Update SEC landing page with list of participating orgs and partner orgs
  src/views/sec/l10n.json
  src/views/sec/sec.jsx
  src/views/sec/sec.scss
Labels: pr - needs review

#5722 test(studios): fix failing permissions tests for studios
  test/unit/redux/studio-permissions.test.js
Labels: pr - good to merge
