Repository scratchfoundation/scratch-www, pull requests merged in 2021-04, with the labels that each got.

#5218 Move the studio route from routes-dev.json to routes.json
  src/routes-dev.json
  src/routes.json
Labels: pr - good to merge

#5217 Studio Comments Fetching & Initial UI
  src/redux/studio-comment-actions.js
  src/views/preview/comment/comment.jsx
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/comment/top-level-comment.jsx
  src/views/preview/presentation.jsx
  src/views/studio/studio-comments.jsx
  src/views/studio/studio.jsx
Labels: pr - good to merge

#5219 Include onAddComment for studio comments
  src/views/studio/studio-comments.jsx
Labels: pr - good to merge

#5227 Revert "[Master] Hotfix/totally normal 2021"
  package-lock.json
  package.json
  src/components/cats/cats.jsx
  src/components/cats/cats.scss
  src/components/footer/www/footer.jsx
  src/components/grid/grid.jsx
  src/components/grid/grid.scss
  src/components/thumbnail/thumbnail.jsx
  src/components/thumbnail/thumbnail.scss
  src/template.ejs
  src/views/search/search.jsx
  static/images/cats/1.jpg
  static/images/cats/2.jpg
  static/images/cats/3.jpg
  static/images/cats/4.jpg
  static/images/cats/Cat1.jpg
  static/images/cats/Cat10.png
  static/images/cats/Cat11.png
  static/images/cats/Cat12.png
  static/images/cats/Cat13.png
  static/images/cats/Cat14.png
  static/images/cats/Cat2.jpg
  static/images/cats/Cat3.jpg
  static/images/cats/Cat4.jpg
  static/images/cats/Cat5.jpg
  static/images/cats/Cat6.png
  static/images/cats/Cat7.jpg
  static/images/cats/Cat8.jpg
  static/images/cats/Cat9.jpg
  static/images/cats/IMG_0071.jpg
  static/images/cats/IMG_0122.jpg
  static/images/cats/IMG_0135.jpg
  static/images/cats/IMG_0288.jpg
  static/images/cats/IMG_0504.jpg
  static/images/cats/IMG_0681.jpg
  static/images/cats/IMG_0684.jpg
  static/images/cats/IMG_0698.jpg
  static/images/cats/IMG_1092.jpg
  static/images/cats/IMG_1157.jpg
  static/images/cats/IMG_1463.jpg
  static/images/cats/IMG_1696.jpg
  static/images/cats/IMG_1977.jpg
  static/images/cats/IMG_2167.jpg
  static/images/cats/IMG_2507.jpg
  static/images/cats/IMG_2681.jpg
  static/images/cats/IMG_2775.jpg
  static/images/cats/IMG_2776.jpg
  static/images/cats/IMG_3218.jpg
  static/images/cats/IMG_4316.jpg
  static/images/cats/IMG_5396.jpg
  static/images/cats/IMG_5880.jpg
  static/images/cats/IMG_6020.jpg
  static/images/cats/IMG_6521.jpg
  static/images/cats/IMG_6558.jpg
  static/images/cats/IMG_9587.jpg
  static/images/cats/IMG_9766.jpg
  static/images/cats/IMG_9775.jpg
  static/images/cats/cat-meme.jpg
  static/images/cats/cat-meme2.jpg
  static/svgs/space-cat.svg
Labels: release

#5176 Add initial selectors for studio permissions
  package-lock.json
  package.json
  src/redux/session.js
  src/redux/studio.js
  src/views/studio/studio-comments.jsx
  src/views/studio/studio-info.jsx
  src/views/studio/studio-projects.jsx
  test/helpers/state-fixtures.json
  test/unit/redux/session.test.js
  test/unit/redux/studio.test.js
Labels: pr - needs review

#5231 Use getState in thunks instead of passing props around
  src/redux/comments.js
  src/redux/studio-comment-actions.js
  src/redux/studio.js
  src/views/studio/studio-comments.jsx
  src/views/studio/studio-info.jsx
  src/views/studio/studio.jsx
Labels: pr - good to merge

#5262 [Master] Release 2021-04-15
  .circleci/config.yml
  .travis.yml
  package-lock.json
  package.json
  src/components/grid/grid.json
  src/redux/comments.js
  src/redux/preview.js
  src/redux/project-comment-actions.js
  src/redux/session.js
  src/redux/studio-comment-actions.js
  src/redux/studio.js
  src/routes-dev.json
  src/routes.json
  src/views/components/components.jsx
  src/views/components/components.scss
  src/views/preview/comment/comment.jsx
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/comment/top-level-comment.jsx
  src/views/preview/presentation.jsx
  src/views/preview/preview.jsx
  src/views/preview/project-view.jsx
  src/views/scratch_1.4/l10n.json
  src/views/studio/studio-comments.jsx
  src/views/studio/studio-info.jsx
  src/views/studio/studio-projects.jsx
  src/views/studio/studio.jsx
  test/helpers/state-fixtures.json
  test/unit-legacy/redux/comments-test.js
  test/unit-legacy/redux/preview-test.js
  test/unit/redux/session.test.js
  test/unit/redux/studio.test.js
Labels: release

#5237 Hook up remaining comment actions for studio comments
  src/redux/studio-comment-actions.js
  src/redux/studio.js
  src/views/studio/studio-comments.jsx
  test/unit/redux/studio.test.js
Labels: pr - good to merge

#5263 [Develop] Release 2021-04-15
  package-lock.json
Labels: release

#5269 Move deploy and integration tests to circle
  .circleci/config.yml
  .travis.yml
Labels: pr - good to merge

#5279 Move comment mute strings to general l10n file
  src/l10n.json
  src/views/preview/l10n.json
Labels: pr - needs review

#5274 Add client-side editing of studio info
  src/redux/session.js
  src/redux/studio-mutations.js
  src/redux/studio-permissions.js
  src/redux/studio.js
  src/views/studio/studio-comments-allowed.jsx
  src/views/studio/studio-comments.jsx
  src/views/studio/studio-description.jsx
  src/views/studio/studio-follow.jsx
  src/views/studio/studio-image.jsx
  src/views/studio/studio-info.jsx
  src/views/studio/studio-open-to-all.jsx
  src/views/studio/studio-projects.jsx
  src/views/studio/studio-title.jsx
  src/views/studio/studio.jsx
  test/unit/redux/session.test.js
  test/unit/redux/studio-permissions.test.js
Labels: pr - changes requested

#5280 Reset studio comments when admin logs in
  src/views/studio/studio-comments.jsx
  test/unit/components/studio-comments.test.jsx
Labels: pr - changes requested
