Repository scratchfoundation/scratch-www, pull requests merged in 2021-09, with the labels that each got.

#5992 More transfer host modal fixes
  src/views/studio/lib/studio-member-actions.js
  src/views/studio/modals/transfer-host-confirmation.jsx
  src/views/studio/modals/transfer-host-modal.scss
  src/views/studio/modals/transfer-host-selection.jsx
  src/views/studio/studio-managers.jsx
Labels: pr - good to merge

#6034 Too many password attempts error
  src/views/studio/l10n.json
  src/views/studio/lib/studio-member-actions.js
  src/views/studio/modals/transfer-host-confirmation.jsx
  test/unit/redux/studio-member-actions.test.js
Labels: pr - needs review

#6007 Add studio transfer test
  test/integration/studios-page.test.js
Labels: pr - good to merge

#6061 Change copy of transfer rate-limit error
  src/views/studio/l10n.json
Labels: pr - good to merge

#6062 Make /educators routes robust to querystrings
  src/routes.json
Labels: pr - needs review

#6063 Ignore querystrings when matching routes
  bin/configure-fastly.js
Labels: pr - good to merge

#5114 converted images around splash video to png, smaller file size
  src/components/intro/intro.scss
  static/svgs/intro/background-cropped.svg
  static/svgs/intro/background.svg
Labels: pr - good to merge, palooza

#6071 Add integration tests leaving comments on projects, studios, and profiles
  test/integration/comments.test.js
Labels: pr - good to merge

#6078 Use studio "host" in state, and accept "host" from api
  src/redux/studio-permissions.js
  src/redux/studio.js
  src/views/studio/lib/studio-member-actions.js
  src/views/studio/modals/transfer-host-confirmation.jsx
  src/views/studio/modals/transfer-host-selection.jsx
  src/views/studio/studio-member-tile.jsx
  test/helpers/state-fixtures.json
  test/unit/redux/studio-member-actions.test.js
  test/unit/redux/studio-permissions.test.js
Labels: pr - good to merge

#6084 Remove use of studio-related feature flags
  src/redux/session.js
  src/views/preview/subactions.jsx
  src/views/studio/studio-member-tile.jsx
Labels: pr - good to merge

#6085 Credits page update 9 21
  src/views/credits/credits.jsx
  src/views/credits/people.json
Labels: pr - needs review

#6097 Allow admins to promote curators to managers
  src/redux/studio-permissions.js
  test/unit/redux/studio-permissions.test.js
Labels: pr - good to merge

#6110 Update Release Workflow
  .github/workflows/main.yml
Labels: pr - good to merge

#6117 Show "Studio Host" on manager tile
  src/views/studio/studio-member-tile.jsx
Labels: pr - good to merge
