Repository scratchfoundation/scratch-www, pull requests merged in 2021-01, with the labels that each got.

#4779 Add new mute message types
  src/components/modal/mute/modal.scss
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/l10n.json
  test/unit/components/compose-comment.test.jsx
Labels: pr - good to merge

#4737 In the Annual Report Team section, open link to Scratch Team members in new tab
  src/components/people-grid/people-grid.jsx
  src/views/annual-report/annual-report.jsx
Labels: pr - good to merge

#4736 World map fixes - Border thickness, Eswatini, remove unused css
  src/components/world-map/world-map.jsx
  src/views/annual-report/annual-report.jsx
  src/views/annual-report/annual-report.scss
Labels: pr - good to merge

#4814 Add Tracy to credits page and Annual Report team section.
  src/views/annual-report/people.json
  src/views/credits/people.json
Labels: pr - good to merge

#4819 [Master] Release 2021-01-07
  .circleci/config.yml
  package-lock.json
  package.json
  src/components/modal/mute/modal.jsx
  src/components/people-grid/people-grid.jsx
  src/components/registration/steps.jsx
  src/components/world-map/world-map.jsx
  src/l10n.json
  src/lib/format-time.js
  src/lib/validate.js
  src/main.scss
  src/views/annual-report/annual-report.jsx
  src/views/annual-report/annual-report.scss
  src/views/annual-report/people.json
  src/views/credits/people.json
  src/views/dmca/dmca.jsx
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/l10n.json
  static/svgs/commenting/warning.svg
  test/unit/components/compose-comment.test.jsx
  test/unit/components/mute-modal.test.jsx
  test/unit/lib/format-time.test.js
Labels: release

#4828 Add back new automod messaging
  src/components/modal/mute/modal.scss
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/l10n.json
  test/unit/components/compose-comment.test.jsx
Labels: pr - good to merge

#4832 Remove use of FormattedHTMLMessage in Annual Report
  src/views/annual-report/annual-report.jsx
Labels: pr - good to merge

#4078 Add noscript tag
  src/template.ejs
Labels: blocked, pr - needs review, priority 4

#4827 Update vertical spacing on mute modal
  src/components/modal/mute/modal.scss
Labels: pr - good to merge

#4843 Update SEC page content
  src/views/sec/l10n.json
  src/views/sec/sec.jsx
  src/views/sec/sec.scss
  static/images/sec/SEC-Top-img.svg
  static/images/sec/SEC-bottom-image.png
  static/images/sec/SEC-bottom-img.svg
  static/images/sec/SEC-top-image.png
  static/images/sec/apply-icon.svg
Labels: pr - good to merge

#4764 Add a timeout to stop displaying the mute status when a mute expires.
  src/views/preview/comment/compose-comment.jsx
  test/unit/components/compose-comment.test.jsx
Labels: pr - good to merge

#4880 Show correct mute messaging instead of always the general message
  src/views/preview/comment/compose-comment.jsx
Labels: pr - good to merge

#4831 Update 1.4 Copytext
  src/views/scratch_1.4/l10n.json
Labels: blocked, pr - needs review

#4887 revise maintenance page to be 3.0 styled, update download links
  static/cdn/maintenance.html
  static/svgs/comment.svg
  static/svgs/extensions/android-grey.svg
  static/svgs/extensions/chromeos-grey.svg
  static/svgs/extensions/mac-grey.svg
  static/svgs/extensions/windows-grey.svg
  static/svgs/reload.svg
Labels: pr - good to merge

#4900 Auto mod/update copy
  src/components/commenting-status/commenting-status.scss
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/l10n.json
  test/unit/components/compose-comment.test.jsx
  test/unit/components/mute-modal.test.jsx
Labels: pr - good to merge

#4919 Set comment post and cancel buttons to be disabled when user is muted.
  src/views/preview/comment/compose-comment.jsx
  test/unit/components/compose-comment.test.jsx
Labels: pr - good to merge

#4928 Hotfix - Changed text on SEC page
  src/views/sec/l10n.json
Labels: pr - needs review
