Repository scratchfoundation/scratch-www, pull requests merged in 2021-12, with the labels that each got.

#6351 Fix flaky comments tests
  package-lock.json
  package.json
  test/integration/comments.test.js
  test/integration/my-stuff.test.js
  test/integration/project-page.test.js
  test/integration/selenium-helpers.js
  test/integration/sign-in-and-out.test.js
  test/integration/studios-page.test.js
Labels: pr - good to merge

#6364 Remove run in band from integration tests
  package.json
  test/integration/comments.test.js
  test/integration/footer-links.test.js
  test/integration/homepage-rows.test.js
  test/integration/join.test.js
  test/integration/my-stuff.test.js
  test/integration/navbar.test.js
  test/integration/project-page.test.js
  test/integration/search.test.js
  test/integration/sign-in-and-out.test.js
  test/integration/statistics.test.js
  test/integration/studios-page.test.js
Labels: pr - good to merge

#6355 App privacy policy
  src/routes.json
  src/views/privacypolicy-apps/l10n.json
  src/views/privacypolicy-apps/privacypolicy-apps.jsx
Labels: pr - good to merge

#6370 Update selenium webdriver
  package-lock.json
  package.json
  test/integration/join.test.js
Labels: pr - good to merge

#6368 Correct link href for studio host transfer message
  src/views/studio/studio-activity.jsx
Labels: pr - good to merge

#6376 circleci add build_pr job that runs on prs, old build doesn't run on prs
  .circleci/config.yml
Labels: pr - needs review

#6372 use large resource_class in CircleCI build job
  .circleci/config.yml
Labels: pr - needs review

#6374 [Master] Add configuration for GTM
  .circleci/config.yml
  src/template-config.js
  src/template.ejs
Labels: pr - good to merge, hotfix

#6375 [Develop] Add configuration for GTM
  .circleci/config.yml
  src/template-config.js
  src/template.ejs
Labels: pr - good to merge, hotfix

#6311 fix(gh-5989): adjust comment load batch size
  src/redux/studio-comment-actions.js
Labels: pr - good to merge
