Repository scratchfoundation/scratch-www, pull requests merged in 2021-05, with the labels that each got.

#5306 Studio info styling
  src/redux/studio.js
  src/views/studio/studio-description.jsx
  src/views/studio/studio-follow.jsx
  src/views/studio/studio-image.jsx
  src/views/studio/studio-info.jsx
  src/views/studio/studio-tab-nav.jsx
  src/views/studio/studio-title.jsx
  src/views/studio/studio.jsx
  src/views/studio/studio.scss
Labels: pr - good to merge

#5287 circleci turn on translation push cron job
  .circleci/config.yml
Labels: pr - good to merge

#5330 Add functionality for adding/removing projects and managing curators
  src/redux/studio-permissions.js
  src/redux/studio.js
  src/views/studio/lib/fetchers.js
  src/views/studio/lib/studio-member-actions.js
  src/views/studio/lib/studio-project-actions.js
  src/views/studio/studio-curator-invite.jsx
  src/views/studio/studio-curator-inviter.jsx
  src/views/studio/studio-curators.jsx
  src/views/studio/studio-managers.jsx
  src/views/studio/studio-member-tile.jsx
  src/views/studio/studio-project-adder.jsx
  src/views/studio/studio-project-tile.jsx
  src/views/studio/studio-projects.jsx
  src/views/studio/studio.jsx
  src/views/studio/studio.scss
  test/helpers/state-fixtures.json
  test/unit/redux/studio-permissions.test.js
Labels: pr - good to merge

#5336 Run npm ci in update-translations cron on circle
  .circleci/config.yml
Labels: pr - good to merge

#5316 Studio reporting using legacy endpoint
  src/redux/studio-report.js
  src/views/studio/studio-info.jsx
  src/views/studio/studio-report.jsx
  src/views/studio/studio.jsx
Labels: pr - good to merge

#5357 update method of checking goodlist of pages for banned user to see (2nd try)
  src/redux/session.js
Labels: pr - needs review

#5345 add donate banner, make close button a mode of button component
  src/_colors.scss
  src/components/forms/button.jsx
  src/components/forms/button.scss
  src/views/splash/donate/donate-banner.jsx
  src/views/splash/donate/donate-banner.scss
  src/views/splash/l10n.json
  src/views/splash/presentation.jsx
  src/views/splash/splash.jsx
Labels: pr - good to merge

#5331 Changed Developers and Teacher FAQ pages
  src/views/developers/developers.jsx
  src/views/developers/l10n.json
  src/views/teachers/faq/faq.jsx
  src/views/teachers/faq/l10n.json
Labels: pr - good to merge

#5392 Fixes to Developers' Page
  src/views/developers/developers.jsx
  src/views/developers/l10n.json
Labels: pr - needs review

#5391 fix logic for when to show intro to users
  src/views/splash/splash.jsx
Labels: pr - good to merge

#5404 Studio open toggle
  src/components/forms/toggle-slider.jsx
  src/views/studio/l10n.json
  src/views/studio/studio-comments-allowed.jsx
  src/views/studio/studio-comments.jsx
  src/views/studio/studio-open-to-all.jsx
  src/views/studio/studio-projects.jsx
  src/views/studio/studio.scss
Labels: pr - needs review

#5405 Outlines for avatars
  src/views/preview/comment/comment.scss
Labels: pr - needs review

#5397 Bug fixes from studio playground test on May 12
  src/views/studio/l10n.json
  src/views/studio/lib/studio-project-actions.js
  src/views/studio/modals/user-projects-modal.scss
  src/views/studio/studio-curator-inviter.jsx
  src/views/studio/studio-project-adder.jsx
Labels: pr - good to merge

#5401 Show "students projects" filter on studio project browser
  src/redux/session.js
  src/redux/studio.js
  src/views/studio/l10n.json
  src/views/studio/lib/user-projects-actions.js
  src/views/studio/modals/user-projects-modal.jsx
Labels: pr - good to merge

#5388 Add error display for studio curator and project adder inputs
  src/components/forms/validation-message.jsx
  src/redux/studio-mutations.js
  src/views/studio/l10n.json
  src/views/studio/studio-curator-inviter.jsx
  src/views/studio/studio-description.jsx
  src/views/studio/studio-image.jsx
  src/views/studio/studio-project-adder.jsx
  src/views/studio/studio-title.jsx
  src/views/studio/studio.scss
Labels: pr - needs review

#5381 Studio tile overflow menu
  src/components/overflow-menu/overflow-icon.svg
  src/components/overflow-menu/overflow-menu.jsx
  src/components/overflow-menu/overflow-menu.scss
  src/views/components/components.jsx
  src/views/components/components.scss
  src/views/components/example-icon.svg
  src/views/studio/icons/curator-icon.svg
  src/views/studio/icons/remove-icon.svg
  src/views/studio/l10n.json
  src/views/studio/studio-member-tile.jsx
  src/views/studio/studio-project-tile.jsx
Labels: pr - needs review

#5418 Bugfixes for studio playground test May 14
  src/components/overflow-menu/overflow-menu.jsx
  src/redux/studio-permissions.js
  src/views/studio/lib/studio-member-actions.js
  src/views/studio/modals/user-projects-modal.jsx
  src/views/studio/modals/user-projects-tile.jsx
  src/views/studio/studio-member-tile.jsx
  src/views/studio/studio-title.jsx
  src/views/studio/studio.scss
  test/unit/redux/studio-permissions.test.js
Labels: pr - good to merge

#5376 Finalize Circleci setup
  .circleci/config.yml
Labels: pr - good to merge

#5434 [Master] Hotfix Donate Banner Update
  src/views/splash/donate/donate-banner.jsx
  src/views/splash/splash.jsx
Labels: pr - good to merge, release

#5433 Use client-side image preview for studio thumbnail instead of server response
  src/redux/studio-mutations.js
  src/views/studio/studio-image.jsx
Labels: pr - good to merge

#5435 [Develop] Hotfix Donate Banner Update
  src/views/splash/donate/donate-banner.jsx
  src/views/splash/splash.jsx
Labels: release

#5438 Studio report modal
  src/redux/studio-report.js
  src/views/studio/l10n.json
  src/views/studio/modals/studio-report-modal.jsx
  src/views/studio/modals/studio-report-modal.scss
  src/views/studio/modals/studio-report-tile.jsx
  src/views/studio/studio-report.jsx
Labels: pr - good to merge

#5443 Use circleCI build ID for saucelabs test names instead
  test/integration-legacy/selenium-helpers.js
  test/integration/selenium-helpers.js
Labels: pr - good to merge

#5445 use Circle’s BUILD_NUM instead of WORKFLOW_ID in saucelabs tests
  test/integration-legacy/selenium-helpers.js
  test/integration/selenium-helpers.js
Labels: pr - good to merge

#5440 Linkify studio descriptions
  src/views/studio/studio-description.jsx
  src/views/studio/studio-image.jsx
  src/views/studio/studio-title.jsx
  src/views/studio/studio.scss
Labels: pr - changes requested

#5444 Studio admin panel
  src/views/studio/studio-admin-panel.jsx
  src/views/studio/studio.jsx
  src/views/studio/studio.scss
  test/unit/components/studio-admin-panel.test.jsx
Labels: pr - good to merge

#5461 Fix keyboard navigation in "add to studio" modal
  src/components/subnavigation/subnavigation.scss
  src/views/studio/modals/user-projects-modal.jsx
  src/views/studio/modals/user-projects-modal.scss
Labels: pr - good to merge

#4540 Move Navbar integration tests from Tap to Jest
  src/components/navigation/www/navigation.jsx
  test/integration-legacy/smoke-testing/test_navbar_links.js
  test/integration/navbar.test.js
Labels: pr - good to merge

#5476 Bump conference URL one year
  src/routes.json
Labels: pr - good to merge

#5478 Fix integration test broken in #5476
  test/integration/footer-links.test.js
Labels: pr - good to merge

#5436 Wait for session to be fetched before loading comments
  src/redux/session.js
  src/views/studio/studio-comments.jsx
  test/unit/components/studio-comments.test.jsx
Labels: pr - good to merge

#5437 Handle more types of project add errors
  src/views/studio/l10n.json
  src/views/studio/studio-project-adder.jsx
Labels: pr - good to merge

#5451 Alert component and studio error and success alerts
  src/components/alert/alert-component.jsx
  src/components/alert/alert-context.js
  src/components/alert/alert-provider.jsx
  src/components/alert/alert-status.js
  src/components/alert/alert.jsx
  src/components/alert/alert.scss
  src/components/alert/icon-alert-error.svg
  src/components/alert/icon-alert-success.svg
  src/views/components/components.jsx
  src/views/studio/l10n.json
  src/views/studio/lib/studio-member-actions.js
  src/views/studio/modals/user-projects-modal.jsx
  src/views/studio/modals/user-projects-tile.jsx
  src/views/studio/studio-curator-inviter.jsx
  src/views/studio/studio-curators.jsx
  src/views/studio/studio-managers.jsx
  src/views/studio/studio-member-tile.jsx
  src/views/studio/studio-project-adder.jsx
  src/views/studio/studio-project-tile.jsx
  src/views/studio/studio-projects.jsx
  src/views/studio/studio.scss
Labels: pr - good to merge

#5468 Studios stats and icons
  src/redux/studio.js
  src/views/studio/icons/activity-icon.svg
  src/views/studio/icons/comments-icon.svg
  src/views/studio/icons/followers-icon.svg
  src/views/studio/icons/last-updated-icon.svg
  src/views/studio/icons/projects-icon.svg
  src/views/studio/icons/report-icon.svg
  src/views/studio/l10n.json
  src/views/studio/studio-info.jsx
  src/views/studio/studio-report.jsx
  src/views/studio/studio-stats.jsx
  src/views/studio/studio-tab-nav.jsx
  src/views/studio/studio.scss
Labels: pr - needs review

#5466 Small fixes for "add to studio" modal
  src/views/studio/lib/user-projects-actions.js
  src/views/studio/modals/user-projects-modal.jsx
  src/views/studio/modals/user-projects-modal.scss
  src/views/studio/modals/user-projects-tile.jsx
  static/svgs/studio/check-icon-white.svg
  static/svgs/studio/plus-icon-white.svg
Labels: pr - needs review

#4792 set, purge static_assets surrogate key on deploy
  bin/configure-fastly.js
  package.json
Labels: caching, needs discussion, pr - good to merge

#5483 Update community guidelines
  src/views/guidelines/guidelines.jsx
  src/views/guidelines/l10n.json
Labels: pr - good to merge

#5439 Add dynamic meta tags for studio pages
  src/routes.json
  src/views/studio/studio-meta.jsx
  src/views/studio/studio.jsx
Labels: pr - good to merge

#5432 Update the curator invitation component to spec
  src/views/studio/l10n.json
  src/views/studio/lib/studio-member-actions.js
  src/views/studio/studio-curator-invite.jsx
  src/views/studio/studio-curators.jsx
  src/views/studio/studio.jsx
  src/views/studio/studio.scss
Labels: pr - changes requested

#5509 Fix the l10n version.
  package.json
Labels: pr - good to merge
