Repository scratchfoundation/scratch-www, pull requests merged in 2021-03, with the labels that each got.

#5058 Don't require a big phone number validation library on every page
  src/components/forms/phone-input.jsx
  src/components/forms/validations.jsx
  src/components/registration/phone-number-step.jsx
  src/components/registration/steps.jsx
  src/views/teacherregistration/teacherregistration.jsx
Labels: pr - good to merge

#5075 Create Plotly bundle to load only choropleth
  src/components/world-map/world-map.jsx
Labels: pr - good to merge

#5078 Content updates march 2021
  src/components/footer/www/footer.jsx
  src/components/page/www/donor-recognition.jsx
  src/l10n.json
  src/views/about/about.jsx
  src/views/about/about.scss
  src/views/about/l10n.json
  src/views/credits/credits.jsx
  src/views/credits/credits.scss
  src/views/credits/l10n.json
  src/views/credits/people.json
  static/images/about/around-the-world.png
Labels: pr - good to merge

#5088 Add spam mute message
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/l10n.json
Labels: pr - good to merge

#5077 Bump chromedriver version to 88, increase jest integration timeouts
  package-lock.json
  package.json
  test/integration/my-stuff.test.js
  test/integration/sign-in-and-out.test.js
Labels: pr - good to merge

#5104 Bump chromedriver version to 88, increase jest integration timeouts
  package-lock.json
  package.json
  test/integration/my-stuff.test.js
  test/integration/sign-in-and-out.test.js
Labels: pr - needs review

#5101 Removed unused dependencies
  package-lock.json
  package.json
  test/integration-cypress/.eslintrc
  test/integration-cypress/README.md
  test/integration-cypress/cypress.json
  test/integration-cypress/cypress/smoke-tests/test-footer-links.js
  test/integration-cypress/cypress/smoke-tests/test-navbar-links.js
  test/integration-cypress/package.json
Labels: pr - needs review

#5122 Pull changes from develop into release branch
  package-lock.json
  package.json
  src/components/footer/www/footer.jsx
  src/components/page/www/donor-recognition.jsx
  src/l10n.json
  src/views/about/about.jsx
  src/views/about/about.scss
  src/views/about/l10n.json
  src/views/credits/credits.jsx
  src/views/credits/credits.scss
  src/views/credits/l10n.json
  src/views/credits/people.json
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/l10n.json
  static/images/about/around-the-world.png
  test/integration-cypress/.eslintrc
  test/integration-cypress/README.md
  test/integration-cypress/cypress.json
  test/integration-cypress/cypress/smoke-tests/test-footer-links.js
  test/integration-cypress/cypress/smoke-tests/test-navbar-links.js
  test/integration-cypress/package.json
  test/integration/my-stuff.test.js
  test/integration/sign-in-and-out.test.js
Labels: release

#5126 [Master] Release 2021-03-11
  package-lock.json
  package.json
  src/components/footer/www/footer.jsx
  src/components/page/www/donor-recognition.jsx
  src/l10n.json
  src/views/about/about.jsx
  src/views/about/about.scss
  src/views/about/l10n.json
  src/views/credits/credits.jsx
  src/views/credits/credits.scss
  src/views/credits/l10n.json
  src/views/credits/people.json
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/l10n.json
  static/images/about/around-the-world.png
  test/integration-cypress/.eslintrc
  test/integration-cypress/README.md
  test/integration-cypress/cypress.json
  test/integration-cypress/cypress/smoke-tests/test-footer-links.js
  test/integration-cypress/cypress/smoke-tests/test-navbar-links.js
  test/integration-cypress/package.json
  test/integration/my-stuff.test.js
  test/integration/sign-in-and-out.test.js
Labels: release

#5127 [Develop] Release 2021-03-11
  src/views/about/about.jsx
  src/views/credits/credits.jsx
Labels: release

#5117 Add dev route with very bare studio playground
  package-lock.json
  package.json
  src/routes-dev.json
  src/views/studio/studio-activity.jsx
  src/views/studio/studio-comments.jsx
  src/views/studio/studio-curators.jsx
  src/views/studio/studio-info.jsx
  src/views/studio/studio-projects.jsx
  src/views/studio/studio-tab-nav.jsx
  src/views/studio/studio.jsx
Labels: pr - needs review

#5121 Made changes to conf 2020 page (fixed dependencies)
  src/views/conference/2020/index/index.jsx
  src/views/conference/2020/index/l10n.json
Labels: pr - good to merge

#5155 Fixed other place where date appears on Conference page
  src/views/conference/2020/index/index.jsx
Labels: pr - good to merge

#5149 Reusable redux module for fetching paginated data
  src/redux/infinite-list.js
  src/views/studio/debug.jsx
  src/views/studio/lib/fetchers.js
  src/views/studio/lib/redux-modules.js
  src/views/studio/studio-activity.jsx
  src/views/studio/studio-curators.jsx
  src/views/studio/studio-info.jsx
  src/views/studio/studio-projects.jsx
  src/views/studio/studio.jsx
  test/unit/redux/infinite-list.test.js
Labels: pr - good to merge

#5019 Circle ci configure tests
  .circleci/config.yml
  .gitignore
  package-lock.json
  package.json
Labels: pr - good to merge

#5166 When a user is already muted, show a different message in the blue box
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/l10n.json
  test/unit/components/compose-comment.test.jsx
Labels: pr - needs review

#5165 Made small updates to Scratch 2021 Conference page
  src/views/conference/2020/index/index.jsx
  src/views/conference/2020/index/l10n.json
  static/images/conference/index/2020/title-banner.jpg
Labels: pr - good to merge

#5164 Fetch studio info and roles in redux
  src/redux/studio.js
  src/views/studio/lib/fetchers.js
  src/views/studio/studio-info.jsx
  src/views/studio/studio.jsx
Labels: pr - good to merge

#5170 update eslint-config-scratch to 7.0.0
  package-lock.json
  package.json
Labels: pr - good to merge

#5171 Fix components page
  src/components/carousel/carousel.json
  src/views/components/components.jsx
Labels: pr - good to merge

#5175 Show different modal message when already muted
  src/l10n.json
  src/views/preview/comment/compose-comment.jsx
  test/unit/components/compose-comment.test.jsx
Labels: pr - changes requested

#5100 Extract comments reducer from preview reducer
  package.json
  src/redux/comments.js
  src/redux/preview.js
  src/redux/project-comment-actions.js
  src/views/preview/preview.jsx
  src/views/preview/project-view.jsx
  test/unit-legacy/redux/comments-test.js
  test/unit-legacy/redux/preview-test.js
Labels: pr - good to merge

#5177 circleci deploy to staging with circle instead of travis
  .circleci/config.yml
  .travis.yml
Labels: pr - good to merge

#5211 Add more components to the components page
  src/components/grid/grid.json
  src/views/components/components.jsx
  src/views/components/components.scss
Labels: pr - good to merge

#5216 [Master] Hotfix/totally normal 2021
  package-lock.json
  package.json
  src/components/cats/cats.jsx
  src/components/cats/cats.scss
  src/components/footer/www/footer.jsx
  src/components/grid/grid.jsx
  src/components/grid/grid.scss
  src/components/thumbnail/thumbnail.jsx
  src/components/thumbnail/thumbnail.scss
  src/template.ejs
  src/views/search/search.jsx
  static/images/cats/1.jpg
  static/images/cats/2.jpg
  static/images/cats/3.jpg
  static/images/cats/4.jpg
  static/images/cats/Cat1.jpg
  static/images/cats/Cat10.png
  static/images/cats/Cat11.png
  static/images/cats/Cat12.png
  static/images/cats/Cat13.png
  static/images/cats/Cat14.png
  static/images/cats/Cat2.jpg
  static/images/cats/Cat3.jpg
  static/images/cats/Cat4.jpg
  static/images/cats/Cat5.jpg
  static/images/cats/Cat6.png
  static/images/cats/Cat7.jpg
  static/images/cats/Cat8.jpg
  static/images/cats/Cat9.jpg
  static/images/cats/IMG_0071.jpg
  static/images/cats/IMG_0122.jpg
  static/images/cats/IMG_0135.jpg
  static/images/cats/IMG_0288.jpg
  static/images/cats/IMG_0504.jpg
  static/images/cats/IMG_0681.jpg
  static/images/cats/IMG_0684.jpg
  static/images/cats/IMG_0698.jpg
  static/images/cats/IMG_1092.jpg
  static/images/cats/IMG_1157.jpg
  static/images/cats/IMG_1463.jpg
  static/images/cats/IMG_1696.jpg
  static/images/cats/IMG_1977.jpg
  static/images/cats/IMG_2167.jpg
  static/images/cats/IMG_2507.jpg
  static/images/cats/IMG_2681.jpg
  static/images/cats/IMG_2775.jpg
  static/images/cats/IMG_2776.jpg
  static/images/cats/IMG_3218.jpg
  static/images/cats/IMG_4316.jpg
  static/images/cats/IMG_5396.jpg
  static/images/cats/IMG_5880.jpg
  static/images/cats/IMG_6020.jpg
  static/images/cats/IMG_6521.jpg
  static/images/cats/IMG_6558.jpg
  static/images/cats/IMG_9587.jpg
  static/images/cats/IMG_9766.jpg
  static/images/cats/IMG_9775.jpg
  static/images/cats/cat-meme.jpg
  static/images/cats/cat-meme2.jpg
  static/svgs/space-cat.svg
Labels: release
