Repository scratchfoundation/scratch-www, pull requests merged in 2021-02, with the labels that each got.

#4932 [Develop] Hotfix SEC Page Text Update
  src/views/sec/l10n.json
Labels: pr - needs review

#4938 Change time library to default to 1 minute when the time remaining is less than 30 seconds.
  src/lib/format-time.js
  test/unit/lib/format-time.test.js
Labels: pr - good to merge

#4901 Automod feedback modal steps
  src/components/modal/mute/feedback-form.jsx
  src/components/modal/mute/modal.jsx
  src/components/modal/mute/modal.scss
  src/l10n.json
  static/svgs/commenting/thank_you_envelope.svg
  test/unit/components/feedback-form.test.jsx
  test/unit/components/mute-modal.test.jsx
Labels: pr - good to merge

#4895 Add @formatjs/relativetimeformat-polyfill
  package-lock.json
  package.json
  src/lib/format-time.js
  src/lib/relative-time-polyfill.js
Labels: pr - good to merge

#4947 [Master] Release 2021-02-04
  package-lock.json
  package.json
  src/components/commenting-status/commenting-status.scss
  src/components/modal/mute/feedback-form.jsx
  src/components/modal/mute/modal.jsx
  src/components/modal/mute/modal.scss
  src/l10n.json
  src/lib/format-time.js
  src/lib/relative-time-polyfill.js
  src/views/preview/comment/compose-comment.jsx
  src/views/preview/l10n.json
  static/svgs/commenting/thank_you_envelope.svg
  test/unit/components/compose-comment.test.jsx
  test/unit/components/feedback-form.test.jsx
  test/unit/components/mute-modal.test.jsx
  test/unit/lib/format-time.test.js
Labels: release

#4943 Open mute modal from reply button if you're muted.
  src/components/modal/mute/modal.jsx
  src/views/preview/comment/comment.jsx
  src/views/preview/comment/compose-comment.jsx
  test/unit/components/compose-comment.test.jsx
Labels: pr - good to merge

#4982 Save automod feedback
  src/components/modal/mute/modal.jsx
  src/views/preview/comment/compose-comment.jsx
  test/unit/components/mute-modal.test.jsx
Labels: pr - good to merge

#4983 update feedback mistake message
  src/l10n.json
Labels: pr - needs review

#5001 [Master] Hotfix/dependency updates
  .travis.yml
  package-lock.json
  package.json
  src/components/registration/steps.jsx
  src/components/stepnavigation/stepnavigation.jsx
Labels: pr - needs review, release

#5002 [Develop] Hotfix/dependency updates
  .travis.yml
  package-lock.json
  package.json
  src/components/registration/steps.jsx
  src/components/stepnavigation/stepnavigation.jsx
Labels: release

#5013 Update to react 16.14
  package-lock.json
  package.json
  src/.eslintrc.js
  src/components/info-button/info-button.jsx
  src/components/modal/addtostudio/container.jsx
  src/views/teacherwaitingroom/teacherwaitingroom.jsx
  webpack.config.js
Labels: pr - good to merge

#5022 Change wording and image size on SEC page
  src/views/sec/l10n.json
  src/views/sec/sec.jsx
Labels: pr - good to merge

#5036 Update to Webpack 4
  package-lock.json
  package.json
  webpack.config.js
Labels: pr - changes requested
