Repository scratchfoundation/scratch-www, pull requests merged in 2022-04, with the labels that each got.

#6697 use node 16.14.2 in circleci and recommend 16
  .circleci/config.yml
  README.md
  package-lock.json
  test/unit/redux/studio-member-actions.test.js
Labels: pr - good to merge

#6727 Revert "[Master] [Hotfix] Totally normal 2022"
  package-lock.json
  package.json
  src/components/grid/grid.jsx
  src/components/oldtimey-mode/oldtimey-mode.jsx
  src/components/oldtimey-mode/oldtimey-mode.scss
  src/components/oldtimey-mode/projector.wav
  src/components/oldtimey-mode/projector2.mp3
  src/components/page/www/page.jsx
  src/components/thumbnail/thumbnail.jsx
  src/components/thumbnail/thumbnail.scss
  src/redux/reducer.js
  src/redux/time-travel.js
  src/views/preview/presentation.jsx
  src/views/preview/project-view.jsx
  src/views/search/Teleport3.wav
  src/views/search/search.jsx
  static/images/oldtimey.png
  static/svgs/space-cat.svg
  webpack.config.js
Labels: release

#6731 Display studio RTL for RTL languages
  src/views/studio/studio.jsx
  test/unit/views/studio.test.jsx
Labels: pr - needs review

#6646 Correct comment compose spacing
  src/components/commenting-status/commenting-status.scss
  src/views/preview/comment/comment.scss
  src/views/studio/studio-comments.jsx
  src/views/studio/studio.scss
Labels: pr - good to merge

#6745 Add messages for scratch week banner so they can be translated.
  src/views/splash/l10n.json
Labels: pr - needs review

#6741 Serve images from uploads instead of cdn2.
  .travis.yml
  src/components/avatar/avatar.jsx
  src/components/people-grid/people-grid.jsx
  src/views/annual-report/2019/blm-projects.json
  src/views/annual-report/2020/annual-report.jsx
  src/views/starter-projects/starter-projects.json
  webpack.config.js
Labels: pr - good to merge

#6738 2021 annual report (QA through map section)
  src/views/annual-report/2021/annual-report.jsx
  src/views/annual-report/2021/annual-report.scss
  src/views/annual-report/2021/l10n.json
  static/images/annual-report/2021/2_Access Section/Access Spotlight Story Illustration.svg
  static/images/annual-report/2021/2_Access Section/Deaf Kids Code Video.png
  static/images/annual-report/2021/3_Community Section/Languages illustration.svg
  static/images/annual-report/2021/3_Community Section/Scratch Lab video.png
  static/images/annual-report/2021/3_Community Section/Thank You Translators.svg
  static/images/annual-report/2021/3_Community Section/YT video spotlight video.png
Labels: pr - good to merge

#6748 Change placeholder name in AR string
  src/views/annual-report/2021/annual-report.jsx
  src/views/annual-report/2021/l10n.json
Labels: pr - good to merge

#6753 Make /annual-report use localization file of 2020 report
  src/routes.json
  src/template.ejs
Labels: pr - good to merge
