Repository scratchfoundation/scratch-www, pull requests merged in 2022-02, with the labels that each got.

#6471 Updated text on Code of Ethics page
  src/views/ethics/ethics.jsx
  src/views/ethics/l10n.json
Labels: pr - good to merge, blocked

#6494 webpack config make limit TerserPlugin to parallel: 4
  webpack.config.js
Labels: pr - good to merge

#6474 circle remove having separate jobs and caching
  .circleci/config.yml
Labels: pr - good to merge

#6518 Replace node sass
  package-lock.json
  package.json
  src/_colors.scss
  src/_frameless.scss
  src/components/card/card.scss
  src/components/carousel/carousel.scss
  src/components/dropdown-banner/banner.scss
  src/components/dropdown/dropdown.scss
  src/components/extension-landing/extension-landing.scss
  src/components/forms/validation-message.scss
  src/components/info-button/info-button.scss
  src/components/modal/base/modal.scss
  src/components/navigation/conference/2019/navigation.scss
  src/components/tooltip/tooltip.scss
  src/views/annual-report/2020/annual-report.scss
  src/views/developers/developers.scss
  src/views/download/download.scss
  src/views/parents/parents.scss
  src/views/studio/modals/studio-report-modal.scss
  src/views/studio/modals/user-projects-modal.scss
  src/views/teachers/landing/landing.scss
Labels: pr - good to merge

#6517 update sass-loader to version 10.2.1
  package-lock.json
  package.json
Labels: pr - good to merge

#6519 update postcss-loader to 4.2.0
  package-lock.json
  package.json
  webpack.config.js
Labels: pr - good to merge

#6533 Update webpack-dev-middleware and bunyan
  package-lock.json
  package.json
Labels: pr - good to merge

#6532 Update Autoprefixer to 10.4.2
  package-lock.json
  package.json
  webpack.config.js
Labels: pr - good to merge

#6538 Fixes styling of dropdown menu buttons for safari
  src/components/forms/select.scss
Labels: pr - good to merge

#6560 [Master] hotfix: bump scratch-gui for Scratch Link 1.4
  package-lock.json
  package.json
Labels: pr - good to merge, hotfix

#6563 create announce.js to announce deploys to slack
  bin/announce.js
  package.json
Labels: pr - needs review

#6522 modal css fix
  src/components/modal/email-confirmation/modal.jsx
  src/components/modal/email-confirmation/modal.scss
Labels: pr - good to merge

#6500 Scratcher Onboarding
  package-lock.json
  package.json
  src/components/not-available/not-available.jsx
  src/routes.json
  src/views/become-a-scratcher/become-a-scratcher.jsx
  src/views/become-a-scratcher/become-a-scratcher.scss
  src/views/become-a-scratcher/l10n.json
  src/views/messages/message-rows/scratcher-invite.jsx
  src/views/messages/presentation.jsx
  static/images/onboarding/community-guidelines.svg
  static/images/onboarding/congratulations-illustration.svg
  static/images/onboarding/create-a-project.svg
  static/images/onboarding/create-studios.svg
  static/images/onboarding/feedback-illustration.svg
  static/images/onboarding/friendly-illustration.svg
  static/images/onboarding/help-out.svg
  static/images/onboarding/honest-illustration.svg
  static/images/onboarding/invitation-illustration.svg
  static/images/onboarding/left-arrow.svg
  static/images/onboarding/left-lines.svg
  static/images/onboarding/profile-page-become-a-scratcher-button.svg
  static/images/onboarding/remix-illustration-1.svg
  static/images/onboarding/remix-illustration-2.svg
  static/images/onboarding/remix-illustration-3.svg
  static/images/onboarding/respect-illustration.svg
  static/images/onboarding/right-arrow.svg
  static/images/onboarding/right-lines.svg
  static/images/onboarding/safe-illustration.svg
  test/unit/components/become-a-scratcher.test.jsx
Labels: pr - good to merge
