Repository scratchfoundation/scratch-www, pull requests merged in 2022-01, with the labels that each got.

#6365 Email Confirmation on Project Page
  src/components/dropdown-banner/banner.scss
  src/components/dropdown-banner/email-confirmation/banner.jsx
  src/components/modal/email-confirmation/modal.jsx
  src/components/modal/email-confirmation/modal.scss
  src/l10n.json
  src/views/preview/presentation.jsx
  src/views/preview/project-view.jsx
  src/views/splash/presentation.jsx
  src/views/splash/splash.jsx
  static/svgs/modal/confirm-email-illustration.svg
  test/unit/components/email-confirmation-banner.test.jsx
  test/unit/components/email-confirmation-modal.test.jsx
Labels: pr - good to merge

#6431 Updates link in email confirmation modal
  src/components/modal/email-confirmation/modal.jsx
Labels: pr - good to merge

#6457 [Hotfix][Master] Fix issue with "see more replies" button on old studio comment threads with > 25 replies
  src/redux/comments.js
  src/redux/project-comment-actions.js
  test/unit-legacy/redux/comments-test.js
Labels: pr - good to merge, hotfix, release

#6458 [Develop] Hotfix - Fix for comment reply regression
  src/redux/comments.js
  src/redux/project-comment-actions.js
  test/unit-legacy/redux/comments-test.js
Labels: release

#6446 Use font weight bold consistently for teacher registration form labels
  src/components/forms/radio-group.jsx
  src/components/registration/steps.jsx
  src/components/registration/steps.scss
Labels: pr - good to merge
