Repository scratchfoundation/scratch-www, pull requests merged in 2022-07, with the labels that each got.

#6902 chore(deps):update dependency scratch-gui to 0.1.0-prerelease.20220706173215
  package-lock.json
  package.json
Labels: dependencies

#6894 removed ray, carl, karishma, bryce, katelyn, sarah. <3 <3 <3
  src/views/credits/people.json
Labels: pr - needs review

#6909 add macOS troubleshooting info on all extension pages
  src/components/extension-landing/extension-troubleshooting.jsx
  src/l10n.json
  src/views/boost/boost.jsx
  src/views/ev3/ev3.jsx
  src/views/gdxfor/gdxfor.jsx
  src/views/gdxfor/l10n.json
  src/views/microbit/microbit.jsx
  src/views/wedo2/wedo2.jsx
Labels: pr - good to merge
